### ISSUE TITLE
AppVar fails to transfer

### ISSUE THREAD

**Issue by adriweb** [CE-Programming/CEmu#101]
Bug reported by Epharius:

The attached appvar can be transferred fine with TI-Connect CE but fails on CEmu.
More precisely, it errors at [link.c:134](https://github.com/CE-Programming/CEmu/blob/49fdd4e3bf2c0fb820db0fc8020bace39b430c81/core/link.c#L134)
```c
temp_size = 4 + (size_t)data_size + (size_t)data_start;
if ((size_t)lSize != temp_size)                        goto r_err;
```
As one can see with a debugger, at this point we have:`lSize`: 197 ; `temp_size`: 70.

[TEST.8xv.zip](https://github.com/CE-Programming/CEmu/files/856686/TEST.8xv.zip)
_(Note: this appvar was created with tivars_lib, so maybe I did mess something up in the format, but at first (and quick) sight it appears correct)_

**Comment by MattWaltz** [comment]
Data at (0x48/9) has correct size bytes. Sizes at (0x39/A) and (0x46/7) are off by 1; need +2 for size bytes. Size at (0x35/6) should be 0x11+(0x48/9), but is no where close. "This number should be 57 (39h) bytes less than the file size." (which would be (0x8C->0x35, 0x00->0x36) in this case). This will also probably change the checksum of the file as well. TI Connect CE probably just doesn't do as many checks as CEmu.

**Comment by adriweb** [comment]
Alright, thanks for the investigation, I'll look into it within tivars_lib.
(I wonder if it's because of the odd/even size in Epharius' code modification, or just if somethign of mine is broken elsewhere in the overall file format handling)

**Comment by adriweb** [comment]
( [Fixed](https://github.com/adriweb/tivars_lib/commit/ee6fce95117c2ce1d3e08731cc80ed34ef804749?diff=unified) :) )
