### ISSUE TITLE
jr cc, X is off by 1

### ISSUE THREAD

**Issue by PeterTillema** [CE-Programming/CEmu#115]
The disassembling or jr cc, X is off by 1, for example it says that is jr to `XXXX0B`, while it actually jr to `XXXX0A`, which is right. Windows 10, 64bit version, 0.9dev_50326c6.

**Comment by MattWaltz** [comment]
Can't reproduce, need more information.

**Comment by PeterTillema** [comment]
Example, OS 5.2.1.0042 at $039A87, there is a 2804, which is jr z, $039A8E, while it does jump to $039A8D
https://i.imgur.com/sid7YsF.png

**Comment by MattWaltz** [comment]
Cannot reproduce. Is this from stepping through the code? How can I *reproduce* this; not just show me *what* the issue is.

![image](http://i.imgur.com/PGPe2aF.png)

**Comment by PeterTillema** [comment]
I just randomly clicked "Stop" when the cursor was flashing at the homescreen, then clicking once "Step" went to an interrupt, then stepping out, then just stepping until you see a jr cc, X :P

**Comment by MattWaltz** [comment]
I did that; and got the same results. I'm about ready to say that the build files aren't being cleaned or something for releases.

**Comment by MattWaltz** [comment]
Fixed

**Comment by adriweb** [comment]
(It was UB, which is why it was hard to reproduce)
