### ISSUE TITLE
Inquiry on Development

### ISSUE THREAD

**Issue by benjaminBrownlee** [CE-Programming/CEmu#118]
In the documentation of this project, it has been stated that there are "no stable binaries" to date and zero releases have been finalized.  This leaves me with a question: is this currently software safe and reliable? I wanted this emulator to simulate assembly language programs on the TI-84 CE that have a high potential for fatal crashes during build and debug.  However, if this software is not ready, I am not saving any time or hardware strain by crashing my computer instead of my calculator.  So, to be redundant, is this software ready for safe and reliable usage?

**Comment by mateoconlechuga** [comment]
Of course; it is entirely reliable and stable. You just need to download one of the build; you can get the latest windows ones here:

jacobly.com/CEmu/master/latest/CEmu64.exe
jacobly.com/CEmu/master/latest/CEmu32.exe

The only reason there are no actual releases is because there's no point until we get everything 100% perfect. As it is right now it is more than suitable for most needs.

**Comment by benjaminBrownlee** [comment]
Thanks for you reassurance.  I have a new laptop so I am a little protective.  So, as a follow up, when you do release your first version, will it still require the SDK to build and run?

**Comment by mateoconlechuga** [comment]
No it will be distributed just like the links I have posted above; although probably compressed. The links above will always give you the latest version; regardless of releases.

**Comment by PeterTillema** [comment]
These are the right links:
[64 bit](http://jacobly.com/CEmu/master/latest/CEmu64.exe)
[32 bit](http://jacobly.com/CEmu/master/latest/CEmu32.exe)

**Comment by benjaminBrownlee** [comment]
So the massive SDK that I downloaded to build and compile the application isn't needed and these links will give me a fully built and ready to use application?

**Comment by mateoconlechuga** [comment]
That's why they are in the readme as well; but yes.
