### ISSUE TITLE
Random RAM Clear [0.9dev_ea6bda5]

### ISSUE THREAD

**Issue by LemonJuiz** [CE-Programming/CEmu#122]
Title says it all. I load the ROM and after about 5 to 10 minutes the entire thing clears RAM, regardless of if keys were typed between first ROM load and clear or not. On build `0.9dev_ea6bda5` for Windows.

**Comment by mateoconlechuga** [comment]
That's not very descriptive. 5 to 10 minutes? So should I just clear out everything and start fresh and see what happens?

**Comment by LemonJuiz** [comment]
Yes as that is what I have done. I have loaded a ROM and done nothing and it clears and I have used the calculator and in the middle of use it clears.

**Comment by mateoconlechuga** [comment]
Awesome thank you :)

**Comment by mateoconlechuga** [comment]
What OS version are you using?

**Comment by LemonJuiz** [comment]
Windows 10.0.14393 Build 14393

**Comment by mateoconlechuga** [comment]
No, I mean calculator OS :)

**Comment by LemonJuiz** [comment]
Oh sorry, TI-84 Plus CE 5.2.2.0043.
And I can tell you because in the time I went to write this comment it cleared again :(
![image](https://user-images.githubusercontent.com/19430499/29303004-c7874f08-814e-11e7-8f06-2f01b977fdca.png)

**Comment by mateoconlechuga** [comment]
All right starting test now; I just pressed the [clear] key to make the  screen blank so I can detect it.

**Comment by mateoconlechuga** [comment]
Have you run any programs that may have modified the save state? Just to be sure choose the `Reload ROM` option under `Calculator`

**Comment by LemonJuiz** [comment]
I had not in some cases of clearing but in others I did run ASM code, specifically the [ICE Compiler](https://github.com/PeterTillema/ICE)

**Comment by mateoconlechuga** [comment]
The ICE Compiler may be triggering random resets; I have been running on Windows 10 with that OS revision and it doesn't appear to be reseting...

**Comment by LemonJuiz** [comment]
Even if it has, I do run the same 8xp on my real calculator and this problem does not occur. Sorry for the lack of reproduciblity, but something happens in CEmu that doesn't occur on hardware. Closed until specific procedures to reproduce are found.

**Comment by mateoconlechuga** [comment]
If it still appears to be reseting for you; would you mind following these steps:

    Open the `Debug` dock and click the `Stop` button
    Select the `Setup`tab
    Choose the `Open Debugger on Reset or NMI` checkbox
    Continue emulation by pressing the `Run` button

This should at least inform us where the error is :)

**Comment by LemonJuiz** [comment]
Ok

**Comment by adriweb** [comment]
Can't reproduce either (on a clean ROM, release build of ea6bda5)

**Comment by adriweb** [comment]
Okay, I might have reproduced it... by entering APD, which, for me happens whenever a demo is done running (at least, a version of gfx_shapes_shift)

Console trace: `[CEmu] Reset caused by resetting bit 1 of port 0x000D`.
This is from here: https://github.com/CE-Programming/CEmu/commit/a20062291d368f78f6a1c857cc498aa512ff9cbc#diff-b8972d6038b94efa930bd8cf51bc8bb4R161 
So, the emulation of this port behaviour might be incorrect there...

**Comment by LemonJuiz** [comment]
Ah, I see. At least it got resolved.
