### ISSUE TITLE
Ctrl-Shift-C shortcut key for screen capture

### ISSUE THREAD

**Issue by Stephan-P** [CE-Programming/CEmu#126]
It would be handy if CEmu would support a shortcut key for a quick screen capture to the paste bin, similar to GeoGebra's Ctrl-Shift-C

**Comment by mateoconlechuga** [comment]
Closed with 8072854. Ctrl-Shift-C now copies the current screen contents to the clipboard.

**Comment by Stephan-P** [comment]
NICE !

Stephan

Van: Matt Waltz<mailto:notifications@github.com>
Verzonden: zaterdag 7 oktober 2017 20:46
Aan: CE-Programming/CEmu<mailto:CEmu@noreply.github.com>
CC: Stephan Paternotte<mailto:stephan@paternottes.net>; Author<mailto:author@noreply.github.com>
Onderwerp: Re: [CE-Programming/CEmu] Ctrl-Shift-C shortcut key for screen capture (#126)


Closed with 8072854<https://github.com/CE-Programming/CEmu/commit/807285486beccf0d35c825a7bbe6a60277302b99>. Ctrl-Shift-C now copies the current screen contents to the clipboard.

**Comment by Stephan-P** [comment]
Ctrl-C is the keyboard shortcut for [prgm], showing me EXEC EDIT NEW.
Ctrl-Shift-C also takes me to [prgm].
No screen capture is copied to the clipboard.
The context menu: File - Copy screen to clipboard does function well.

**Comment by adriweb** [comment]
Did you try it from a new build ?
It’s working fine for me

**Comment by Stephan-P** [comment]
I used cemu-20171008_034959-git-fcaf086-win64-release-static which was the latest available this morning.
Meanwhile cemu-20171008_071851-git-e6c189e-win64-release-static seems to have the Ctrl-Shift-C as well as the context menu "Copy screen capture to clipboard" removed

**Comment by Stephan-P** [comment]
I’m using build cemu-20171008_034959-git-fcaf086-win64-release-static which I picked up this morning.

Stephan

**Comment by mateoconlechuga** [comment]
It should be fixed now with commit d133f1c. The build should update soon; so keep an eye out. Thanks for the report :)

**Comment by Stephan-P** [comment]
I just downloaded cemu-20171008_174606-git-83f2f46-win64-release-static, the youngest in the list.
When I try Ctrl-Shift-C first switches to [prgm] and then copies the screen to the clipboard.
I'm not sure I understand the building numbering, so I hope that this is one too early. I'll check again at a later stage.

**Comment by mateoconlechuga** [comment]
You are looking for where `83f2f46`-win64-release-static becomes `d133f1c`-win64-release-static :)

**Comment by alberthdev** [comment]
Try using [this page](http://alberthdev.github.io/CEmu/download) (specifically the MSVC tab), and the big "Download 64-bit" button - that should always get you the latest release, no matter what!

**Comment by Stephan-P** [comment]
Got d133f1c now. 
Ctrl-Shift-C no longer takes me to [prgm], but no screen is copied to the clipboard I'm afraid.

**Comment by mateoconlechuga** [comment]
Can confirm it works fine under linux. Starting windows vm to test.

**Comment by Stephan-P** [comment]
Had a screen capture app running, But also after closing it, no screen copied into the  clipboard.
Via the context menu "Copy screen to clipboard" functions fine.

**Comment by adriweb** [comment]
Considering the copied object is directly an image (and not an image _file_), try pasting it into an app like Paint or Word.

**Comment by mateoconlechuga** [comment]
Also try clicking on the emulated lcd screen before taking a screenshot.

**Comment by Stephan-P** [comment]
Copying into Word is my test enviroment.
 
Clicking the emulated screen is making the difference.
- Click screen and then Ctrl-Shift_C does the trick.
- Just clicking the app window (it needs to be the active app) and then Ctrl-Shift-C does NOT work.

Okay, now a bit more complex.
- CEMU restarted.
- First Ctrl-Shift-C does not work.
- Click emulator window and then Ctrl-Shift-C and it works.
- Following this, Ctrl-Shift-C works also without further clicking the emulator window.

**Comment by mateoconlechuga** [comment]
Hm so it is a focus issue. I'll look into fixing that.

**Comment by Stephan-P** [comment]
Jacobly's build of today:
Click CEmu app and press Ctrl-SHift-C still does NOT copy the screen to Word
Click CEmu screen and press Ctr-Shift-C does NOT copy the screen to Word
Repeated attempts of the above do NOT copy the screen to Word

Right-click the CEmu screen and choose menu option Copy screen to clipboard DOES copy the screen to Word.

Is Ctrl-Shift-C picked up at all in the Windows version?

**Comment by adriweb** [comment]
Note that you can now simply drag'n'drop the screen into Word (or elsewhere).  
Doesn't solve the potential key binding issue, but at least you know now...
