### ISSUE TITLE
[Debugger] "Step" doesn't behave as expected

### ISSUE THREAD

**Issue by PeterTillema** [CE-Programming/CEmu#132]
So I set a breakpoint at a certain address, and there was a normal OS call. Right after that was another call, but when I clicked "Step", it didn't go to that call, but it seems like it waits some time (a few ms at max), before it opens the debugger again, where I can continue stepping. Downloaded the latest 64-bits version.

<img src="https://i.imgur.com/shO8Urm.gif">

**Comment by PeterTillema** [comment]
Program: https://ufile.io/ptd7j
Debug state: https://ufile.io/rw98a

**Comment by mateoconlechuga** [comment]
Fixed by @jacobly0 on branch feature/lcd-spi
