### ISSUE TITLE
prgmDUMP cannot be sent 

### ISSUE THREAD

**Issue by Leo428** [CE-Programming/CEmu#135]
I am using a TI-84 Plus CE. I clicked save program and tried to send the program to my calculator through TI Connect CE. It failed. The error message was "A Token is invalid, so we are not able to open it".

**Comment by adriweb** [comment]
You have to transfer it, not open it. You can do so by drag'n'dropping the file onto calc name in the calculator explorer area of TI-Connect CE.

**Comment by Leo428** [comment]
Thank you very much!
