### ISSUE TITLE
Frameskip 0 option & recording to .webm/.mp4

### ISSUE THREAD

**Issue by KryptonicDragon** [CE-Programming/CEmu#136]
It'd be nice if CEmu supported frameskip 0, for 60fps recording, as well as recording to other formats like .webm or .mp4 (just examples).

**Comment by mateoconlechuga** [comment]
Frameskip 0 is now supported. I see no real point in adding video output support because of the multitude of online tools (e.g. **https://cloudconvert.com/gif-to-mp4**).

**Comment by adriweb** [comment]
(or just `ffmpeg` locally, which is a wonderful tool)

**Comment by mateoconlechuga** [comment]
^ That as well :)
