### ISSUE TITLE
Automated OBS builds, with libpng-apng

### ISSUE THREAD

**Issue by adriweb** [CE-Programming/CEmu#137]
Basically the same as Firebird here https://software.opensuse.org/download.html?project=home%3AVogtinator%3Afirebird-emu&package=firebird-emu
It would allow to have CEmu be available through the package manager on Arch, Debian, Fedora, openSUSE, and Ubuntu.
Once done, we should update the download page to mention that.

I'll probably poke @Vogtinator at some point for config issues...

**Comment by adriweb** [comment]
Finally done - https://build.opensuse.org/package/show/home:adriweb:CEmu/CEmu
Link to be added to the releases.

**Comment by adriweb** [comment]
Re-opening this, because we need libpng-apng too.

**Comment by adriweb** [comment]
Technically I did something (3a2591831f709b47c4b951f408adb7ef41e1a78d) that may set up libpng-apng correctly... but something's wrong (I get a segfault for png capture... and even png screenshot)
`0x00007fffe01aae00 in setup_png_transformations () from /lib64/libgdk_pixbuf-2.0.so.0`

Any idea?

**Comment by mateoconlechuga** [comment]
```
W: An error occurred during the signature verification. The repository is not updated and the previous index files will be used. GPG error: http://repository.spotify.com stable InRelease: The following signatures couldn't be verified because the public key is not available: NO_PUBKEY EFDC8610341D9410
W: GPG error: http://download.opensuse.org/repositories/home:/adriweb:/CEmu/xUbuntu_17.10  Release: The following signatures couldn't be verified because the public key is not available: NO_PUBKEY C018BCC26A836E4D
W: The repository 'http://download.opensuse.org/repositories/home:/adriweb:/CEmu/xUbuntu_17.10  Release' is not signed.
N: Data from such a repository can't be authenticated and is therefore potentially dangerous to use.
N: See apt-secure(8) manpage for repository creation and user configuration details
```

**Comment by adriweb** [comment]
All good, it finally worked :P

**Comment by adriweb** [comment]
I'm reusing this issue to let people know that the current release build is [available on OBS](https://software.opensuse.org//download.html?project=home%3Aadriweb%3ACEmu&package=cemu) for the following distros/versions/archs :)

(Note that for v2.0 we'll have to drop some of the older ones...)

<b>Arch</b> : x86_64
<b>CentOS_8</b> : x86_64 aarch64
<b>CentOS_8_Stream</b> : x86_64 aarch64
<b>Raspbian_9.0</b> : armv7l aarch64
<b>Raspbian_10</b> : armv7l aarch64
<b>Debian_9.0</b> : i586 x86_64 armv7l aarch64
<b>Debian_10</b> : i586 x86_64 armv7l aarch64
<b>Debian_Testing</b> : x86_64 i586 armv7l aarch64
<b>Debian_Unstable</b> : x86_64 i586 armv7l aarch64
<b>Fedora_25</b> : i586 x86_64
<b>Fedora_26</b> : x86_64 i586
<b>Fedora_27</b> : x86_64 i586 armv7l aarch64
<b>Fedora_28</b> : x86_64 i586 armv7l aarch64
<b>Fedora_29</b> : x86_64 i586 armv7l aarch64
<b>Fedora_30</b> : x86_64 i586 armv7l aarch64
<b>Fedora_31</b> : x86_64 armv7l aarch64
<b>Fedora_32</b> : x86_64 armv7l aarch64 ppc64le
<b>Fedora_33</b> : x86_64 armv7l aarch64 ppc64le
<b>Fedora_34</b> : x86_64 armv7l aarch64 ppc64le
<b>Fedora_Rawhide x86_64</b> : i586 armv7l aarch64
<b>SLE_15_SP1</b> : x86_64
<b>SLE_15_SP2</b> : x86_64
<b>SLE_15_SP3</b> : x86_64
<b>openSUSE_Factory_ARM</b> : armv7l aarch64
<b>openSUSE_Leap_15.0</b> : x86_64 aarch64 armv7l
<b>openSUSE_Leap_15.1</b> : x86_64 aarch64 armv7l
<b>openSUSE_Leap_15.2</b> : x86_64 aarch64 armv7l ppc64le
<b>openSUSE_Leap_15.3</b> : x86_64 aarch64 ppc64le
<b>openSUSE_Leap_42.2</b> : x86_64 armv7l aarch64
<b>openSUSE_Leap_42.3</b> : x86_64 i586 armv7l aarch64
<b>openSUSE_Tumbleweed</b> : i586 x86_64
<b>Ubuntu_16.04</b> : i586 x86_64
<b>Ubuntu_16.10</b> : i586 x86_64
<b>Ubuntu_17.04</b> : i586 x86_64
<b>Ubuntu_17.10</b> : i586 x86_64
<b>Ubuntu_18.04</b> : i586 x86_64
<b>Ubuntu_18.10</b> : i586 x86_64
<b>Ubuntu_19.04</b> : i586 x86_64
<b>Ubuntu_19.10</b> : i586 x86_64 armv7l aarch64
<b>Ubuntu_20.04</b> : i586 x86_64 armv7l aarch64
<b>Ubuntu_20.10</b> : i586 x86_64 armv7l aarch64
<b>Ubuntu_21.04</b> : i586 x86_64 armv7l aarch64
