### ISSUE TITLE
Record animated PNGs (MSVC builds)

### ISSUE THREAD

**Issue by runer112** [CE-Programming/CEmu#140]
Recording animated PNGs instead of or in addition to animated GIFs would be nice. It would remove the need for quantization to 256 colors, allowing for fully lossless recording and presumably making encoding easier.

**Comment by mateoconlechuga** [comment]
That would be rather neat :)

**Comment by adriweb** [comment]
FTR, from IRC:

We should use libpng with the apng patch: https://sourceforge.net/projects/libpng-apng/files/. Probably putting that on GitHub on a repo we'd use as a submodule.

Regarding symbol conflicts (since Qt already uses libpng), @jacobly0 proposes this: `SYMBOL_CFLAGS = -DPNGLIB_LIBNAME='APNG@PNGLIB_MAJOR@@PNGLIB_MINOR@_0' \`

**Comment by mateoconlechuga** [comment]
The main issue now is just fixing MSVC builds.

**Comment by adriweb** [comment]
Let's ping @alberthdev regarding MSVC :)

**Comment by alberthdev** [comment]
Is the GCC/Clang method still via doing custom symbol changes? Or is there another library that can be used for apng?

**Comment by adriweb** [comment]
Nope, all there is to it is:
- script to fetch the lib+patch and build+install it: https://github.com/CE-Programming/CEmu/blob/master/gui/qt/capture/get_libpng-apng.sh
- pkg-config stuff in the .pro file: https://github.com/CE-Programming/CEmu/blob/master/gui/qt/CEmu.pro#L48-L49

**Comment by alberthdev** [comment]
Finally done... QMake will now expect `LIBPNG_APNG_LIB`, `ZLIB_LIB`, and `LIBPNG_APNG_INCLUDE` to be defined (either in the environment or on the QMake command line) before allowing you to build. Note that this is only applicable to MSVC builds - MinGW/MSYS(2) builds will still require that the right things are installed and available in pkg-config (libpng, zlib) before building.
