### ISSUE TITLE
Can't run linux build, qt libs throwing errors

### ISSUE THREAD

**Issue by Lesquivemeau** [CE-Programming/CEmu#144]
Trying to launch CEmu on Ubuntu w/ ElementaryOS desktop env. but QT Libs keep throwing the same errors

(Installed the required libs, tried to install qt5-default as well but still can't launch CEmu)

![image](https://user-images.githubusercontent.com/26309108/33148216-43d44f46-cfcb-11e7-81ef-f4b2c2d709c7.png)

Thanks for your help

**Comment by nathanfarlow** [comment]
Same thing happening here. This might also be contributed to my general lack of knowledge of Linux, though :)

sudo apt-get install libqt5core5a libqt5network5 libqt5gui5 libqt5widgets5
Reading package lists... Done
Building dependency tree       
Reading state information... Done
libqt5core5a is already the newest version.
libqt5gui5 is already the newest version.
libqt5network5 is already the newest version.
libqt5widgets5 is already the newest version.
0 upgraded, 0 newly installed, 0 to remove and 0 not upgraded.

./CEmu
./CEmu: /usr/lib/x86_64-linux-gnu/libQt5Network.so.5: no version information available (required by ./CEmu)
./CEmu: /usr/lib/x86_64-linux-gnu/libQt5Gui.so.5: no version information available (required by ./CEmu)
./CEmu: /usr/lib/x86_64-linux-gnu/libQt5Core.so.5: no version information available (required by ./CEmu)
./CEmu: /usr/lib/x86_64-linux-gnu/libstdc++.so.6: version `GLIBCXX_3.4.21' not found (required by ./CEmu)
./CEmu: /usr/lib/x86_64-linux-gnu/libQt5Widgets.so.5: no version information available (required by ./CEmu)

**Comment by adriweb** [comment]
I assume you downloaded this linux build from @jacobly0's website?
He's saying it won't work for other people, because it's built in a special way for him... or something like that :P

Anyway, you can build CEmu yourself with the README instructions, and/or try to convince jacobly to host a static build :D

**Comment by mateoconlechuga** [comment]
For releases in the future, static builds will be provided across OSes to avoid this. For now; temporary builds have been removed from the download section, and linux users can just use the README instructions to build from the source. :)
