### ISSUE TITLE
ROM Dump Program Wont Open In TI-Connect Software

### ISSUE THREAD

**Issue by nice6599** [CE-Programming/CEmu#145]
**The ROM Dump Program Wont Open In TI-Connect Software**
When I use the TI-Connect software to load the rom dump program on to my calculator the software refuses to load the program 

<img width="526" alt="badtoken" src="https://user-images.githubusercontent.com/23456132/33716696-1d2eb056-db25-11e7-81af-3efce82323e6.png">

I am running the TI-Connect software on an external drive not a usb. disk speed is roughly Read/120mbps Write/100mbps (not sure if that matters) 

[Log.log](https://github.com/CE-Programming/CEmu/files/1539222/Log.log)

Note: error starts at 08:08:05.198448 and ends at 08:08:14.394157 

I'm not sure what to do next please some help here

**Comment by adriweb** [comment]
Just transfer the program (drag'n'drop it over the calc in the Calculator Explorer area), don't open it in the programe editor area.
