### ISSUE TITLE
Keypad holding timing

### ISSUE THREAD

**Issue by mateoconlechuga** [CE-Programming/CEmu#157]
It seems when emulating the keypad the delay timings are off when keys are held. Uploaded is the file needed to reproduce this behavior.

[DEMO.8xp.zip](https://github.com/CE-Programming/CEmu/files/1627038/DEMO.8xp.zip)
Source: http://www.rafb.me/results/1mjQwW40.html

**Comment by mateoconlechuga** [comment]
Updated the file.

**Comment by mateoconlechuga** [comment]
Some numbers: When a real calculator reaches 100, CEmu is only at 18. Thus, CEmu progresses only at 18% of the actual keypad speed.

**Comment by mateoconlechuga** [comment]
Fixed with a397974.

**Comment by mateoconlechuga** [comment]
This works fine on Linux and MacOS. And then comes lovely Windows, where is running at about 25% speed it seems.

**Comment by jacobly0** [comment]
Exactly 25% in fact, which suggests that it is using the wrong clock, or the clock rate got corrupted, but I'm having trouble figuring out a way to debug windows.
