### ISSUE TITLE
Update README for v1.0 Target

### ISSUE THREAD

**Issue by mateoconlechuga** [CE-Programming/CEmu#159]
We need to update the README with new pictures, information, and build instructions.

**Comment by mateoconlechuga** [comment]
New branch for changes before they go live: https://github.com/CE-Programming/CEmu/tree/feature/readme

**Comment by mateoconlechuga** [comment]
Just needs updated screenshots :)

**Comment by adriweb** [comment]
Okay, I've updated the macOS screenshot, it shows a simple setup, with a 83PCE.

@mateoconlechuga can you do a Windows one showing debug stuff on a 84+CE (without the keypad if you want, but with fancy things like mem visualizer(s), etc.) ?
@jacobly0 or @mateoconlechuga can you do a Linux one with some mixed standard-debug layout maybe, but with the keypad (then whatever else you want).

For the screenshots themselves, like now they should be a transparent PNG with a small shadow, and 280px of height (with a reasonable width) for the thumbnail version.

(and update the readme when you do... then we can (squash-)merge the branch and close this issue :D)

**Comment by adriweb** [comment]
Thanks, readme updated with our screenshots.

All done, feature/readme branch merged, via https://github.com/CE-Programming/CEmu/pull/169
