### ISSUE TITLE
Emulator interaction with the outside world

### ISSUE THREAD

**Issue by debrouxl** [CE-Programming/CEmu#16]
Issue #15 mentions a set of use cases for cooperation _inside_ the emulated environment; there's also a set of use cases for cooperation _outside_ the emulated environment.

Here are several suggestions:
- the ability to send files to the emulator, trigger keypresses, retrieve a snapshot of the console / a subset of the addressing space and MMIO / whatever, stream events to the outside in a publish-subscribe fashion (console, processor exceptions, data watches, etc.);
- the ability to communicate with real calculators;
- the ability to communicate with virtual calculators.

Existing practices and code bases in community code bases include:
-  TIEmu's D-Bus interface (interoperable but relatively complex and heavyweight) and OLE interface (platform-specific) make it possible to e.g. send files to the emulator;
- the portable libti\* stack takes care of lower and higher layers of communication with real and virtual calculators. TIEmu and TilEm use it.

Other technical options include, but are far from limited to:
- ZeroMQ for transporting messages, or maybe its newer nanomsg offspring, whose future is more cloudy;
- Cap'n Proto for message definition, serialization and deserialization, or its better-known, much more heavyweight Protocol Buffers ancestor.

Of course, I'm biased by having been the maintainer (not the creator) of both libti\* and TIEmu for 6 years and a half. But libti\* stack, where I'm focusing instead of the unmaintainable TIEmu mess, is the community's GPL'ed reference implementation of a calculator <-> computer communication stack. While it's not perfect, it has a significant number of good things, I / Benjamin Moody / Jonimus (mainly, plus contributors) have been improving it a lot over time, and it's not wise to shun it entirely.

Like in issue #15, more brainstorming is needed, then we'll be able to create multiple, more focused issues :)

**Comment by elfprince13** [comment]
The downside of using some MMIO range is that it would be more difficult to reliably structure commands (i.e. We would need a protocol instead of just reading PC+n bytes).

**Comment by adriweb** [comment]
I'll note here that while it's not interaction once launched, it's somewhat related: there was talk, on #cemu-dev, about possible CLI parameters for CEmu when launching it.
Idea included which ROM to load, which file to send once ready and possibly which keys to press after that, which GUI setup to use etc.
This should probably be a new issue in itself so that it can be tracked as a todo/wish-list item, though :)

**Comment by MateoConLechuga** [comment]
In order to actually do this; need USB support from issue #25 :) Hopefully that will come with time.

**Comment by adriweb** [comment]
At least regarding keypresses and such, I've exposed two functions so far, to send keyCodes and letters, see [extras.h/.c](https://github.com/CE-Programming/CEmu/blob/master/core/extras.h)

**Comment by MateoConLechuga** [comment]
These functions only work within the OS though. It would be better to
support the hardware directly as the Qt GUI does, simply by using arrays
and indexes.

**Comment by adriweb** [comment]
Well, `keypad_key_event` works fine for that already :)
Unless you mean another abstraction layer on top of that.

**Comment by MateoConLechuga** [comment]
Ah, I see. Good enough for me :) Nice work

**Comment by adriweb** [comment]
Update: @MattWaltz added IPC with 4937756.
An example use case that works right now is to send files from one instance to another, at least from the command-line.

**Comment by adriweb** [comment]
Closing this for now, to re-open if needed.
(Note: it'd probably be good to use 5.5 instead of 5.6 [here](https://github.com/CE-Programming/CEmu/commit/493775627bb9a2b77c4960081fb5eb3883cb0c5f#diff-ef62af2c016b9e0bc79e7a0a752151e8R1577))
