### ISSUE TITLE
Update Translations for v1.0 Target

### ISSUE THREAD

**Issue by mateoconlechuga** [CE-Programming/CEmu#160]
French and Spanish Translations need to be updated for the v1.0 Target.

**Comment by adriweb** [comment]
French done - https://github.com/CE-Programming/CEmu/commit/2d45836d87bd4c673b1611495d1328c5540dad3c

**Comment by mateoconlechuga** [comment]
Spanish done - fe524b8 
Dutch done - 018e2ab
