### ISSUE TITLE
Update webpage for v1.0 release

### ISSUE THREAD

**Issue by mateoconlechuga** [CE-Programming/CEmu#162]
We should make it possible to link the "stable" releases as well maybe? At the very least it would be nice to have static linux builds, maybe even mac development builds as well.

**Comment by alberthdev** [comment]
Do we want to put our v1.0 release binaries on GitHub, and then just link to them from our webpage?

**Comment by mateoconlechuga** [comment]
Sure, that would be nice. Perhaps a section for "stable", and a section for "development".

**Comment by adriweb** [comment]
Well, stable binaries will be on GitHub releases (+ probably OBS), and dev ones will be provided by jacobly+alberhtro as usual, I think that's the simplest plan :)

**Comment by alberthdev** [comment]
If we do decide to go for that, I think we can just segment the pages out - one page (/download/) to indicate whether the user wants a release build or dev build, then two separate pages (/download/release, /download/dev) for handling each. We should be able to leverage the GitHub REST API for fetching release information as well... with some caching of course to prevent the user from inadvertently hitting the rate limit via F5 mashing!

**Comment by adriweb** [comment]
Heh I'm not sure if there's going to be that many github releases (that often, I mean), so you probably don't have to worry about implementing some REST API fetching, come good old copy/paste at each release is probably fine for now...

**Comment by mateoconlechuga** [comment]
It would also be nice if the gh_pages branch was updated with the latest commit/date information for development builds :)

**Comment by adriweb** [comment]
I've changed a few minor things, but @alberthdev it'd be nice if you could put the MSVC builds by default for Windows on the dev. builds download page (which alro requires a few rephrasing, I suppose) :)
Also, I noticed a little bug: when the window is small, it correctly gets re-layouted, but the sidebar/menu doesn't actually work then, there's a grey overlay blocking clicks :P

If you could do this before Sunday it'd be great :D

**Comment by mateoconlechuga** [comment]
This looks great! I feel like the issue is good enough for a close now :)
