### ISSUE TITLE
Update Qt version for automated MSVC builds

### ISSUE THREAD

**Issue by adriweb** [CE-Programming/CEmu#165]
Needs to be Qt 5.10 :)

(jacobly's builds, as well as mine, are already using that version, so only the win msvc ones are needed now)

**Comment by adriweb** [comment]
This isn't actually critical for the 1.0 release, changing the target.

**Comment by mateoconlechuga** [comment]
@alberthdev I broke things :D b67fcc4

**Comment by adriweb** [comment]
We'll need this for the 1.1 version @alberthdev ; hopefully soon :D

**Comment by alberthdev** [comment]
I recommend an amazing command that will fix all of your problems:

    sed -i 's/5\.10/5\.6/g' appveyor.yml

Presto! MSVC builds will work again, and you'll get an "updated" Qt!

(In all seriousness, will try to get to it soon... need to update my VM side and clean it up a bit before resuming development.)

**Comment by alberthdev** [comment]
With commits cd4c04 to 90b59d, we should now be at Qt v5.10.1. Please test the binaries that are located [here](https://oss.jfrog.org/artifactory/oss-snapshot-local/org/github/alberthdev/cemu/git/201803/20180330/cemu-20180330_024247-git-90b59d2/). Future incremental commits will use Qt v5.10.1 from now on.

If everything looks good, let's (finally) close this out! :D

**Comment by mateoconlechuga** [comment]
Seems to work great on my end :)

**Comment by adriweb** [comment]
So hmm, I've gone crazy and actually ran all the builds, they all seem to function as expected!
Good job and thanks :P

(One thing I've noticed, but that's probably not Qt 5.10's fault, is that at least one of the APNG capture is [way too fast](https://i.imgur.com/MQlK1ee.png))

Closing this now, I guess :)
