### ISSUE TITLE
Opening CEmu bug

### ISSUE THREAD

**Issue by jcgter777** [CE-Programming/CEmu#168]
Thanks to (I think) @adriweb and @mateoconlechuga , I got CEmu to "open", and bypass the security settings on my mac. But, now, everytime I open it, it instantly crashes. (I don't even see anything. Direct error message) I just get an error that CEmu quit unexpectedly.

**Comment by adriweb** [comment]
Running the binary witin the Terminal may give you more info, but anyway there will be another release soon than you can try.
If it still doesn't work (while confirmed to work for others), the issue is probably coming from your computer...

**Comment by jcgter777** [comment]
I'll wait for the next release!
