### ISSUE TITLE
Control freezing / speed issues

### ISSUE THREAD

**Issue by mateoconlechuga** [CE-Programming/CEmu#173]
Sometimes the controls for frameskip and emulation speed don't seem to respond. This is usually due to leaving CEmu for a bit and doing other things while it is in the background. Also, CEmu dips in performance to around 50% when running heavy programs.

**Comment by mateoconlechuga** [comment]
When CEmu is left running for some time, the LCD refuses to update along with the reported emulated speed and FPS.

**Comment by mateoconlechuga** [comment]
Heavy program:

[bin.zip](https://github.com/CE-Programming/CEmu/files/1712676/bin.zip)

**Comment by adriweb** [comment]
Looks like it's better for me now, no random crashes and still 100% speed even with SPI.

**Comment by mateoconlechuga** [comment]
I still feel like it is all ub :P

**Comment by mateoconlechuga** [comment]
This is better, but still needs a QMutex for protection of the lcd image. Maybe? idk.
