### ISSUE TITLE
"Other CEmu detected" crashes

### ISSUE THREAD

**Issue by PeterTillema** [CE-Programming/CEmu#175]
I downloaded the latest CEmu, but whenever I opened it, the message "Other CEmu detected" popped up (only a title bar, no content in the pop up), and then CEmu crashed. Do I need to delete anything?

**Comment by adriweb** [comment]
Nope, not fixed here (actually it was fine before, but not anymore :P)

```
CEmu(22542,0x7fffac907340) malloc: *** error for object 0x115dfa000: pointer being freed was not allocated
*** set a breakpoint in malloc_error_break to debug
```

This happened when I just wanted to close that window (and why does it just have an OK button only?)
![](https://i.imgur.com/prmLCou.png)
