### ISSUE TITLE
In macOS version, when "resetting", it just quits. 

### ISSUE THREAD

**Issue by jcgter777** [CE-Programming/CEmu#180]
When I press either "Reset CEmu" or "Reset UI Docks", it just quits the app. Can you make it just reload the app?

**Comment by mateoconlechuga** [comment]
It should reload the application? I'm not sure why it isn't, Adriweb will need to look into that. If you just want to reset the calculator, select `Calculator > Reset Calculator`

**Comment by jcgter777** [comment]
I know how to reset the calc. It's even easier than that. There's a `RESET` Button!!!

I _am_ confused why it doesn't reload the app.

**Comment by adriweb** [comment]
Can't reproduce, works as expected here.
(Same with your "Saving failed" issue you reported on Cemetech).

Might be related to your OS being too old, idk.

**Comment by adriweb** [comment]
If you're able to launch this from a debugger, however (`lldb` I guess), it might help tracking down the issue if it's a crash. I could send you a build with symbols or even a debug build to see if it still happens.

Also, open a terminal and run this: `[path]/CEmu.app/Contents/MacOS/CEmu`, by replacing `[path]` by where the app is. Then copy/paste what you may see when it quits unexpectedly.

**Comment by jcgter777** [comment]
Alright!

**Comment by jcgter777** [comment]
Nothing comes up. It's not an "unexpected quit" It just quits.

**Comment by mateoconlechuga** [comment]
I also cannot reproduce :/

**Comment by jcgter777** [comment]
@mateoconlechuga What happens for you? Just quit? Or reload?

**Comment by mateoconlechuga** [comment]
You need to look up the phrase "cannot reproduce"

**Comment by jcgter777** [comment]
No I don't

**Comment by mateoconlechuga** [comment]
![image](https://user-images.githubusercontent.com/9890252/36175875-baafe82e-10c5-11e8-80ea-25819ca7e249.png)

**Comment by jcgter777** [comment]
What the freak?

**Comment by mateoconlechuga** [comment]
Humor is wasted on the stupid.

**Comment by jcgter777** [comment]
Me, right?

**Comment by mateoconlechuga** [comment]
Exactly.

**Comment by jcgter777** [comment]
It's not funny. More like disgusting

**Comment by LAX18** [comment]
Well.... It IS pretty funny

**Comment by jcgter777** [comment]
Funny, but disgusting

**Comment by mateoconlechuga** [comment]
Thinking reproduction is disgusting is what is wrong with the world. It's the core purpose of life.

Anyway, this bug is not reproducible, and hence why the issue has been closed. It was recommended to upgrade your OS, so there is not much else we can do on this end.

**Comment by jcgter777** [comment]
Not reproducible.

**Comment by debrouxl** [comment]
Hmm... everybody take a small break from this issue and have, say, a walk to breathe ? ;)
