### ISSUE TITLE
Cycle counter counts down sometimes

### ISSUE THREAD

**Issue by PeterTillema** [CE-Programming/CEmu#182]
**Version**:
1.0

**Description (actual vs expected)**
In the debugger, the cycle counter can count down - it's only supposed to go up.
![Screenshot](https://i.imgur.com/wgv9Xup.gif)

**How to reproduce the issue:**
I managed to trigger it like this: just run AoCE and stop at a random time. Then zero the cycles and check the include DMA checkbox. Go up to about 400 cycles and then uncheck the checkbox.
Need to try a bit more with checking and unchecking it, because it's quite random.

More info from IRC:
<P_T> Actually, the first 'ldi' from ldir where the counter went below 0, it froze (stuck at -6) until the instruction after ldir
<P_T> If I check the 'Include DMA' checkbox, everything works fine, but it fails again when unchecking it

**Comment by adriweb** [comment]
BTW, the issue is around here: https://github.com/CE-Programming/CEmu/blob/master/core/debug/debug.cpp#L92

Some notes, even though there are several ways of fixing it:
```
<@jacobly> it should be debugger.dmaCycles += cpu.dmaCycles; ... debugger.dmaCycles -= cpu.dmaCycles;
<@jacobly> and then you just display debugger.totalCycles or debugger.totalCycles + debugger.dmaCycles
<@jacobly> during emulation, debugger.dmaCycles is basically whatever cpu.dmaCycles was when zero cycles was last clicked
<@jacobly> during debugging, debugger.dmaCycles is basically how many dma cycles have happened since zero cycles was last clicked
```
