### ISSUE TITLE
Update AppVeyor autobuilder to properly build release tags + deploy to GitHub release

### ISSUE THREAD

**Issue by alberthdev** [CE-Programming/CEmu#183]
From IRC:
```
<Adriweb> when appveyor is building a tag, it needs to pass that tag name as CEMU_VERSION=namehere
<Adriweb> as qmake arg
```

Also, deployment to GitHub release when things are done - builds may also get uploaded to the JFrog Bintray but maybe in a different folder structure due to the commit being a release.

**Comment by alberthdev** [comment]
From IRC:

```
<Adriweb> with those names, for the upload: windows_32bit_CEmu.zip and windows_64bit_CEmu.zip
<Adriweb> less confusing for people
```

(We won't use the usual development naming convention, for both GitHub release builds + JFrog ones.)

**Comment by adriweb** [comment]
I'm not really sure it's *that* useful to have the auto-upload to the release. I mean, it's just 2 files to download, rename, and reupload :P
Especially considering that until the release is actually published (and not as a draft), it's not public, so I'm not sure if it can see it and use it as a destination for the upload?

**Comment by adriweb** [comment]
Yep, it worked, congrats!
