### ISSUE TITLE
APNG recording is too fast

### ISSUE THREAD

**Issue by mateoconlechuga** [CE-Programming/CEmu#188]
Um yeah I have no idea what I did wrong...

**Comment by adriweb** [comment]
(Note: in the current state of things, APNG recording still works but the frame rate is incredibly slow, just in case someone was wondering if only one frame got saved)
Looks like I get one frame every 0.5*fps seconds (or maybe a bit faster) but that might be a coincidence

**Comment by mateoconlechuga** [comment]
Fixed with fbc4125d
