### ISSUE TITLE
'Add Memory View' not visible

### ISSUE THREAD

**Issue by PeterTillema** [CE-Programming/CEmu#189]
Whenever I click on 'Add Memory View', nothing appears. I have to restart CEmu to see it. I'm using Windows like always ;)

**Comment by adriweb** [comment]
Note: appears to be only on Windows.
Tested on macOS and Linux, the new windows shows up as expected.

**Comment by runer112** [comment]
I've also experienced this bug in the MSVC build of CEmu for Windows. The bug is not present in the MinGW build.
