### ISSUE TITLE
Panels that cannot make use of vertical expansion should not expand vertically

### ISSUE THREAD

**Issue by runer112** [CE-Programming/CEmu#190]
Panels that do not contain any vertically expanding elements and merely add empty space when expanded vertically should not expand vertically when competing for the space with panels that do have vertically expanding elements.

These are the offending panels:

 * AutoTester 
 * Capture
 * CPU Status
 * Debug Control
 * Miscellaneous
 * Settings

Tested on MSVC and MinGW Windows builds.

**Comment by runer112** [comment]
IRC discussion about reproduction, a workaround, and limitations of the workaround:

> 16:04:10 <•Runer112> put capture and memory view in a vertical stack
16:04:23 <•Runer112> resize window vertically
16:04:41 <•Runer112> ideally, capture should not grow, as it can make no use of the space
16:04:54 <•Runer112> all the extra height should be given to other panels in the column first
16:05:18 <•MateoC> Okay that's a lot harder to do than it sounds
16:05:36 <•Runer112> I've played with qt creator, so I wouldn't be too surprised
16:05:53 <•Runer112> I imagine you'd have to somehow hook into whatever logic decides how to auto-resize stuff
16:06:08 <•MateoC> Yes
16:06:24 <•MateoC> But the point is you can do that yourself
16:06:35 <•Runer112> I can do what myself
16:06:56 <•Runer112> write the logic hook?
16:07:17 <•MateoC> No, just drag the spacer
16:07:33 <•Runer112> that's a workaround, not a fix
16:07:40 <•Runer112> also, doesn't work with edit mode disabled
16:08:18 <•Runer112> and then when you enable edit mode, drag it, and disable edit mode, the missing title bar space gets reallocated and screws it up again

**Comment by mateoconlechuga** [comment]
After a bit of testing, this is controllable via `widget()->setSizePolicy(w, h);`

This should just take a bit of fine-tuning to figure out how to make it work well.

**Comment by mateoconlechuga** [comment]
Reopened because the above panels inherit a "fixed" size, which means they aren't expandable.

**Comment by adriweb** [comment]
Looks like jacobly's commits fix all that.

At least on macOS (https://i.imgur.com/O6aVfB0.png) and windows/mingw (https://i.imgur.com/z3QgLsq.png) it looks fine.
Even though the drag'n'drop may appear a bit weird sometimes (https://gfycat.com/DentalGlitteringGallinule).

I also had to toggle edit mode twice for things to get correct, but in the end it works nicely.
