### ISSUE TITLE
Upon startup, all extra space in a vertical stack of panels is allocated to the topmost panel

### ISSUE THREAD

**Issue by runer112** [CE-Programming/CEmu#192]
Ideally, the distribution from the last run would be recalled. At minimum, it should be distributed equally.

Tested on MSVC and MinGW Windows builds.

**Comment by mateoconlechuga** [comment]
Easily reproducible by placing debug control and disassembly underneath. I swear this is a Qt bug not correctly executing restoreGeometry and restoreState on the docks.
