### ISSUE TITLE
TI-OS never idles to sleep

### ISSUE THREAD

**Issue by runer112** [CE-Programming/CEmu#195]
This may have been intended behavior, but it is undeniably an emulation inaccuracy. This should be controllable via an emulation setting.

**Comment by mateoconlechuga** [comment]
This is usb related... But any more than that is unknown :P

**Comment by mateoconlechuga** [comment]
This has been reopened because it is seen as lower priority to another bug

**Comment by adriweb** [comment]
Since this is USB, I'm moving it to its target

**Comment by mateoconlechuga** [comment]
I think this is actually fixed now? I've had multiple times where it apds on me.
