### ISSUE TITLE
LCD controller's (PL111's) LPP not handled properly

### ISSUE THREAD

**Issue by runer112** [CE-Programming/CEmu#196]
With "Emulate physical LCD SPI drawing" checked, lowering LPP (lines per panel) lowers both the number of rows and columns refreshed. It should only lower the number of rows refreshed.

**Comment by mateoconlechuga** [comment]
Simple test code to replicate:

```asm
	ld	hl,(mpLcdRange+4)
	push	hl
	res	0,h
	res	1,h
	ld	(mpLcdRange+4),hl
	ld	a,100-1
	ld	(mpLcdRange+4),a

	ld	hl,vram
	ld	de,vram+1
	ld	bc,320*240*2
	ld	(hl),100
	ldir

_:	call	_GetCSC
	or	a,a
	jr	z,-_

	pop	hl
	ld	(mpLcdRange+4),hl
	ret
```

**Comment by mateoconlechuga** [comment]
Here's the offending code: https://github.com/CE-Programming/CEmu/blob/master/core/lcd.c#L152-L167

**Comment by mateoconlechuga** [comment]
![image](https://user-images.githubusercontent.com/9890252/38463697-4f83ff4e-3ab5-11e8-8b86-845d43da85bc.png)

The above rectangle should stretch across the whole screen horizontally.

[test.8xp.zip](https://github.com/CE-Programming/CEmu/files/1887070/test.8xp.zip)

.
