### ISSUE TITLE
Reassess which columns should be sortable across all tables

### ISSUE THREAD

**Issue by runer112** [CE-Programming/CEmu#200]
In my assessment, it seems that every column that does not just display a button could provide some utility by being sortable.

On that topic: why are the buttons in tables if they're the same for every row? Should they just exist outside the table and act upon the highlighted row?

Also, why is there no third state of sorting when clicking on a column header to not sort? That seems like a pretty standard pattern.

**Comment by mateoconlechuga** [comment]
I don't think that it is really worth it to have sortable lists besides in the variable views, which is already supported... I'm going to close this unless someone *really* wants to sort debugging addresses and labels.

**Comment by mateoconlechuga** [comment]
Also highlighting lines and then selecting a button is how it used to be, and it really annoyed me that I would have to highlight a line, mouse up to a button and then select the next one and so on. The way it is now is much more efficient.
