### ISSUE TITLE
High DPI rendering issues on Windows

### ISSUE THREAD

**Issue by runer112** [CE-Programming/CEmu#201]
CEmu has some rendering issues at high DPI on Windows. Interestingly, the MSVC and MinGW Windows builds have entirely separate issues.

The MSVC Windows build has the issue that standard Windows UI elements don't match the DPI. Note the appearance of the checkmarks in the checkboxes, the arrows on the number box, and the radio buttons:

![cemu_msvc_high_dpi_issue](https://user-images.githubusercontent.com/6608979/36347353-5b7e82aa-1423-11e8-9db6-1a9ec94c83f5.png)

The MinGW Windows build has the issue that the printing on keys on the keypad does not display properly whatsoever, and the font used for the faceplate text doesn't look great either:

![cemu_mingw_high_dpi_issue](https://user-images.githubusercontent.com/6608979/36347359-7a8b13ac-1423-11e8-9f70-fee9d44e4be0.png)

**Comment by adriweb** [comment]
The MSVC situation might improve with #165, but that's just a guess. Someone would need to test and report back.
Also, see all the stuff in here http://doc.qt.io/qt-5/highdpi.html
And some things were already done in the pas, regarding this, see #90

**Comment by mateoconlechuga** [comment]
May be fixed, although needs some testing.

**Comment by mateoconlechuga** [comment]
Yeah we just need #165 to be implemented it seems. @alberthdev ?

**Comment by adriweb** [comment]
@runer112 care to try the latest Qt 5.10 MSVC builds? 
https://oss.jfrog.org/artifactory/oss-snapshot-local/org/github/alberthdev/cemu/git/201803/20180331/cemu-20180331_092311-git-afa21cc/ for instance

**Comment by mateoconlechuga** [comment]
@runer112 bump :)

**Comment by runer112** [comment]
The latest MSVC build now behaves like MinGW builds always have. Windows UI elements like checkboxes are rendered at high DPI, but the printing on the keypad is messed up.

**Comment by mateoconlechuga** [comment]
@runer112 How about this build: https://oss.jfrog.org/artifactory/oss-snapshot-local/org/github/alberthdev/cemu/git/201804/20180405/cemu-20180405_041515-git-9614bb7
