### ISSUE TITLE
High DPI icons

### ISSUE THREAD

**Issue by runer112** [CE-Programming/CEmu#202]
Using icons with higher resolution versions for high DPI environments would be nice. CEmu currently uses [famfamfam's "Silk"](http://www.famfamfam.com/lab/icons/silk/), a set of ~700 16x16 icons licensed under CC 2.5 with a credit clause. I discovered [FatCow's "Farm-Fresh Web Icons"](http://www.fatcow.com/free-icons), a set of ~3900 icons designed at both 16x16 and 32x32, licensed under CC 3.0 with a credit clause. Considering the large number of icons (so equivalent or better versions of all currently used icons probably exist) and the nearly identical licensing, it seems like it could be an easy drop-in, but with the addition of 32x32 versions of icons.

**Comment by adriweb** [comment]
Hmmm, nice.
![](https://i.imgur.com/ttb9Jd1.png)
