### ISSUE TITLE
Handling of console strings is real bad

### ISSUE THREAD

**Issue by mateoconlechuga** [CE-Programming/CEmu#204]
Yeah, some logs:

> 11:07 <•jacobly> I mean the "correct" way is to use a circular buffer
11:07 <•jacobly> and a semaphore
11:14 <•jacobly> all the updates coalesce until the gui can handle them
11:14 <•jacobly> the emu thread blocks only when the buffer is full
11:14 <•MateoC> Ah neat
11:15 <•jacobly> and until there are enough bytes available to add a string
11:15 <•MateoC> I just realized how it is currently done is horrid
11:17 <•jacobly> so append string to console looks like: lock strlen bytes, put chars at emu thread position, circularly, emit unique signal
11:18 <•MateoC> So um
11:19 <•jacobly> the slot looks like: read size - available chars at gui thread position, circularly, then release however many read

**Comment by mateoconlechuga** [comment]
Someone halp

**Comment by mateoconlechuga** [comment]
It seems fixed but idk :P

**Comment by mateoconlechuga** [comment]
Suggestions on the best way to fix this other than duplicating code?

**Comment by jacobly0** [comment]
My suggestion was arrays of length 2, using the type enum as an index.

**Comment by mateoconlechuga** [comment]
It just needs to block and flush now when the types change. I'm not sure how that could be done; potentially consoleWriteSemaphore[prev].acquire(available); but where?

**Comment by mateoconlechuga** [comment]
I broke everything :(

**Comment by adriweb** [comment]
"everything" might be an exaggeration, as only types aren't working for me (on macOS anyway) :)

**Comment by mateoconlechuga** [comment]
dbg_sprintf(dbgout, "THIS SHOULD TOTALLY I THINK\n");
    dbg_sprintf(*dbgerr, "THIS SHOULD TOTALLY I THINK\n");
    dbg_sprintf(*dbgerr, "THIS SHOULD TOTALLY I THINK\n");
    dbg_sprintf(*dbgerr, "THIS SHOULD TOTALLY I THINK\n");
    dbg_sprintf(dbgout, "THIS SHOULD TOTALLY I THINK\n");
    dbg_sprintf(dbgout, "THIS SHOULD TOTALLY I THINK\n");
    dbg_sprintf(dbgout, "THIS SHOULD TOTALLY I THINK\n");
    dbg_sprintf(*dbgerr, "THIS SHOULD TOTALLY I THINK\n");
    dbg_sprintf(dbgout, "THIS SHOULD TOTALLY I THINK\n");
    dbg_sprintf(dbgout, "THIS SHOULD TOTALLY I THINK\n");
    dbg_sprintf(dbgout, "THIS SHOULD TOTALLY I THINK\n");
    dbg_sprintf(*dbgerr, "THIS SHOULD TOTALLY I THINK\n");

Prints:

![image](https://user-images.githubusercontent.com/9890252/37238638-9b6bfd54-23df-11e8-97d8-2688982ab51c.png)
