### ISSUE TITLE
Not able to find where to have a calculator only layout like shown on the main page 

### ISSUE THREAD

**Issue by Ocraftyone** [CE-Programming/CEmu#205]

**Comment by adriweb** [comment]
Basically:
1. layout the keypad beneath the screen
2. in the menus, uncheck all the docks/panes except Keypad
3. disable UI edit mode

**Comment by Ocraftyone** [comment]
It still doesn't look as polished and rounded as the picture does. 
![image](https://user-images.githubusercontent.com/24759591/36392254-5dfcc568-1578-11e8-9c6f-92dc599f6466.png)

**Comment by mateoconlechuga** [comment]
You simply don't have a big enough screen.

**Comment by adriweb** [comment]
Well, resize your window to make the sizes match :)
(if you can, indeed)

You can also choose to uncheck the "skin" toggle around the screen, and/or choose a different scale for the LCD.

There's nothing more to it I'm afraid, so I'll close this issue.

**Comment by Ocraftyone** [comment]
Thanks the scale fixed it. Didn't realize that that was there

**Comment by mateoconlechuga** [comment]
Just a quick comment that it is annoying the scale only does increments of 25. This should be fixed in the next release.
