### ISSUE TITLE
Automatically use Portable Configuration if the standard path is non-writable

### ISSUE THREAD

**Issue by adriweb** [CE-Programming/CEmu#208]
In case of missing permissions to write in the standard settings path, automatically turn on the "portable configuration" setting, and display an info popup about that.
A simple silent permissions check should be performed first (instead of erroring when it tries to write things) to determine if this has to be done.

**Comment by mateoconlechuga** [comment]
Um no? The issue is that CEmu attempts to write to the system app data location, not the user one :P
