### ISSUE TITLE
Emulation speed and FPS updates in status bar

### ISSUE THREAD

**Issue by Stephan-P** [CE-Programming/CEmu#214]
What happens?
-------------
In the status bar of the CEmu window, the emulation speed and FPS indicators are updated at rapid speed, flickering and changing position

What were you expecting to happen?
----------------------------------
1. Update the emulation speed and FPS at a lower rate, making it easier to watch for the human eye
2. Use a fixed width for the Emulation speed percentage in order to prevent the FPS indication shifting left and right. Or even better, give the FPS indicator its own position in the status bar, independant from the preceeding emulation speed.

What are the steps to reproduce this issue?
-------------------------------------------
1. Setup CEmu in calculator mode (LCD + keypad)
2. Run the calculator emulation
3. Watch the status bar go wild

Any logs, error output, screenshot, etc?
----------------------------------------
![snipaste_2018-02-22_08-21-54](https://user-images.githubusercontent.com/10008599/36525272-839319ac-17a9-11e8-8b6b-f9b3e2fc0278.png)

Any other comments?
-------------------
I am SO pleased with CEmu as a TI SmartView alternative.

What versions of software are you using?
----------------------------------------
**Operating System:** Windows 10 64bit Home Edition with latest updates
**CEmu version (and git SHA):** 1.0

**Comment by mateoconlechuga** [comment]
Added the fix to this annoyance along with a spin button to toggle the refresh rate. Currently will update every 1 second by default. Also moved the FPS display to the bottom right as well. Unfortunately the development MSVC builds are not updated (you can always get a mingw one), but this should be fixed in the near future. Thanks for the request! :)
