### ISSUE TITLE
Title of floating window reflects last panel docked to it

### ISSUE THREAD

**Issue by runer112** [CE-Programming/CEmu#216]
The title of a floating window reflects the last panel docked to that window. It should instead reflect the active panel docked to that window.

Encountered on the MSVC Windows build, commit fbc4125.

**Comment by mateoconlechuga** [comment]
Cannot reproduce. Keep in mind MSVC is horribly outdated.

**Comment by runer112** [comment]
Yup, I was using a week-old build and this appears fixed in the latest MinGW build.
