### ISSUE TITLE
Go to register

### ISSUE THREAD

**Issue by runer112** [CE-Programming/CEmu#217]
In the disassembly and memory viewer panels, it would be useful to be able to go to the address stored in a register. I'd suggest this be implemented by simply matching register names entered in the Goto dialog.

**Comment by mateoconlechuga** [comment]
You already can; either by ctrl+click on a register text to goto in the disassembly, ctrl+shift+click to goto in the memory view, and clicking of the green register text to goto in the memory view.

**Comment by runer112** [comment]
Those shortcuts are nice to know about, but those aren't sufficient when using added memory view panels, and definitely not when using multiple.
