### ISSUE TITLE
Stack view skips first entry

### ISSUE THREAD

**Issue by runer112** [CE-Programming/CEmu#225]
Culprit: https://github.com/CE-Programming/CEmu/blob/442151337248661ef3f3fc164b1d2e1f03d92805/gui/qt/debugger.cpp#L1917-L1923

The stack address should be incremented after displaying each entry, not before. This change should also be applied to the non-adl case in this function, and to both cases in `drawNextStackLine`. For bonus points, unify the main logic duplicated across all four of these blocks into one function.

**Comment by mateoconlechuga** [comment]
Fixed with cc74173
