### ISSUE TITLE
Disassembler rewrite

### ISSUE THREAD

**Issue by mateoconlechuga** [CE-Programming/CEmu#226]
The disassembler is bad and slow. Ideas on how to make it better? :)

**Comment by runer112** [comment]
What about it is bad and slow?

**Comment by mateoconlechuga** [comment]
I'd just like to make it in C and put it in the core so it could be used by other things as needed.

**Comment by debrouxl** [comment]
Maybe C++ with a C API, to maximize interoperability while making development easier by leveraging some C++ / STL facilities internally ?

**Comment by mateoconlechuga** [comment]
C with callbacks as necessary :)

**Comment by mateoconlechuga** [comment]
Looks pretty much done thanks to jacobly :)
