### ISSUE TITLE
Build for iOS platform

### ISSUE THREAD

**Issue by artemnovichkov** [CE-Programming/CEmu#227]
Can I run any ROMs with Calc-only layout on iOS?

**Comment by adriweb** [comment]
Nope, sorry, not made for this purpose, and it wouldn't even look good (if it worked at all on a mobile device).
Also the calc-only layout is just a selection of docks/tabs that are hidden, and drag'n'droped to make it look like a calc ; it's particlarly useful for good-looking pictures of a CE running games or whatnot, when developers want to show off their projects.

However, you should absolute tell TI about your (and probably other people's) interest about a phone CE emulator app, it may change their minds about not having one...
Here's their email: ti-cares@ti.com

**Comment by mateoconlechuga** [comment]
Texas Instruments has informed us they don't want support of any mobile platforms and to focus primarily on developmental features. However, we cannot stop and external forks of this project.

**Comment by adriweb** [comment]
(BTW this was mentioned here with a bit more info: https://github.com/CE-Programming/CEmu/issues/86#issuecomment-250947346 ; an iPad version (or basically a tablet with a big enough screen, like a small laptop) would probably work much better than a mobile one, even though this is still something that has been done here. Once again, it'd be nice to have TI agree that mobiles apps would be a good idea...)
