### ISSUE TITLE
To get back the barre menu

### ISSUE THREAD

**Issue by juanito30** [CE-Programming/CEmu#228]
It's not a big deal, but i try to hide the barre menu. It worked. But after, i did not find a way to get back this barre menu.
May be someone knows how to.
Thanks

**Comment by adriweb** [comment]
You can right-click on the screen, and a context menu will show up where you'll be able to find an option to toggle the menu bar back on.

**Comment by hykilpikonna** [comment]
![image](https://user-images.githubusercontent.com/22280294/54713116-3d3fad80-4b24-11e9-87ff-afa737816df5.png)

I accidentally hide the menu too, didn't find any way to get it back...

**Comment by adriweb** [comment]
Same comment as before, it still works the same:

You can right-click on the screen, and a context menu will show up where you'll be able to find an option to toggle the menu bar back on.

**Comment by hykilpikonna** [comment]
Ohhhh you mean the actual calculator screen...
I thought you mean the screen as the computer monitor screen so like anywhere on this window...
Anyways...
Thanks!
