### ISSUE TITLE
"Step over" sometimes continues instead

### ISSUE THREAD

**Issue by elfprince13** [CE-Programming/CEmu#23]
In at least 3 separate instances, I attempted to step over a `jr nc,someaddress` and instead found that the debugger had instead continued.

**Comment by MateoConLechuga** [comment]
Use step rather than step over for jumps and things. It's not done yet

**Comment by Runer112** [comment]
That fix will still not correctly handle `djnz` or `ret`.

Also, while I realize it's good to just get a pretty close implementation for now, I wouldn't feel comfortable putting the step over issue to rest until it gets a proper redoing, involving checking the stack pointer and such.

**Comment by MateoConLechuga** [comment]
Fixed with 3610b35
