### ISSUE TITLE
Feature request: Key press history Dock

### ISSUE THREAD

**Issue by Stephan-P** [CE-Programming/CEmu#230]
(Thanks for reporting an issue! Please make sure to fill out the blanks below.)

Feature request: Key press history Dock
---------------------------------------------
**Operating System:** Windows 10 
**CEmu version:** 1.0
**Describe your issue:**  
My use of CEmu is educational, that is in the class room. 
As such my dock settings are minimal; screen + keypad.
I would like to ask for one extra dock to become available: History of key presses.
This would be very helpfull with class instructions.
Possibly (hopefully) it's a minor thing to establish.

(I find CEmu a much faster and much more convenient TI-84 emulator than TI's own SmartView. I for once have not yet discovered the smart bit in it.)

**Comment by adriweb** [comment]
This is already available in CEmu, even though it wasn't really designed for educational use :)
You can find it in the menus: File > Show Key History.

**Comment by Stephan-P** [comment]
Merci bien, Adrien
