### ISSUE TITLE
Syntax highlight in the TI-Basic viewer

### ISSUE THREAD

**Issue by adriweb** [CE-Programming/CEmu#231]
Basically just do like for the Lua editor: https://github.com/CE-Programming/CEmu/commit/ed97832c38ff97333c638f7af4623c4cd89059a3#diff-1ab30fd710566ccc19a3fd2a811c2057

**Comment by mateoconlechuga** [comment]
Can we make it an editor too

**Comment by adriweb** [comment]
Yes that's #116 which is however a bit more complex but definitely on my todo list :P

**Comment by adriweb** [comment]
Available in the `feature/basic-highlight` branch.

Plz test and feedback :)

![Screenshot](https://i.imgur.com/h4gKko1.png)

**Comment by adriweb** [comment]
Added some more colors for labels/gotos and prgm*.
Also all lists are blue now.

![screenshot](https://i.imgur.com/uZnWGNL.png)

Looks like it's good enough for master, since @mateoconlechuga keeps pushing for a merge :P

Maybe later we can add some color customization per syntax type...
