### ISSUE TITLE
Qt Error Encountered While Starting CEmu

### ISSUE THREAD

**Issue by LenticularAurora** [CE-Programming/CEmu#234]
Operating System: Windows 10 Pro 64-bit
CEmu Version: 1.0
---------------------------------------

```
qt.network.ssl: QSslSocket: cannot call unresolved function SSLv23_client_method
qt.network.ssl: QSslSocket: cannot call unresolved function SSL_CTX_new
qt.network.ssl: QSslSocket: cannot call unresolved function SSL_library_init
qt.network.ssl: QSslSocket: cannot call unresolved function ERR_get_error
qt.network.ssl: QSslSocket: cannot call unresolved function ERR_get_error
```

- I keep getting the following error whenever I start the application.
- Another issue that I experience is that the keypad and the console are separated and cannot connect as in the image provided in the GitHub info page.

**Comment by mateoconlechuga** [comment]
@alberthdev We need to make sure we are adding the static versions of libeay32.lib and libssl32.lib please.

Anyway, this should hopefully be fixed in the next release (soon). Thanks for the report!

**Comment by LenticularAurora** [comment]
Sorry, forgot to write that the Windows 10 version was a 64-bit version.

**Comment by mateoconlechuga** [comment]
As for dropping the docks around, the easiest method is to close all the docks, maximize the window, and then order the docks around from the menu. Hope this helps!

**Comment by LenticularAurora** [comment]
Couldn't rearrange them to look like a real calculator and ended up with this instead:
https://i.imgur.com/wmidiDF.png

**Comment by mateoconlechuga** [comment]
You simply don't have a high enough resolution display. You can solve this by changing the screen scale and/or skin display modes in the settings menu.

**Comment by LenticularAurora** [comment]
Ok, now the the scale is at 75% and it's working but the sizes are off.
<img src="https://i.imgur.com/hVspAMy.png">
Recommendation, make the program responsive to fix this problem and I will report back if I encounter another problem such as this one.

**Comment by mateoconlechuga** [comment]
I personally hardly ever use the keypad; all of the keys have corresponding keybindings on the keyboard. Anyway the next release will have a lot of fixes as well, thanks again!

**Comment by runer112** [comment]
The UI has had a lot of work put into it recently to make it quite responsive. However, this is designed to be a computer application and use at low resolutions hasn't been a big consideration.

Also, I'd recommend turning off the skin instead of reducing the scale to 75%. The screen contents look much nicer at multiples of 100%.

**Comment by LenticularAurora** [comment]
No problem and one other thing is that when you disable all the docks while leaving the keypad enabled you will notice that the keypad will align to the center while the LCD screen remains aligned to the left and that you have to resize them for them to fit together although the size difference between the keypad and the LCD is still there. And I get the following error code in the command prompt that is still running in the background while the application is working:

`QWindowsWindow::setGeometry: Unable to set geometry 1366x740+0+23 on QWidgetWindow/'MainWindowWindow'. Resulting geometry:  1366x705+0+23 (frame: 8, 31, 8, 8, custom margin: 0, 0, 0, 0, minimum size: 937x740, maximum size: 16777215x16777215).`

I would've contributed to your work but I do not have the right set of tools at the moment 😢

**Comment by alberthdev** [comment]
@LenticularAurora Could you try the dev builds located [here](https://ce-programming.github.io/CEmu/download)? (Make sure to click on the Development tab.)

If this issue still occurs on the development build, please provide a screenshot of the error and the version of the build you are using. Thanks!

**Comment by LenticularAurora** [comment]
@alberthdev Just tried out the dev build and it seems that at 70% everything is in sync but the problem is that with the increase of size there seem to be a bug preventing both the keypad and the screen to increase size without being out of sync. 

Well done and thank you for fixing the calculator!

**Comment by mateoconlechuga** [comment]
What exactly do you mean by out of sync?

**Comment by alberthdev** [comment]
Just to make sure things actually, actually work, please try this build as well:

[CEmu_v1.1fake.zip](https://github.com/CE-Programming/CEmu/files/1886049/CEmu_v1.1fake.zip)

Note that since this has a differently tagged (invalid) version, you may get a prompt to update. Ignore, and then ensure that no settings are erased. This should be fine for this version, since it is built off of the development tree. (Don't do this for any other version, though!)

**Comment by LenticularAurora** [comment]
@mateoconlechuga This is what I mean (these task were performed with settings set to 70% scale):
>! <img scr="https://i.imgur.com/lWTbLta.png">

And this is what happens if the main window is not minimised to the size of the calculator:
<img src="https://i.imgur.com/W7lFfHS.png">
Just noticed that when I tried to minimise the size of the calculator after making it bigger this happened:
<img scr="https://i.imgur.com/g7pv6QP.png">

Another thing you should know is that increasing the size of the calculator does not increase the size of both the keypad and the screen but does increase the size of the screen only! (I know it says display, but to make the calculator bigger so that the user can see better there ought to be a way to make sure that both the keypad and the screen increase in size and does not do so unless they are increasing in such way to make it look like the calculator is zooming in and not one part increasing while the other remains the same).
<img src="https://i.imgur.com/lp95a70.png">

And to get the calculator to look like it's a real calculator we need to separate the UI from the main window, like this (this leaves the main window empty thus having us open 2 tabs without being able to minimise one of those tabs):
<img src="https://i.imgur.com/ilm6zcC.png">

(And FYI, whenever I start the latest version of the development build the title bar is hidden and to show it again I have to increase the size of the window using the bottom right corner to do so.)

**Comment by LenticularAurora** [comment]
@alberthdev Apparently that version didn't let me chose the rom I wanted and therefore the keypad did not work.

**Comment by mateoconlechuga** [comment]
There is no bug. You can disable the menu bar and the status bar from the `Extras` menubar option to get more space. The screen was never meant to be locked to the keypad.

Either set it to a lower scale, or disable the skin. Honestly for developers we do not care if it looks like a "real calculator"
