### ISSUE TITLE
Resizing initial CEmu window makes it to disappear

### ISSUE THREAD

**Issue by Stephan-P** [CE-Programming/CEmu#237]
What's wrong, and with what software version?
---------------------------------------------
**Operating System:** Windows 10
**CEmu version:** 1.1 beta (executable date:  march 17)
**Describe your issue:**  
Upon first start, CEmu fills the full height of the screen.
Part of the CEmu window is beneath the windows taskbar and cannot be viewed or reached.
In trying to resize the CEmu window (by dragging its top right corner) the window completely disappears to a location off screen and nothing can be done anymore.

In my opinion there are two issueas at hand
-------------------------------------------
1. At initial start CEmu sizes its window to full screen height. Please subtract taskbar height from full screen height to calculate window height.
2. Resizing the window makes it disappear to an off screen location

**Comment by adriweb** [comment]
This is a mix of what's explained here: https://github.com/CE-Programming/CEmu/issues/234#issuecomment-377589594 and a Qt/Windows issue, I guess.

BTW, there are more recent builds - choose the "Development" tab here: https://ce-programming.github.io/CEmu/download#modal-wizard-64-bit-release-static 
Try resetting all your settings (the menu item "Reset CEmu") and launch it again, just in case

**Comment by Stephan-P** [comment]
I did click the development tab and took the 64-bit Windows version from there.
Now I've entered into the dungeons of "Advanced Download options" - "Browse MSCV builds" - further down into the latest date folder. Quite a trip...

**Comment by adriweb** [comment]
"subtract taskbar height" is quite windows-specific (and even then, some people don't have it at the bottom, for instance), so we'd have to find a generic solution to this.

That said, it may just be linked to https://github.com/CE-Programming/CEmu/issues/238#issuecomment-377697162 
So, I'm closing this one as we'll solve that other one. Once that's done, feel free to re-open this one if need be.
