### ISSUE TITLE
[v1.1] Window state doesn't restore correctly in portable mode, all panes are shown and stacked

### ISSUE THREAD

**Issue by Stephan-P** [CE-Programming/CEmu#238]
What's wrong, and with what software version?
---------------------------------------------
**Operating System:** Windows 10
**CEmu version:** 1.1beta (build date 17/3)
**Describe your issue:**  
I get the impression that CEmu does not save or restore its saved state.
If I manage to setup CEmu the way I want it (and frantically trying to avoid its disappearance act), upon the next start it comes back with its initial window settings.
BTW, where would it save its settings, because I've got CEmu v1.0 installed, plus CEmu v1.1beta in a folder on the desktop. It looks like my experiments with v1.1beta do not harm the settings of v1.0.

**Comment by adriweb** [comment]
Check if you have "Portable mode" enabled. Considering you've had to play with those, you're probably in a weird state of things with multiple CEmus...

Settings saving/restoring work fine on my own here, mac/linux/windows.

**Comment by Stephan-P** [comment]
I downloaded 1.1dev (6f825f0) and placed this into a desktop folder named CEmu-test.
I started it and immediately put it into portable mode. A file cemu_config.ini appeared.
I wrestled to get all the docks out of the way, leaving me just the LCD and Keypad.
Please note that a LOT of debugging docks are not listed in the Docks menu, making it hard to disable them when they're positioned somewhere down the taskbar.
Once I got everything in place, I reset the calculator to see it running properly.
After closing CEmu and restarting it again, I get the same initial window config the program starts with at its initial run.

**Comment by Stephan-P** [comment]
When I import the saved window configuration (*.ini) file CEmu crashes without issue

**Comment by Stephan-P** [comment]
My regular CEmu v.1.0 still functions normally, so no settings have been mixed somewhere.

**Comment by adriweb** [comment]
So, you're saying the issue is saving/restoring in portable mode. This could be looked into further.

**Comment by Stephan-P** [comment]
I found the folder C:\Users\username\AppData\Local\cemu-dev\CEmu 
This explains why both versions can live alongside eachother.

**Comment by adriweb** [comment]
Correct, settings have been moved here in v1.1.

**Comment by adriweb** [comment]
I guess I am able reproduce the issue in portable mode, but for me in non-portable/normal, saving and loading of settings works fine.

**Comment by adriweb** [comment]
Investigation so far... :

`m_pathRom` (at least) doesn't get set when CEmu launches in portable mode, which makes the setup wizard run again.
The value is however correct in the .ini file (although it's a relative path)

**Comment by adriweb** [comment]
So, it turns out there were path issues in portable mode, on macOS, due to where the actual binary is located (.app bundle etc.).
I've fixed that now, and I believe I am now able to face the same situation as on Windows: stuff loads, but the UI configuration doesn't (or at least, it gets messed up).

**Comment by adriweb** [comment]
I'm out of ideas. Everything settings-wise is OK (loaded correctly) and restoreState in setup() returns true, so apparently it didn't fail.
Yet the docks/panes aren't correctly positioned, and I don't know why. Something in updateDocks() ?

FWIW, it actually looks like this:
![](https://i.imgur.com/QV5OOLr.png)

@mateoconlechuga halp ?

**Comment by mateoconlechuga** [comment]
Closed with c576812

**Comment by Stephan-P** [comment]
I've downloaded the latest cemu-20180405_124103-git-7e52797-win64-release-static and tried it.
At first run the window is a complete mess with all sorts of docks displayed across eachother.
Uing the option Restore GUI Docks, the mess is gone, the docks are displayed and all debugger windows are invisible.

Still one thing is not working right.
Situation:
directory contains cemu.exe, cemu_config.ini and cemu_image.ce
Portable mode is OFF
With each restart cemu is starting like fresh new.
When these two files are removed from the directory, cemu starts as configured

**Comment by adriweb** [comment]
I'd suggest deleting all settings, local and shared, and trying again from scratch :)

**Comment by Stephan-P** [comment]
Good suggestion. This makes a difference.
- I deleted cemu_config.ini and cemu_image.ce from cemu-test dir and appdata dir
- Upon start cemu.exe asks for ROM etc. I arrange docks in NON-portable mode and save State.
- Upon next start CEmu starts as configured (:-)
- I change the mode to portable and cemu_config.ini and cemu_image.ce appear in installation dir.
- Upon next start CEmu starts as configured
- I change the mode tot NON-portable again. both files remain in the install dir.
- I make sure to disable GUI Edit mode, size the window appropriately, and save status
- Upon next start CEmu starts almost as configured, but GUI Edit mode is ON (with window top bars)
- I try several times and notice it is not consistent; sometimes the restart is fine, sometimes GUI Edit mode is switched on (odd)
- Now for several trials, cemu restarts as desired (without GUI mode on)

Either way, switching GUI Edit mode on/off causes the width of the CEmu window to change 1 or 2 pixels. Rounding issue?

**Comment by mateoconlechuga** [comment]
Try downloading the latest development release. It should be fixed now.

> switching GUI Edit mode on/off causes the width of the CEmu window to change 1 or 2 pixels. Rounding issue?

No, this is related to the spacer that you can move to arrange the docks with more precision. It is disabled in non-edit mode, so that way you don't have the extra space on the side of the calculator screen, or the old issue you had where the keypad and lcd weren't aligned.
