### ISSUE TITLE
Laying out windows is freaking annoying

### ISSUE THREAD

**Issue by mateoconlechuga** [CE-Programming/CEmu#239]
I set something up, open a new dock, and everything is destroyed. Or I switch UI edit mode, and then everything expands and looks awful.

**Comment by Stephan-P** [comment]
Once setup (calculator only), upon next start CEmu adds extra width and height to its window size
![snipaste_2018-04-01_11-35-13](https://user-images.githubusercontent.com/10008599/38171819-11ce2512-35a1-11e8-82e9-d624421dcce3.png)

**Comment by mateoconlechuga** [comment]
I'm well aware but thanks :)
