### ISSUE TITLE
Minor GUI suggestions

### ISSUE THREAD

**Issue by Stephan-P** [CE-Programming/CEmu#242]
Console window size + About CEmu dialogue
---------------------------------------------
**Operating System:** W10 Home
**CEmu version:** 1.1dev
**Describe your issue:**  
Upon start CEmu throws up a rather large Console window. Annoyance.
Suggestion 1. The Console window is user sizable. If you store Console window size in the Calculator State and use these values upon start, then the user can create his own less annoying Console window.
Suggestion 2. Otherwise reduce/minimize the console window at startup
Suggestion 3. Open Console window at a later stage and only if enabled

The About CEmu dialogue shows us detailed information of CEmu
Suggestion: Make the text selectable so that we can easily copy the version number and build number for reports like this.

**Comment by adriweb** [comment]
Hmm well the default UI is meant to be customized anyway, and on macOS the about dialog text is already selectable... ¯\_(ツ)_/¯

**Comment by adriweb** [comment]
I enabled something that probably makes text selection possible if it wasn't already possible, in the about window.
You should be able to try soon, when the build is done.

**Comment by mateoconlechuga** [comment]
The console window will be disabled on release builds.

**Comment by Stephan-P** [comment]
Adrien, cemu-20180408_091034-git-a4fa561-win64-release-static does not (yet) have selectable text in the About dialogue. The links work, but otherwise nothing can be selected for Ctrl-C copy actions.

PS. Don't let this minor thing stop you from releasing v1.1. ;-)

**Comment by adriweb** [comment]
Sadly this seems to be windows-only... I'll reopen but to be fixed later on

**Comment by alberthdev** [comment]
@Stephan-P Try this build out - in the About dialog there is a new button that allows you to easily copy the CEmu version and build commit hash.

[CEmu_v1.1fake_withvercopy.zip](https://github.com/CE-Programming/CEmu/files/1887773/CEmu_v1.1fake_withvercopy.zip)

Screenshots:
![image](https://user-images.githubusercontent.com/1274384/38471009-38b85ccc-3b39-11e8-9258-1934a140a481.png)
![image](https://user-images.githubusercontent.com/1274384/38471020-5286448e-3b39-11e8-9999-0098677f3a40.png)
Paste it in anywhere:
![image](https://user-images.githubusercontent.com/1274384/38471027-7b47cef6-3b39-11e8-9af0-62bd1f0efea6.png)

If this works for you we'll go ahead and make this the de-facto way for copying and pasting version and build commit hash.

**Comment by Stephan-P** [comment]
Loverly! Tested and verified. 
I take it this'll call for two more strings to be translated. I'll keep a lookout.
Note that the buttons are shifting because the second string is longer.
Depending the language this effect can be worse: Versie kopiëren - Versie gekopieerd!
Suggestion: keep just one button that is greyed out after the copy has been made.

**Comment by alberthdev** [comment]
Buttons shifting is probably not that big of an issue, given that there's some sort of visual feedback given to indicate that the version is copied. That said... let's see what it looks like and if it's really an issue we can take a look at it!
