### ISSUE TITLE
Runs a little slow

### ISSUE THREAD

**Issue by Smiggle** [CE-Programming/CEmu#245]
My program seems to run at normal speed if you up the speed to 120%

**Comment by mateoconlechuga** [comment]
Please do not post roms here! Thanks.

Anyway; it's probably just you think it is running slow. You can check the actual emulation speed on the lower left status bar in the program. If it does seem a little slow, then decheck `Emulate physical LCD SPI drawing` in the settings.

**Comment by adriweb** [comment]
Don’t post such links.
Regarding the slowness, it’s probably your computer. That said, there are things you can try even: adjusting the speed slider, and disabling SPI emulation.
