### ISSUE TITLE
Is it possible to turn the TI-84+ CE .8eu OS file from education.ti.com into a ROM?

### ISSUE THREAD

**Issue by i336** [CE-Programming/CEmu#247]
I don't have a TI-84+ CE, and would like to see what one is like to work with. I want to randomly poke at/play with CEmu in TI-84+CE mode for 10 minutes :)

Well. Either my Google-fu is really bad today, or the, uh, *droids* I'm looking for <sup>\**AHEM*\*</sup> don't surface easily. That doesn't surprise me that much, really; 2015 was only 3 years ago after all.

However, in the process of poking around, what I *did* find was [this no-fuss OS download from TI](https://education.ti.com/en/software/details/en/158B7669E4C0493A84D33D9A22FDBD3C/ti-84plusceoperatingsystem). I had no problems accepting the attached EULA, and now I have an `.8eu` file.

While searching I also stumbled on [this small guide showing how to JPEGify a calculator ROM <sup>awesome.</sup> to load it into jsTIfied](https://www.reddit.com/r/jailbreak/comments/5yvrg4/tutorial_how_to_get_a_fully_functional_texas/), where I learned Wabbitemu could convert downloaded OS files into a ROMs.

Except, of course, Wabbitemu doesn't support the TI-84+ CE. Understandable.

(Must-mention sidenote: I initially tried https://github.com/alberthdev/wxwabbitemu, which compiled and worked perfectly(!), minus not supporting the TI-84+ CE - and then Wabbitemu via WINE.)

So, I'm curious - have I not searched deeply enough, or is this currently not possible? Is the reason it's not possible because this OS download is missing necessary info baked into actual ROMs, perhaps?

**Comment by LAX18** [comment]
Would it be wrong to lend i336 my TI84+CE rom? Just so he can try it out?
