### ISSUE TITLE
Memory View mirrors

### ISSUE THREAD

**Issue by PeterTillema** [CE-Programming/CEmu#248]
What's wrong, and with what software version?
---------------------------------------------
**Operating System:** 
Windows 10
**CEmu version:**
CEmu 1.1dev (git: 75230c6)
**Describe your issue:**  
When I go to mirrored RAM (i.e. `$D81234`), nothing happens, and it would be nice if CEmu then just shows the 'unmirrored' side, i.e. `$D01234`.

EDIT: this only happens in the Memory tab, not the Memory View tab.

**Comment by mateoconlechuga** [comment]
The memory tab is for displaying just the ram block, not mirrored hardware. The memory view was intended to be more versatile for just this case.
