### ISSUE TITLE
Writing 0 to $D0258C freezes CEmu

### ISSUE THREAD

**Issue by PeterTillema** [CE-Programming/CEmu#251]
(Thanks for reporting an issue! Please make sure to fill out the blanks below.)

What's wrong, and with what software version?
---------------------------------------------
**Operating System:**
Windows 10
**CEmu version:**
CEmu 1.1dev git 75230c6
**Describe your issue:**  
When I write the byte 0 to `$D0258C` (FPSBase + 2 or FPS - 1), CEmu slows down a lot or freezes/crashes at all. 

What are the steps to reproduce this issue?
-------------------------------------------
1. Write byte 0 to `$D0258C`

Any logs, error output, screenshot, other comments...?
-----------------------------------------------------
<img src="https://i.imgur.com/f1U39jR.gif">

**Comment by mateoconlechuga** [comment]
Needs more sanity checks on dock stack interfaces.

**Comment by runer112** [comment]
Recommended minimum sanity checks for both FP and OP stacks: base >= end, and both base and end in "normal" RAM (D00000-D40000).
