### ISSUE TITLE
Timers are broken

### ISSUE THREAD

**Issue by PeterTillema** [CE-Programming/CEmu#254]
(Thanks for reporting an issue! Please make sure to fill out the blanks below.)

What's wrong, and with what software version?
---------------------------------------------
**Operating System:**
Windows 10
**CEmu version:**
CEmu 1.1dev git: 5145eb7
**Describe your issue:**  
Whenever I set timer 1 to count down, it counts down with a standard step size, no matter what the opcode is (if I use the CPU timer).

What are the steps to reproduce this issue?
-------------------------------------------
1. Run this code: https://pastebin.com/YGbWH4z4
2. Look at `$F20000` and see it count down.

Any logs, error output, screenshot, other comments...?
<img src="https://i.imgur.com/uRUoM9y.gif" />

**Comment by adriweb** [comment]
I guess this is related to timer issues detailed in https://github.com/CE-Programming/CEmu/issues/212
Also, see fb1df718bdc1d469941fc1e0cb96de117fd5318c I'm not sure if it's related.
