### ISSUE TITLE
Timers are off

### ISSUE THREAD

**Issue by jacobly0** [CE-Programming/CEmu#256]
I think cpu_restore_next can't be called inside port.c -> sched_process_pending_events.  Should I move it out or conditionalize it.

**Comment by jacobly0** [comment]
[Here](https://github.com/CE-Programming/CEmu/files/2038911/timersha.zip)'s the latest timer testing program.

**Comment by adriweb** [comment]
> [Here](https://github.com/CE-Programming/CEmu/files/2038911/timersha.zip)'s the latest timer testing program.

This manages to crash CEmu, actually :P
`Assertion failed: (0 <= delay && delay <= 2), function gpt_next_event, file ../../core/timers.c, line 64.`

**Comment by mateoconlechuga** [comment]
Move it out :)

**Comment by jacobly0** [comment]
Fixed the `cpu_restore_next` issue in 9133e0c4c3176cf56dff26db1ef267e93269a255, but now graphing triggers the assert reproducibly.

**Comment by jacobly0** [comment]
Fixed the graphing assert in 376ed58b272342ea4804bc7c9ef7350d83bef8e2, now back to the original issue.

**Comment by jacobly0** [comment]
Now enabling a 32K asserts...

**Comment by mateoconlechuga** [comment]
branch before it's too late ;)

**Comment by jacobly0** [comment]
Fixed this assert with cd7afbd0b85c4be5a7a35cb6009cbc13deb198c8 and fixed all but one case of the offset timers with 93c4cff8f149400f16e7c3719881f3edfe292cc1, now to just fix that.

**Comment by jacobly0** [comment]
Fixed a bunch of obscure offset issues in 296fb15e18d3c92718a7aa8f534be945b61d3134, so now I think everything works except lines 0-4.

**Comment by adriweb** [comment]
Nice job!

I've moved to 1.x the two other remaining issues that we originally planned to fix for 1.1, but clearly they'll take some more time to (re)dive into, analyze, and fix.
So I guess when this one is closed (or if you think it's good enough as it is now?), it should be good to release v1.1 :)

**Comment by mateoconlechuga** [comment]
Good enough for me :) Let's do a release! :D

**Comment by adriweb** [comment]
> Good enough for me :) Let's do a release! :D

I'm just waiting for @jacobly0 to give his green light :P The lang stuff got updated in the meantime.

**Comment by adriweb** [comment]
> Fixed the graphing assert in 376ed58, now back to the original issue.

Just had a freeze when trying to graph something, so it looks like a release will have to wait (assuming it's directly related) for this to be fixed at least :(
Repro equation in Y1: `fnInt(X,X,0,X)`

**Comment by jacobly0** [comment]
Fixed graphing freeze with f3c109c07685da6f4e85733994f8a8de450134f0.

**Comment by adriweb** [comment]
Yep, can confirm :)

**Comment by mateoconlechuga** [comment]
CLOSE IT :D

**Comment by jacobly0** [comment]
#254 was closed a while ago, but this issue is for the few subtle remaining issues, and so won't be closed for some time, and therefore, should not be considered a blocker.
