### ISSUE TITLE
Failed to build : qmake does not find zdis-related files

### ISSUE THREAD

**Issue by josephscade** [CE-Programming/CEmu#257]
I am currently unable to compile CEmu on my computer using a Linux OS.
---------------------------------------------
**Operating System:** Solus OS Budgie
**CEmu version:** git version, commit [420ad60](https://github.com/CE-Programming/CEmu/commit/420ad6008af3ce90597f2b831813c83d90df56a1)
**Issue:**  the command `qmake -r CEMU.pro` reports errors related to `zdis` files:

What are the steps to reproduce this issue?
-------------------------------------------
1. Download the git version using `git clone https://github.com/CE-Programming/CEmu.git`
2. `cd` to `CEmu/gui/qt`
3. Run `qmake -r CEmu.pro`
4. See the following errors:
```
Project MESSAGE: Warning: unless your system libpng has APNG support, you will not be able to record screen captures!
WARNING: Failure to find: ../../core/debug/zdis/zdis.c
WARNING: Failure to find: ../../core/debug/zdis/zdis.h
```

If you want me to provide additional information, do not hesitate to ask!

Cheers,
Léo

**Comment by adriweb** [comment]
Actually, those files are in a submodule (different git repo).
Easy solution: remove the downloaded CEmu folder and clone the repo that way instead: `git clone --recursive https://github.com/CE-Programming/CEmu.git`.
Then it should work

I'll add a specific error in the .pro file in such cases, thanks.

**Comment by josephscade** [comment]
Thank you for you soooooooo fast reply,
Have a nice day,
Thanks again
