### ISSUE TITLE
OS keypad scanning doesn't behave like on HW

### ISSUE THREAD

**Issue by adriweb** [CE-Programming/CEmu#259]
I just happened to try https://usercontent.irccloud-cdn.com/file/J3zZLVEQ/MANDRAGO.8xp .
And contrary to the real calc where everything is fine (just tested again to be sure), whenever a key is pressed in CEmu, it behaves as if the user was holding it.

By the way, it turns out that this also wasn't working in CEmu v1.0. So, it looks like this wasn't really much of a blocking issue in the past or we'd have gotten complaints earlier... I guess it can "not be" a blocking issue this time as well...

_Note: the game source that deals with that is:_
```c
void startKeys()
{
    (*(uint8_t*)0xF50000) = 3; // continuous
}

void stopKeys()
{
    (*(uint8_t*)0xF50000) = 0;
}

uint8_t isKeyPressed(uint16_t key)
{
    uint8_t* addr = (uint8_t*)(0xF50000 + (uint8_t)(key >> 8));
    uint8_t mask = key & 0xFF;
    return ((*addr)&mask) ? 1 : 0;
}
```
And we have:
```c
#define KEY_DOWN    0x1E01
#define KEY_LEFT    0x1E02
#define KEY_RIGHT   0x1E04
#define KEY_UP      0x1E08
```

**Comment by jacobly0** [comment]
This is the program's fault because the os interrupt handler changes the scanning mode.  OTOH, not sure why exactly behavior differs from HW.

**Comment by adriweb** [comment]
issue title/content reworded, as it had incorrect assumptions.

**Comment by jacobly0** [comment]
BTW, here's a much simpler repro that never touches continuous mode: [keywatch.zip](https://github.com/CE-Programming/CEmu/files/2151047/keywatch.zip) (`on` to exit)

**Comment by mateoconlechuga** [comment]
wut
