### ISSUE TITLE
Improved keypad

### ISSUE THREAD

**Issue by MateoConLechuga** [CE-Programming/CEmu#26]
If you would be so kind to commit some keypad changes, that would be  fantastic :)

**Comment by MateoConLechuga** [comment]
Pretty please? :)

**Comment by adriweb** [comment]
Remote highlight of jacobly in IRC

**Comment by MateoConLechuga** [comment]
Remote jacobly bump

**Comment by adriweb** [comment]
jacobly plz

**Comment by adriweb** [comment]
For those wondering, jacobly's branch with improved keypad is here: https://github.com/CE-Programming/CEmu/tree/keypad
(it probably needs rebasing :P)

**Comment by adriweb** [comment]
keypad branch merged into master, with new and improved fancy things 🎉
