### ISSUE TITLE
Settings for adjusting console text colors

### ISSUE THREAD

**Issue by KryptonicDragon** [CE-Programming/CEmu#262]
Maybe add options in the settings dock to change the background and foreground colors of the text in the console dock, allowing for separate settings for "normal" and "error" text.
As well as options to have the text colors fit the OS theme.

**Comment by mateoconlechuga** [comment]
The console now just uses the os theme. It doesn't really make sense to me to make the whole thing configurable since you can already just use specific text color background and foreground.
