### ISSUE TITLE
Clearing CEmu console via Form feed no longer works

### ISSUE THREAD

**Issue by KryptonicDragon** [CE-Programming/CEmu#263]
What's wrong, and with what software version?
---------------------------------------------
**Operating System:** Windows 10 x64 v1803
**CEmu version:** v1.1dev (git: e4efbd8)
**Describe your issue:**  Clearing the console dock via a form feed character in a debug print no longer works.

What are the steps to reproduce this issue?
-------------------------------------------
1. Make a C program with `dbg_sprintf(dbgout, "\f");`
2. Run the program in CEmu
3. Look at the console dock and watch as it doesn't get cleared

**Comment by mateoconlechuga** [comment]
Of course it doesn't work; have you not been paying attention :P

**Comment by mateoconlechuga** [comment]
So to clear the console now you do this:

*(char*)0xFD0000 = 1;

Eventually this will be turned into a debug macro, but for now it should be simple enough.
