### ISSUE TITLE
Feature request: conditional breakpoints

### ISSUE THREAD

**Issue by PeterTillema** [CE-Programming/CEmu#265]
There are many cases where you have to use conditional breakpoints, like only stop at `$D1A881` when the program running is not program X etc. Not sure how that would look like though.

**Comment by adriweb** [comment]
Probably relatively easy to do with a breakpoint callback/handler in Lua once that's done :P
Until then, uh... I doubt we'll add things like that, it'd be a bit too complicated to have to handle some sort of custom conditional expression parsing (is it even scripting, for saying "when program X is running" ?)

**Comment by adriweb** [comment]
WIth source-level debugging and stack vars able to be inspected, maybe this could come earlier than expected somehow, to some extent.
@jacobly0 would know...

**Comment by mateoconlechuga** [comment]
No Adriweb.

**Comment by adriweb** [comment]
Apparently, we need more "specs" as to what would be nice to have. I'm definitely not against having more details, use cases etc. for each possible sub-feature of this. What kind of conditional expressions or simple tests would we want? Things like that.
I guess we can assign people and decide how to do it after it's clearer.

**Comment by mateoconlechuga** [comment]
Added this to issue #252 in order to clean up the issue list.
