### ISSUE TITLE
Key history shows all keys twice

### ISSUE THREAD

**Issue by PeterTillema** [CE-Programming/CEmu#267]
(Thanks for reporting an issue! Please make sure to fill out the blanks below.)

What's wrong, and with what software version?
---------------------------------------------
**Operating System:**
Windows 10
**CEmu version:**
CEmu 1.1dev (git: 8c407aa)
**Describe your issue:**  
Whenever you press any key, it appears twice in the Key History dock.

What are the steps to reproduce this issue?
-------------------------------------------
1. Open the Key History dock
2. Press some keys

Any logs, error output, screenshot, other comments...?
-----------------------------------------------------
<img src="https://i.imgur.com/XHHwUjN.png">

**Comment by adriweb** [comment]
Huh... I don't have an issue with a master build. Your version 8c407aa is "old". Try with an updated build

**Comment by PeterTillema** [comment]
Yep, that fixed it.
