### ISSUE TITLE
Poor FPS in BOTW with AMD GPUs

### ISSUE THREAD

**Issue by TheYoshiGuy** [CE-Programming/CEmu#268]
(Thanks for reporting an issue! Please make sure to fill out the blanks below.)

What's wrong, and with what software version?
---------------------------------------------
It's slow on AMD GPUs playing BOTW

What are the steps to reproduce this issue?
-------------------------------------------
1. Buy AMD GPU
2. Open latest CEmu
3. Load BOTW

Any logs, error output, screenshot, other comments...?
------------------------------------------------------
Yeah also where to download roms?

**Comment by adriweb** [comment]
CEmu isn’t Cemu, you got the wrong website ^^

**Comment by LAX18** [comment]
Furthermore, downloading ROMS of games you do not own is illegal and highly discouraged.

**Comment by ReaperOfSouls1909** [comment]
my amd gpu isnt slow help i want nvidia bugs like flocker!!

**Comment by adriweb** [comment]
See my comment above, CEmu ≠ Cemu.
