### ISSUE TITLE
Disassembler occasionally does not correctly disassemble.

### ISSUE THREAD

**Issue by Legend-of-iPhoenix** [CE-Programming/CEmu#270]
What's wrong, and with what software version?
---------------------------------------------
**Operating System:** Mac. (I don't think this matters)
**CEmu version:** CEmu 1.0dev_ea90601-dirty
**Describe your issue:**  The disassembler does not always disassemble correctly when there could be multiple options for the disassembly.

What are the steps to reproduce this issue?
-------------------------------------------
1. Open the disassembler
2. Hop to RAM location `$021D94` (equate `CpHLDE_s`). (This is just one example, I'm sure there are others)
The assembled hex at that location is `C3733B0B`, which the disassembler incorrectly turns into `.dl $3B73C3 \ dec bc`, when it should be `jp $0B3B73`.

Any logs, error output, screenshot, other comments...?
-------------------------------------------------------
Here's the incorrect disassembly, in-situ:
```
021D84     C3163B0B      jp $0B3B16
021D88     C3283B0B      jp $0B3B28
021D8C     C33A3B0B      jp $0B3B3A
021D90     C35D3B0B      jp $0B3B5D
021D94     C3733B        .dl $3B73C3
021D97     0B            dec bc
021D98     C36D3B0B      jp $0B3B6D
021D9C     C3073B0B      jp $0B3B07
021DA0     C3013B0B      jp $0B3B01
021DA4     C37A3B0B      jp $0B3B7A
```

**Comment by Legend-of-iPhoenix** [comment]
```
<jacobly> that CEmu is from Feb 4...
<jacobly> disasm was completely rewritten Apr 16
<iPhoenix> Ask jcgter not me, it was his CEmu, not mine. (I'm not on my usual laptop, and he became busy)
<jacobly> it's also likely a TIOS/user program bug that I can't do anything about :P
<iPhoenix> Oh fun.
```

**Comment by jacobly0** [comment]
This means that a buggy TIOS/user program jumped to the address 0x21D97.  Also, this version of CEmu is from way before the disassembler was rewritten, and I don't know if the current disassembler even supports that yet...
