### ISSUE TITLE
Add support for TASing

### ISSUE THREAD

**Issue by onlymx13** [CE-Programming/CEmu#275]
Recording and replaying TASes would be a very interesting feature for CEmu. If I'm not mistaken, @mateoconlechuga once said on a different website that he would not be against TASing features for CEmu. Therefore, I want to have it documented as an issue as there are basically no other emulators that allow TASing, because BizHawk doesn't do it well.

**Comment by adriweb** [comment]
It seems to me that this could be considered like a mix of #19 (Lua scripting) + #178 (deterministic autotester), basically.

**Comment by mateoconlechuga** [comment]
Hey things are deterministic now

**Comment by mateoconlechuga** [comment]
Added this to issue #252 in order to clean up the issue list.
