### ISSUE TITLE
Check for Update

### ISSUE THREAD

**Issue by benjaminBrownlee** [CE-Programming/CEmu#279]
**Operating System:** Windows 10 
**CEmu version:** v1.1

Despite being up to date CEmu prompts me to update every launch with a link to a release (v1.1) I already have installed. The config file has the following settings regarding updates and version:

```
[General]
check_for_updates=2
version=1.1
...
```

**Comment by adriweb** [comment]
Alright, the latest release (a new one for real, now) should fix that now... hopefully.
All builds (win/mac/linux) updated.

**Comment by alberthdev** [comment]
Yeah, this was a misunderstanding - I saw that the dev version was marked "v1.1dev", so figured that the actual release version would be this way, too...

Should be fixed with d0fd69f.
