### ISSUE TITLE
Dumper not working

### ISSUE THREAD

**Issue by Ambyte00** [CE-Programming/CEmu#280]
(Thanks for reporting an issue! Please make sure to fill out the blanks below.)

What's wrong, and with what software version?
---------------------------------------------
**Operating System:** MacOS X
**CEmu version:** v1.1.1
**Describe your issue:**  
After saving the dumper program and sending it to my TI-83 Premium CE and running it with the Assembler, it says done, but no files are created. I've tried several times, I've updated CEmu and then saved the dumper from the newer version and sent it to my calculator and tried again and I experienced the same issue.

What are the steps to reproduce this issue?
-------------------------------------------
Running the dumper program.

Any logs, error output, screenshot, other comments...?
------------------------------------------------------
No.

**Comment by mateoconlechuga** [comment]
Does it say "Dumping Segment A..." or anything like that when running?

**Comment by adriweb** [comment]
Also, what's the OS version on the calculator?
As well at the datecode on the back (to the right of the serial number, it looks like "L-0317E") ?

**Comment by Ambyte00** [comment]
@mateoconlechuga I press enter and it instantly says done.
@adriweb My calculator is on 5.3 and the date code is L-0318L. (also what does the date code do?)

**Comment by jacobly0** [comment]
That means that you don't have enough ram.  You need at least 65535 RAM FREE which you can check on the `2nd` + `mem` + `2` menu.  You can get more ram by deleting (`del`) and/or archiving (`enter`) existing variables in submenus of that menu.

**Comment by Ambyte00** [comment]
@jacobly0 I actually thought that could've been it but didn't try because it was pretty late at night! I'll try in a minute!
