### ISSUE TITLE
Not responsive to touch screen?

### ISSUE THREAD

**Issue by Stephan-P** [CE-Programming/CEmu#282]
What's wrong, and with what software version?
---------------------------------------------
**Operating System:** Windows 10
**CEmu version:** CEmu 1.1dev (git: d0fd69f)
**Describe your issue:**  
Using CEmu as a TI-84 emulator only, I find that it is not very responsive to touch screen. 
Key presses on the touch screen (or Smartboard) are barely registered. 
Possibly related: Skin scaling is set to 70%

What are the steps to reproduce this issue?
-------------------------------------------
1. Setup CEmu with just the Display and the Keyboard, all other docks and windows disabled, Menu and status bar disabled.
2. On my particular laptop I had to set the scaling to 70% for best fit in the screen canvas
3. Try to control the TI-84 through the touch screen

Any logs, error output, screenshot, other comments...?
------------------------------------------------------
none

**Comment by jacobly0** [comment]
Could you test using the touchscreen with the [latest development build](https://jacobly.com/CEmu/latest/CEmu64.exe)?  If possible, also test if touching multiple keys at once works.

**Comment by runer112** [comment]
That's better, but there are still problems:

 * Touching a key and then dragging off of the key doesn't release the key (until the touch is eventually lifted, wherever that may be).
 * Windows' default touch and hold to right-click behavior should be suppressed. It's too easy to accidentally activate CEmu's key hold.
 * Multi-touch is to be foiled by another default right-click trigger.

**Comment by runer112** [comment]
Another suggestion, if possible: blow up the hit-boxes for keys when using touch.

**Comment by mateoconlechuga** [comment]
We just need to be sure we can still activate key holds using touch in some way.

**Comment by mateoconlechuga** [comment]
*bump*

Also, I realized we need a way for CEmu to have a GUI option to disable the keyboard interfacing in case someone uses an on-screen keyboard.

**Comment by adriweb** [comment]
@Stephan-P any news?
We're aiming for a release sometime soon - any feedback (you can try the latest development builds) would be helpful!

**Comment by Stephan-P** [comment]
Yes of late, I've been a quiet, yet daily user. .
I'll install the latest development build today and test out how it works on touch screen and smart board. I've got some time for that.
Further, I hope that these 1-2 pixels offset in the positioning of the keypad Dock jabs been fixed.
Ik get back to you before tonight.
Stephan

Stephan Paternotte
Roeselarestraat 60
1066 SX Amsterdam
Nederland
------------------------------------
T: 020 6171388<tel:+31206171388>
M: 06 17694623<tel:+31617694623>
E: stephan@paternottes.net<mailto:stephan@paternottes.net>

________________________________

**Comment by adriweb** [comment]
Note that you'd need to try that one: http://jacobly.com/CEmu/master/latest/CEmu64.exe since the MSVC builds aren't working lately.

**Comment by Stephan-P** [comment]
Yeah, I noticed that the development builds got stuck on september.
So, I'll use Jacobly's now.

**Comment by Stephan-P** [comment]
Alright!
Jacobly's build works well on my touch screen as well as the Smart Board.
AFAIC this issue can be closed. NICE!
