### ISSUE TITLE
RAM from hardware calculator

### ISSUE THREAD

**Issue by onlymx13** [CE-Programming/CEmu#285]
People often say that their physical calc is having an issue. Many of the issues for Cesium are people complaining about their specific calculator. In CEmu, you can save and restore states. If those people could make a state from their hardware calculator, they could provide it for better debugging.

**Comment by mateoconlechuga** [comment]
You can now import / export ram states with 155f1eb. I don't see much point in making a tool to get it from a real calculator, it's really not hard to do if someone really needs to do that and sort of outside the scope of CEmu.
