### ISSUE TITLE
TI-Basic "debugging"

### ISSUE THREAD

**Issue by adriweb** [CE-Programming/CEmu#286]
We have quite a few information already (and are able to retrieve some more from some known memory locations) in order to have an idea of the current execution state of a TI-basic program.

With this information, we should be able to make some kind of "debugger", or at least a live-viewer of what's going on:
* current program being run (`basic_prog`)
* current line (`curPC`)
* current variables _(we have that already with the var list/viewer)_

The variable viewer as of now can already show _(and reformat, but I guess we can't use that feature here, unless we have original line info...?)_ 

This "TI-Basic" debugger will likely require a new dedicated dock in order to maximize its usefulness and UX, with a custom UI being split in 2 parts:
* [x] a code viewer (like the current one, with syntax highlight, line numbers etc.)
   * [x] highlighting the currently executing line (and fetched parts)
   * [x] ability to stop and step
* [ ] a variable viewer -> later on, see #456
  
I'll add that to the "v2.0 - source-level debugging" release target, as it seems quite appropriate, but I guess we'll see over time how it develops.

**Comment by adriweb** [comment]
( Dev to be done in a `feature/basic-dbg` branch )

**Comment by mateoconlechuga** [comment]
I want a label tracker

**Comment by adriweb** [comment]
todo: think how/if #287 can help with TI-Basic debugging.

**Comment by adriweb** [comment]
Splitting this so that current working stuff can be merged into master, and creating another issues for the rest/improvements to be done later.
