### ISSUE TITLE
Initiate drag from screen to capture screenshot

### ISSUE THREAD

**Issue by runer112** [CE-Programming/CEmu#290]
The captured screenshot should become attached to the "drag," allowing it be "dropped" elsewhere as a PNG file. For reference, this feature request comes from having the same functionality in Wabbitemu.

**Comment by adriweb** [comment]
Hmmmm https://github.com/CE-Programming/CEmu/commit/504863f8edf44d54d3731e8d10c87c369bc55a81

Also, quoting myself from 2016 on #cemu-dev quoting @Vogtinator in some IRC logs: 
```
[2016-04-26 03:44:17] <Adriweb_> "An idea which enables (a platform independent) way to copy files:
[2016-04-26 03:44:17] <Adriweb_> reimplement QAbstractItemModel::mimeData() so it contains a file uri-list there return a custom QMimeData implementation which reimplements QMimeData::retrieveData() 
[2016-04-26 03:44:18] <Adriweb_> The basic idea in the QMimeData::retrieveData() implementation is that you create a temporary file write the contents to the temp file return the path to the temp file this will start a copy of the temp-file to the drop destination in the desktop."
[2016-04-26 03:45:07] <Adriweb_> to be able to drag'n'drop the screen as a PNG to the desktop or elsewhere
```

Not sure how relevant all that is now, though.

**Comment by sdeutsch354** [comment]
> Hmmmm [504863f](https://github.com/CE-Programming/CEmu/commit/504863f8edf44d54d3731e8d10c87c369bc55a81)
> 
> Also, quoting myself from 2016 on #cemu-dev quoting @Vogtinator in some IRC logs:
> 
> ```
> [2016-04-26 03:44:17] <Adriweb_> "An idea which enables (a platform independent) way to copy files:
> [2016-04-26 03:44:17] <Adriweb_> reimplement QAbstractItemModel::mimeData() so it contains a file uri-list there return a custom QMimeData implementation which reimplements QMimeData::retrieveData() 
> [2016-04-26 03:44:18] <Adriweb_> The basic idea in the QMimeData::retrieveData() implementation is that you create a temporary file write the contents to the temp file return the path to the temp file this will start a copy of the temp-file to the drop destination in the desktop."
> [2016-04-26 03:45:07] <Adriweb_> to be able to drag'n'drop the screen as a PNG to the desktop or elsewhere
> ```
> Not sure how relevant all that is now, though.

Was this feature disabled?

**Comment by mateoconlechuga** [comment]
It used to exist. And then I removed it because it didn't work quite how I wanted it to due to Qt weirdness. I think I have a plan on how to improve it; I might not get a chance to add it until Monday night though.

**Comment by mateoconlechuga** [comment]
added it back in, a development build should be ready for you in the next hour or so.

**Comment by sdeutsch354** [comment]
Thank you so much
