### ISSUE TITLE
Add "Copy PNG" button to Capture panel

### ISSUE THREAD

**Issue by runer112** [CE-Programming/CEmu#291]
This button would have the same functionality as the "Copy screen to clipboard" menu item. It would sit in the same "Screenshot" group with the existing "PNG" button, which I'd suggest be renamed "Save PNG" to match.

**Comment by mateoconlechuga** [comment]
Okay I'll add it this when I add drag and drop copy abilities

**Comment by adriweb** [comment]
That's fine, I can take care of it quickly.
