### ISSUE TITLE
Console Problems

### ISSUE THREAD

**Issue by DevBlocky** [CE-Programming/CEmu#292]
What's wrong, and with what software version?
---------------------------------------------
**Operating System:** Windows 10 Pro
**CEmu version:** v1.1.1
**Describe your issue:**  
No messages are appearing in Console

From other examples on issues, it seems there are supposed to be more than 1 message in Console when starting up the application, but there is only one for me and it reads

> [CEmu] Initialized Server [Calculator | cemu-16948]

I tried outputting a string to `dbgout` in a C program I wrote, but this did not log anything. I even tried the binary from the [Debugging Example](https://github.com/CE-Programming/toolchain/tree/master/examples/debugging) on toolchain, but still no luck with Console. (NOTE: The debugging example was able to attach to the debugger and create breakpoints and such)

What are the steps to reproduce this issue?
-------------------------------------------
There seems to be no steps, atleast for me. This has been happening since I downloaded and ran the program. Maybe it's an issue with the ROM?

Any logs, error output, screenshot, other comments...?
------------------------------------------------------
![Screenshot of Console window](https://i.imgur.com/De3DzEf.png)
```
[CEmu] Initialized Server [Calculator | cemu-16948]
```

**Comment by blockba5her** [comment]
and the statement above is why i shouldn't program

but anyways thank you.

**Comment by mateoconlechuga** [comment]
If you are on windows, you can activate the console interface through "Calculator" > "Toggle Windows Console". You may need to restart CEmu for it to take effect, but in theory it should just work.
