### ISSUE TITLE
Can't press second and alpha at the same time

### ISSUE THREAD

**Issue by WilmeRWubS** [CE-Programming/CEmu#293]
latest windows 10 
cemu 1.1.1

I cant press second and aplha at the same time like in oiram(mario) while on my real ti84 plus ce-t it does work.

**Comment by mateoconlechuga** [comment]
You can't on the keyboard?

**Comment by WilmeRWubS** [comment]
What do you mean with your question?

**Comment by runer112** [comment]
I think he's asking if you're trying using the visual keypad or a physical keyboard. Pressing two buttons at once on the visual keypad with one mouse pointer doesn't work, of course (and multi-touch support for touchscreens is iffy). But you should be able to press multiple keys at once on a physical keyboard. 2nd is `;` and alpha is `'`.

If you press both of these on a physical keyboard, does it work? If not, can you look at what the visual keypad shows when you do this? Does it highlight both keys as being pressed anyway, or just one?

**Comment by WilmeRWubS** [comment]
O i mean my real life keyboard. I don't have two mice XD

**Comment by runer112** [comment]
In that case, can you answer my last two questions?

**Comment by WilmeRWubS** [comment]
pressing ' doesnt do the alpha function.

**Comment by adriweb** [comment]
Just in case, make sure to click on the virtual screen first, then try pressing keys on your computer keyboard again.

**Comment by WilmeRWubS** [comment]
I just did what you suggested but alpha still doesnt work somehow.

**Comment by runer112** [comment]
What happens if you press alpha (`'`) first and then 2nd (`;`)? Presumably you should see alpha work when it's the only key pressed, but what happens when you add 2nd?

If that still doesn't let both keys be pressed together, can you go to http://en.key-test.ru/ and press both keys together there and confirm that both keys light up blue together? Although it seems unlikely, it's possible that the combined keypresses simply aren't happening according to your keyboard/OS.

**Comment by WilmeRWubS** [comment]
Tried http://en.key-test.ru/ everything working fine. ' is just doing nothing at all.

**Comment by runer112** [comment]
If the apostrophe key works fine outside of CEmu, I'm out of ideas as to what's wrong. The only last-ditch thing I might suggest is to try the latest developer version of CEmu: http://jacobly.com/CEmu/master/latest/CEmu64.exe

**Comment by WilmeRWubS** [comment]
Also not working?? is it of the rom????

**Comment by runer112** [comment]
If the alpha button on the virtual keypad works, then there's nothing wrong with the ROM. I'm currently out of ideas why that would work but not the keyboard key mapped to alpha, though.

**Comment by WilmeRWubS** [comment]
Lol I also dont know whats wrong because my key should work fine

**Comment by WilmeRWubS** [comment]
''''''''''''''' as you can see

**Comment by WilmeRWubS** [comment]
O I forgot to mention that I couldnt find the alpa key on my keyboard so I switched to wabbitemu as keyboard option. With this one I could find the alpha key and there i couldnt do second and alpha at the same time.

**Comment by WilmeRWubS** [comment]
Same goes with jsTIfied

**Comment by mateoconlechuga** [comment]
Personally I think that this is just an issue of selecting the wrong keymap. If you haven't tried Extras > Reset CEmu I would suggest you do that.
