### ISSUE TITLE
Key history window

### ISSUE THREAD

**Issue by Stephan-P** [CE-Programming/CEmu#301]
CEmu v1.2dev (git: 749970e)
Windows 10 18.03

Some nice-to-haves regarding the Key history window.

1. The Key History window lists all key presses vertically. If I remember correctly TI SmartView lists the key presses in line. If key presses remain vertically listed, then this would justify a more narrow window. Unfortunately, narrowing the Key History window is limited by a lot of items in its status bar. How about doing away with the new lines and list the key presses inline?
2. Enable the Key History window. If I close the CEmu main window, the Key History window remains open and CEmu is not shut down. If I then close the Key History window as well, CEmu is still not shut down. I would expect that closing CEmu also closes the Key History window.
3. It would be nice if status (on/off), size and position of the Key History window is saved and restored for a next run of CEmu.

**Comment by Stephan-P** [comment]
Thanks very much, Mateo.
I tested it this morning with CEmu v1.2dev (git: f919060)
It's a great improvement indeed and I think that I'll adjust the Dutch text for "Clear History" into a short and simple "Clear" so that he window can be narrowed down further.

A few remarks.
1. The Key History dock is not listed among the docks: RMB-Docks, but rather RMB-Extras-Key history. (Or should I do another clean install of CEmu?)
2. If enabled via RMB-Extras, there is no easy way to disable the Key history dock again. The Key History dock does not have a close button.
3. The only way to remove Key History dock(s) is to enable UI-edit mode, then click the respective close button(s) and leave GUI-Edit mode again
4. If already enabled, clicking RMB-Extras-Key History adds another Key History window. One can add as many as one likes.
5. Size of the Key History dock appears to be saved alright, but upon restart CEmu places this dock off position: a full title bar height lower and a couple of pixels right of its previous position.

If all this has a low priority, then I understand. I'm aware of this different use case scenario of mine.

**Comment by mateoconlechuga** [comment]
Leave me alone.

**Comment by adriweb** [comment]
Yeah most of this is due to the GUI edit mode - not much we can do about this very specific case without altering a more global behaviour, which we probably don't want, right now.

**Comment by mateoconlechuga** [comment]
Fine, I fixed it.

**Comment by mateoconlechuga** [comment]
Reopened because of the can't reproduce issue of dock shifting.
