### ISSUE TITLE
Wait states are not emulated correctly.

### ISSUE THREAD

**Issue by TheLastMillennial** [CE-Programming/CEmu#303]
---------------------------------------------
**Operating System:** Windows 10 
**CEmu version:** CEmu v1.2 (git: 1621ab4) 
**Describe your issue:**  
CEmu is accepting wait state values that a physical calculator wont accept, such as -1, 0, or 256 without crashing or slowing to a crawl. It should only accept values up to 255

What are the steps to reproduce this issue?
-------------------------------------------
1. Install [ADVSPEED ](http://ceme.tech/DL1755)
2. Run it and accept the terms
3. Press the up arrow key 4 times
4. Press [3] to disable safety restrictions
5. Watch CEmu not crash. Or if you're on a physical calculator, watch it crash.

Alternative steps:
1. Install [ADVSPEED ](http://ceme.tech/DL1755)
2. Run it and accept the terms
3. Press [enter] to set a custom value
4. Enter any number
5. Press [enter] to set the value
6. Disable safety restrictions if you need to
7. Watch CEmu accept nearly any number (it doesn't like numbers with decimals though)

Any logs, error output, screenshot, other comments...?
------------------------------------------------------
No unusual logs.
[APNG](https://i.imgur.com/26P5gqA.png)
CEmu seems to be taking the values, such as 256 and subtracting 256 from it, that would make sense why it reset the wait states to 0 when I re-ran the wait state changer program. Again, when I try to input the same numbers on my physical calculator, it just crashes.

**Comment by mateoconlechuga** [comment]
I don't think I would classify this as a bug.
