### ISSUE TITLE
Something is up with the wait command.

### ISSUE THREAD

**Issue by onlymx13** [CE-Programming/CEmu#306]
What's wrong, and with what software version?
---------------------------------------------
**Operating System:** Windows 10
**CEmu version:** v1.2
**Describe your issue:**  
I run a simple 'wait 6 seconds' program and find the calculator waiting 12-14 seconds.

What are the steps to reproduce this issue?
-------------------------------------------
It's detailed in the apng below.

Any logs, error output, screenshot, other comments...?
------------------------------------------------------
![](https://i.ibb.co/cJkhZsh/wait-command.png)

**Comment by onlymx13** [comment]
Note that this does NOT happen on my hardware calc.

**Comment by jacobly0** [comment]
I can repro with v1.2 but not on master, so I'm assuming this has already been fixed.

**Comment by jacobly0** [comment]
This repro'd intermittently, needs investigation.

**Comment by adriweb** [comment]
From what was discussed on IRC, "the issue is in GetCSC", @jacobly0 said.
No idea yet as how to make CEmu behave more like the hardware regarding this so far, though.

**Comment by onlymx13** [comment]
Doesnt repro for me on master
