### ISSUE TITLE
Virus detection on Windows Defender

### ISSUE THREAD

**Issue by faulenroc** [CE-Programming/CEmu#310]
(Thanks for reporting an issue! Please make sure to fill out the blanks below.)

What's wrong, and with what software version?
---------------------------------------------
**Operating System:** …  
**CEmu version:** … (see in the `About CEmu` menu)  
**Describe your issue:**  
… (including, if applicable what you expect vs. what happens)  

What are the steps to reproduce this issue?
-------------------------------------------
1. …
2. …
3. …

Any logs, error output, screenshot, other comments...?
------------------------------------------------------
…

**Comment by jacobly0** [comment]
False positives are common with less popular executables.

**Comment by debrouxl** [comment]
Heh. Once in every while, the detection patterns in pro-virus software fires even on popular, but harmless executables. Over the years, installers for other programs I maintain were hit as well. And we all know all variants of pro-virus software constantly fail, on a daily basis and an epic scale, to detect actual real-world malware (some of which even leverages the numerous bugs in said pro-virus software). Pro-virus software sucks, full stop :)
