### ISSUE TITLE
LCD isn't turning off

### ISSUE THREAD

**Issue by LogicalJoe** [CE-Programming/CEmu#311]
The C code
`#define LCD_POWER (1 << 11)`
`lcd_Control &= ~LCD_POWER;`
Causes the LCD to go crazy:
![snow](https://user-images.githubusercontent.com/47825483/54883851-93706180-4e40-11e9-8fd8-e97a1bfe3968.gif)
Instead of turning it off.

**Comment by adriweb** [comment]
2da1219687a76ef80b2f1261e2813bca710b2efb
