### ISSUE TITLE
Appvar previews display hex incorrectly

### ISSUE THREAD

**Issue by commandblockguy** [CE-Programming/CEmu#312]
**CEmu version:** v1.2dev (git: 76c6458)

In the "Calculator Variables" section, in the hexadecimal appvar preview, bytes that have a upper nibble of 0 (value < 0x10) will only display the lower nibble. This means it is impossible to tell the difference between appvars containing values 0x12 and 0x0102, for example.

Steps to Reproduce:
-------------------------------------------
1. Compile the following using the toolchain:
```c
void main {
    ti_var_t slot;
    char temp[5] = {0, 0, 0, 0, 0};

    ti_CloseAll();

    slot = ti_Open("test", "w");
    ti_Write(temp, 1, 5, slot);
}
```
2. Transfer and run the program
3. Click "View calculator variables" in the "Calculator receive" section. The preview for the appvar `test` will be `00000`, while the expected value is `0000000000` as 5 bytes were written.

**Comment by adriweb** [comment]
Fixed upstream, will update CEmu
