### ISSUE TITLE
Too many popup errors crash CEmu

### ISSUE THREAD

**Issue by TheLastMillennial** [CE-Programming/CEmu#317]
---------------------------------------------
**Operating System:** Windows 10 Pro 
**CEmu version:** CEmu v1.2dev (git: 8e50261)
**Describe your issue:**  CEmu crashes when too many popup errors occur, perhaps limit how many can appear at once?

What are the steps to reproduce this issue?
-------------------------------------------
1. Turn off emulation throttle.
2. Send an absurd amount of files (I sent 302) to the calculators memory when it doesn't have the space for it.
3. Once the memory fills completely up, enjoy hundreds of popup errors notifying you to check the console.

Any logs, error output, screenshot, other comments...?
------------------------------------------------------
Nope.

**Comment by adriweb** [comment]
Setting this as v1.3 target, which should normally be (soon) the last release before any new major one (which would be v2.0 with source-level debugging)
