### ISSUE TITLE
[Autotester] Check return value of C program

### ISSUE THREAD

**Issue by PeterTillema** [CE-Programming/CEmu#319]
Would be nice if you can check the HL register after executing a C program, in order to check the (error) code.

**Comment by adriweb** [comment]
Once we figure out / decide on a safe way to retrieve register values at a given time, we can work on that.
Until then, I suppose you should try to somehow save the values in a known safe memory location, and hash that just like any other area in the autotest file.

**Comment by adriweb** [comment]
Well, I guess we can reopen that when/if needed.
