### ISSUE TITLE
(Not issue) Idea!

### ISSUE THREAD

**Issue by JaroslavN** [CE-Programming/CEmu#32]
If the cemu comes out on android or ti-nspire cx or ...
would you be able to send programs from the ti-84ce to the nspire cx or phone ?
![cemu](https://cloud.githubusercontent.com/assets/16990273/13203363/94e5cdb4-d8b6-11e5-8137-791ba092c07c.png)

**Comment by MateoConLechuga** [comment]
This... isn't an emulator feature. ;)

**Comment by adriweb** [comment]
Unless done with Firebird and CEmu, but that'd be kind of pointless between those emulators :P
