### ISSUE TITLE
Unable to download development build via repository on Arch Linux

### ISSUE THREAD

**Issue by JingYenLoh** [CE-Programming/CEmu#320]
What's wrong, and with what software version?
---------------------------------------------
**Operating System:** Arch Linux
**CEmu version:** N.A.
**Describe your issue:**  
Per title, download fails with maximum file size exceeded error.

What are the steps to reproduce this issue?
-------------------------------------------
1. Go to the [Linux development build link](https://software.opensuse.org/download.html?project=home%3Aadriweb%3ACEmu&package=cemu&locale=en)
2. Follow the instructions for "Add repository and install manually" to add repo.
3. Try to install cemu via `pacman -S home_adriweb_CEmu_Arch/cemu`

Any logs, error output, screenshot, other comments...?
------------------------------------------------------
```
➜ sudo pacman -S home_adriweb_CEmu_Arch/cemu
resolving dependencies...
looking for conflicting packages...

Packages (1) cemu-1.3-0

Total Download Size:   0.78 MiB
Total Installed Size:  2.28 MiB

:: Proceed with installation? [Y/n] 
:: Retrieving packages...
error: failed retrieving file 'cemu-1.3-0-x86_64.pkg.tar.xz' from download.opensuse.org : Maximum file size exceeded
warning: failed to retrieve some files
error: failed to commit transaction (download library error)
Errors occurred, no packages were upgraded.
```

**Comment by adriweb** [comment]
Unfortunately I don't think we can do much to help on our side but to point you to forums etc.

You can try to download the package manually and install it?

See also:
- https://github.com/msys2/MSYS2-packages/issues/1025#issuecomment-341942410
- https://forum.artixlinux.org/index.php?topic=568.msg4451#msg4451

**Comment by maxrd2** [comment]
I had same problem with my arch linux repository, repository.db contains file with some filesize that is stored in repository.db. Pacman asks curl to download N bytes of that file.
If actual filesize on server is < N, the server will respond with this error.

In other words, xxxx.pkg.tar.xz file that was added with repo-add to repo.db.tar.xz is different size from xxxx.pkg.tar.xz on server.

**Comment by JingYenLoh** [comment]
I recently attempted this again and I am able to install CEmu now :) It seems the issue only existed in that build's `repository.db`. I consider this issue resolved on my end.

**Comment by adriweb** [comment]
Great!

**Comment by JingYenLoh** [comment]
That's an incredibly fast response :O I forgot to include this in my response, but thanks for making this amazing software!

**Comment by benoitldr** [comment]
just `sudo pacman -S home_adriweb_CEmu_Arch/cemu` do the tricks for me, install via yaourt is still lead to the same error
