### ISSUE TITLE
keypad assertion fails

### ISSUE THREAD

**Issue by nmosier** [CE-Programming/CEmu#323]
(Thanks for reporting an issue! Please make sure to fill out the blanks below.)

What's wrong, and with what software version?
---------------------------------------------
**Operating System:** macOS 10.14.5
**CEmu version:** CEmu v1.3dev (git: 87c3b43)
**Describe your issue:**  CEmu crashes. One of the assertions in gui/qt/keypad/key.h fails, causing the crash. This happens within 1-30 minutes of running CEmu. Not necessarily triggered when buttons are being pressed -- sometimes happens when I click "Run" in Debugging Control (that is, execution was stopped at the time). 

I have also noticed that keys are very sticky / sometimes

What are the steps to reproduce this issue?
-------------------------------------------
1. Open CEmu.
2. Use the keypad for a while.
3. At some point afterwards, CEmu crashes.

Any logs, error output, screenshot, other comments...?
------------------------------------------------------

[crash.txt](https://github.com/CE-Programming/CEmu/files/3418643/crash.txt)

**Comment by jacobly0** [comment]
This indicates an issue with the touch event code, which I am unable to directly test myself.  When I get to a computer, I'll resurrect the touch debug code so you can produce a detailed log of what is going on.

**Comment by jacobly0** [comment]
I added touch logging to the log/touch branch.  It creates/overwrites a file called touch.log in the cwd.  If you can send me the log created when reproducing the assertion fail, I might be able to debug the issue.  Ideally, I would prefer one where it crashes quickly over one that takes longer to crash.

**Comment by adriweb** [comment]
Note that on macOS, the log file will be next to the actual app binary (somewhere like `[...]/CEmu.app/Contents/MacOS/touch.log`).
I got logs in there with a debug build, I'll leave it there in case it crashes as well.

**Comment by nmosier** [comment]
Here is a log of when it took 5 minutes to crash:

[touch.log](https://github.com/CE-Programming/CEmu/files/3426690/touch.log)

**Comment by nmosier** [comment]
And another log, when it took only about 3 minutes to crash:

[touch.log](https://github.com/CE-Programming/CEmu/files/3426707/touch.log)

**Comment by adriweb** [comment]
to re-open if this still happens on latest nightly.
