### ISSUE TITLE
Would Android support be possible?

### ISSUE THREAD

**Issue by jaketheda2** [CE-Programming/CEmu#329]
Please excuse me if this isn't the place to ask, but would it possible to somehow port the Linux version to Android? 

For me personally, it's a lot easier to pick up my phone and press buttons on the touch screen than to use a cursor to manually select the buttons. But, there's really no good equivalent on Android right now. (The only graphing calculator emulator currently on the platform is Wabbitemu, which hasn't been updated in years despite freezing intermittently on good hardware.)

If CEmu was ported, it would fill a gaping hole in the product ecosystem, be infinitely more useful, and make education more affordable (not everyone has a PC and can afford a $100 expense just for a class).

Regardless, thank you to everyone involved for making CEmu in the first place. It's an awesome, indispensable tool, and I'm a huge fan :)

**Comment by adriweb** [comment]
Thanks for the kind words!

Unfortunately, not really, as explained here (for iOS, but same answer): https://github.com/CE-Programming/CEmu/issues/227 and in another similar issue if I remember correctly. 

But please do reach out to TI to let them know you'd be interested in a mobile version of an emulator - the more we tell them, the more likely something may happen, I guess...

**Comment by adriweb** [comment]
I forgot to mention that there are alternatives however, even free ones: Firebird is a TI-Nspire emulator that has a mobile version (and TI doesn't care for some reason), and NumWorks have official free mobile versions too. HP has a free lite HP Prime app too.

**Comment by Stephan-P** [comment]
Here's a decent Android TI-84 Plus emulator. 
https://play.google.com/store/apps/details?id=com.incptmobis.calculatorfree&hl=en_US

**Comment by SoCuul** [comment]
> I forgot to mention that there are alternatives however, even free ones: Firebird is a TI-Nspire emulator that has a mobile version (and TI doesn't care for some reason), and NumWorks have official free mobile versions too. HP has a free lite HP Prime app too.

Hi!
Is there a reason why CEmu has chosen to not support any platforms other than desktop? Even though they wouldn't be the optimal way for using CEmu as intended, it would provide overwhelming benefits for people who wanted to use it.

**Comment by adriweb** [comment]
Well there isn't really anything that wasn't already said here and there, see https://github.com/CE-Programming/CEmu/issues/329#issuecomment-524128972 

We'll see if there's any change next year considering it's going to be the 10-year anniversary of the CE - maybe TI will be more... open-minded regarding community/third-party tools but considering their various online emus (also working on mobile) are rather recent, I wouldn't be so sure.

**Comment by adriweb** [comment]
I'll lock this to prevent further duplicate Q&A but I'll be sure to reply in case things change.
