### ISSUE TITLE
Inaccurate cycle times on block instructions

### ISSUE THREAD

**Issue by calc84maniac** [CE-Programming/CEmu#33]
On the EZ80, block instructions such as LDIR only fetch the opcode bytes on the first iteration, and thus all the following iterations (until the end condition is reached or an interrupt occurs) will run faster. Currently CEmu refetches the opcode bytes every iteration like on the Z80, causing a noticeable performance drop in some programs.

**Comment by MateoConLechuga** [comment]
Fixed with commit 2fd34e8. Thanks!
