### ISSUE TITLE
Cant press alpha and second at the sametime

### ISSUE THREAD

**Issue by Wesleycoding** [CE-Programming/CEmu#330]
(Thanks for reporting an issue! Please make sure to fill out the blanks below.)

What's wrong, and with what software version?
---------------------------------------------
**Operating System:** …  
**CEmu version:** … (see in the `About CEmu` menu)  
**Describe your issue:**  
… (including, if applicable what you expect vs. what happens)  

What are the steps to reproduce this issue?
-------------------------------------------
1. …
2. …
3. …

Any logs, error output, screenshot, other comments...?
------------------------------------------------------
…

**Comment by Wesleycoding** [comment]
You can’t press alpha and second at the sametime.

**Comment by jacobly0** [comment]
With a mouse you can right click a button to toggle holding it down.  With a [url=https://github.com/CE-Programming/CEmu/wiki/Keybindings]keyboard[/url] you can press two keys at once.
