### ISSUE TITLE
How can I combine the screen and the keypad into a simple on-screen version of the calcualtor?

### ISSUE THREAD

**Issue by nexgen91** [CE-Programming/CEmu#331]
Not really an issue, but I dont know how else to get this information...
---------------------------------------------
**Operating System: Windows 10
**CEmu version: 1.3
**Describe your issue: I would like to combine the screen and keypad into an on screen version of the calculator instead of having them side by side or floating, not sure if this is possible?

**Comment by adriweb** [comment]
The generic answer to that is:
1) enable UI Edit mode from the menus
2) move around the docks/windows as you want them to be
3) disable UI edit mode

**Comment by nexgen91** [comment]
This is the[ result](https://imgur.com/undefined) I get when doing that, [this ](https://imgur.com/2rZ2aGe)is what I would like to have

**Comment by briangordon** [comment]
@nexgen91 I had some issues with this at first too, but it is possible to get both the keypad and the screen docked in the left column. Try putting the keypad there first and then dragging the screen up to the top of the column. 

<img width="1920" alt="Untitled" src="https://user-images.githubusercontent.com/1331024/66102069-eb152580-e565-11e9-9bd9-986272ba8d74.png">

**Comment by adriweb** [comment]
Hmm I have more luck moving the keypad below the LCD (and not touching the LCD), although it has to be dropped quite low for the rectangle "preview" position to appear correctly.

**Comment by nexgen91** [comment]
> 
> Hmm I have more luck moving the keypad below the LCD (and not touching the LCD), although it has to be dropped quite low for the rectangle "preview" position to appear correctly.

Thank you, I was finally able to get it to work by doing that 🙂
