### ISSUE TITLE
Key Hold Being Activated on Smartboard

### ISSUE THREAD

**Issue by Kkid2** [CE-Programming/CEmu#332]
I am currently using the latest stable release of CEmu on Windows 10.  Is there a way to disable the hold key functionality?  I am having a problem using CEmu on my Smartboard where a key will become locked down as if right clicked.  I have disabled the press to hold right click on my smartboard, so I'm unsure how the key is getting locked down.  Any help would be greatly appreciated!  Thank you!

**Comment by mateoconlechuga** [comment]
We had a similar issue reported, and it should be fixed in the latest development release, available here by clicking on the "Development" Tab: https://ce-programming.github.io/CEmu/download

**Comment by Kkid2** [comment]
Thanks for the update Matt.  I'll try this release with my students this
week.
