### ISSUE TITLE
Keypad refused to dock under display screen

### ISSUE THREAD

**Issue by tlongfellow** [CE-Programming/CEmu#337]
I'm sure this just user error. I can dock and undock the screen, but the keypad won't dock.
I'm using windows 10 pro w/most recent updates
Freshly downloaded ver. 1.3 of emulator
The keypad will not dock under the screen.
What's wrong, and with what software version?

**Comment by adriweb** [comment]
Yeah, Qt can be a pain sometimes regarding to docking. It will eventually work, you have to find what position/area the mouse drop has to be on for it to work. In my case, I have to drag/drop the keypad quite a bit lower than one would expect for it to dock correctly (below the screen, in my case).
But anyway, way, not that much we can do here, sorry. You'll have to try again until you get it to work :)

**Comment by tlongfellow** [comment]
adriweb, thank you for your timely response. I've sort of figured out some of the docking. I'll keep at it. I'm a bit surprised that the screen and the keypad are separate, but I suppose there are reasons.
Cheers!
> 
> Yeah, Qt can be a pain sometimes regarding to docking. It will eventually work, you have to find what position/area the mouse drop has to be on for it to work.
> In my case, I have to drag/drop the keypad quite a bit lower than one would expect for it to dock correctly (below the screen, for me).
> But anyway, not that much we can do here, sorry. You'll have to try again until you get it to work :)

**Comment by johann-petrak** [comment]
No luck here at all to do this.

**Comment by adriweb** [comment]
I replied on the other issue already but I'll just note that a rewrite is on-going GUI-wise, where another Qt lib will handle docking panes etc, that turns out to make things much better. In particular changing the layout is much easier.

**Comment by johann-petrak** [comment]
Thanks! Maybe the issue here is that I am running this on Linux (Ubuntu 18.04, Mate desktop manager)

Great program BTW, and great that it is available as deb package!

I do not know how complicated would be, but since most people probably want to stack the screen on top of the keypad, maybe add a menu function or button for doing this without drag+drop somewhere?
