### ISSUE TITLE
LCD DMA is not implemented

### ISSUE THREAD

**Issue by mateoconlechuga** [CE-Programming/CEmu#34]
This causes some games and programs that operate in higher bpp modes (even 16bpp v 8bpp) to run much too quickly.

**Comment by JaroslavN** [comment]
but if you put the rate on the lowest they are still too fast

**Comment by MateoConLechuga** [comment]
*bump* Any thoughts to the developers on how to implement this properly? Do we even know the timing ratio involved?

**Comment by MateoConLechuga** [comment]
Since it's been a while, has any more research been done on the amount of stolen states?

**Comment by adriweb** [comment]
I fear too many people are away during summer :P

**Comment by MattWaltz** [comment]
*Bump* Hey let's knock this out within the next week! :D

**Comment by AlvajoyAsante** [comment]
It will not turn when I try to.

**Comment by adriweb** [comment]
You should probably ask about this on a forum, this issue here has nothing to do with it.
