### ISSUE TITLE
Swipe Gesture Bug on Mac

### ISSUE THREAD

**Issue by PiRunner** [CE-Programming/CEmu#340]
(Thanks for reporting an issue! Please make sure to fill out the blanks below.)

What's wrong, and with what software version?
---------------------------------------------
**Operating System:** macOS Sierra 10.12.6
**CEmu version:** v1.3
**Describe your issue:**  
On a Mac, you can switch between full screen windows or between a full screen window and the desktop with either a 4-finger swipe gesture on the trackpad or Ctrl+[left or right arrow]. Because of its convenience, I use the trackpad gesture. When I'm programming, I often swipe between CEmu and another window. However, most of the times I do this, either a key on the emulator sticks, disabling all keys, and can only be fixed by reloading the rom, or CEmu crashes altogether. I'm guessing this has to do with the gesture because that's the only time this happens. As I add fingers to the trackpad to begin the gesture (this all happens in a fraction of a second), two fingers (scroll) then three (click and drag) are added before four fingers are on the trackpad, which may have to do with the issue. I've attached a crash log and a link to a video of the phenomenon.

What are the steps to reproduce this issue?
-------------------------------------------
1. Open the emulator on a Mac.
2. Swipe to another window.
3. The emulator will often either malfunction (keys sticking) or crash.

Any logs, error output, screenshot, other comments...?
------------------------------------------------------
[AppleCrashReport.txt](https://github.com/CE-Programming/CEmu/files/3884358/AppleCrashReport.txt)
Video: https://youtu.be/Hnoy66g0tj4

**Comment by adriweb** [comment]
Thanks for the nice report, I'll check it out tonight.

**Comment by adriweb** [comment]
Well, I can reproduce the fact that gestures tend to trigger unexpected "random" keypresses but so far I can't make it crash (I'm on latest master).
I'll try to see what events exactly it's getting, because that's rather unexpected and it looks like a Qt issue...

**Comment by adriweb** [comment]
Can't repro this issue anymore, on latest nightly build.
