### ISSUE TITLE
Feature request: F-key menu method

### ISSUE THREAD

**Issue by zbot473** [CE-Programming/CEmu#342]
Is it possible to get a built in call to produce popup f-key menus like this, rather than having to draw them?
![Menu item circled](https://user-images.githubusercontent.com/49821700/73090009-744dc080-3ea5-11ea-9d53-65f8c4de2bcd.png)

**Comment by jacobly0** [comment]
This has nothing to do with CEmu.

**Comment by adriweb** [comment]
(It's the OS that behaves that way)

**Comment by zbot473** [comment]
Sorry, meant to add this to the toolchain
