### ISSUE TITLE
CEmu custom key bindings (NOT a bug/issue)

### ISSUE THREAD

**Issue by KMisthebomb** [CE-Programming/CEmu#345]
I wanted to know how to create a custom keymap for CEmu but haven't quite been able to figure it out. Can someone help me please?

**Comment by adriweb** [comment]
Yeah we need to write documentation about that I guess. Probably here https://github.com/CE-Programming/CEmu/wiki/Keybindings
For now I believe you can export a keymap then modify the file and import it again. @mateoconlechuga may weigh in since he wrote that feature.

**Comment by KMisthebomb** [comment]
Ok, thanks so much! I figured out what key was which with trial and error (and Google), but I think a documentation for this would be a great idea!

**Comment by Mr-FuzzyPenguin** [comment]
Hi adriweb, I would like to know how to make the .ini file in order to make those keybinds happen. I am not sure where to look.

**Comment by adriweb** [comment]
You can export one, modify it, then import it.
