### ISSUE TITLE
Scale Screen

### ISSUE THREAD

**Issue by 9p4** [CE-Programming/CEmu#346]
Would it be possible to change the size of the display when emulating?

**Comment by adriweb** [comment]
The UI being completely customizable, yes.
Look at the setting for toggling the skin around the LCD, as well as the size.
You can also hide the window borders/titles in the menu by toggling "UI Edit mode"

**Comment by sambhavsaggi** [comment]
Currently, although it is possible to scale the display with the scale setting, I should have clarified that I was looking at dragging to resize the display should also exist

**Comment by adriweb** [comment]
Scaling has been improved (for the interpolations and in ratio-preserving fullscreen mode) but I suppose we aren't really planning on having free-hand resizing via the window size...
