### ISSUE TITLE
loading forever

### ISSUE THREAD

**Issue by Dmole** [CE-Programming/CEmu#353]
What's wrong, and with what software version?
---------------------------------------------
**Operating System:**
Windows 10.0.18362.836
**CEmu version:**
1.19.0d
**Describe your issue:**  
It is expected the game will launch, or an error should be shown.
Instead the window title said loading forever.

What are the steps to reproduce this issue?
-------------------------------------------
1. Launch CEmu
2. Launch Game

Any logs, error output, screenshot, other comments...?
------------------------------------------------------
Lite crash dump attached
[crash_20200516_1202247.dmp.zip](https://github.com/CE-Programming/CEmu/files/4639361/crash_20200516_1202247.dmp.zip)

**Comment by jacobly0** [comment]
This repo is for CEmu not Cemu.
