### ISSUE TITLE
CEmu opens, bounces around on the dock, then immediately crashes [MacOS]

### ISSUE THREAD

**Issue by acagliano** [CE-Programming/CEmu#356]
(Thanks for reporting an issue! Please make sure to fill out the blanks below.)

What's wrong, and with what software version?
---------------------------------------------
Mac OS X  10.14.6
1 commit behind head, on the USB CEmu fork. Can't tell you what version, doesn't stay running long enough.
I launch CEmu after a successful build. It bounces on the dock for a few seconds, then just closes. No crash message. No log output that I can see (not quite sure where this build logs to either)

**Comment by adriweb** [comment]
What does it say in the terminal when you launch the binary directly? That's by doing `~/PATH/TO/CEmu.app/Contents/MacOS/CEmu`

**Comment by acagliano** [comment]
```
qt.qpa.fonts: Populating font family aliases took 1072 ms. Replace uses of missing font family "MS Shell Dlg 2" with one that exists to avoid this cost. 
```
That's it.

**Comment by adriweb** [comment]
Huh. Well, assuming this is built in Release, can you build in Debug?
Also, I suppose I can try building it myself here and let you try.

**Comment by acagliano** [comment]
Also, here's the weirder part. I use the Homebrew package manager, so when I open Qt creator and try to run qmake from inside there, it will not let me build. However, when I run qmake from the command line, it builds. Then i do make. It works fine from Terminal.

**Comment by adriweb** [comment]
Looks like a semi-broken install? Well, or at least you haven't setup PATH to be pointing at your manual install of the Qt toolchain before brew's (I keep min in `~/Qt` for instance, and brew does its things in /usr/local)

**Comment by acagliano** [comment]
I did that. Now i've got `zlib development package not found`. Meanwhile:
`Homebrew: zlib 1.2.11 is already installed and up-to-date`

**Comment by adriweb** [comment]
Yeah, you probably have to launch Qt Creator from the terminal (`open ~/Qt/Qt\ Creator.app` for instance) since that's where the env vars are set up. - at least I do.
It's mentioned [in the wiki](https://github.com/CE-Programming/CEmu/wiki/Building-CEmu#build-issues-and-solutions) :D

**Comment by acagliano** [comment]
Ok this time it built successfully from within Qt Creator, and got:
`qt.qpa.fonts: Populating font family aliases took 1016 ms. Replace uses of missing font family "MS Shell Dlg 2" with one that exists to avoid this cost.`
I get this when it crashes.

**Comment by adriweb** [comment]
Are you able to launch the debugger? Either from Qt Creator or standalone from the terminal? It'd be nice to get a backtrace.
Also, is that on a Debug release or Release one? Or both?

Also, I have the same log message when I launch mine, it just doesn't crash though :P 
```
22:52:17 [:~/Documents/CEmu] master(+0/-0)+* ± gui/build-CEmu-Desktop_Qt_5_15_0_clang_64bit-Release/CEmu.app/Contents/MacOS/CEmu
qt.qpa.fonts: Populating font family aliases took 240 ms. Replace uses of missing font family "MS Shell Dlg 2" with one that exists to avoid this cost.
```

One more thing, maybe you can try deleting all your CEmu config/state/pref files? But preferably try to debug it first so we can repro and fix the issue.

**Comment by acagliano** [comment]
When I try to 'start debugging of startup project`, I get the following popup in a terminal window:
```
AnthonysMBP805:~ acagliano$ /var/folders/42/_svlrpqn64j8557ny5s3phmc0000gn/T/tmpmQwewS ; exit;
Cannot connect creator comm socket /private/var/folders/42/_svlrpqn64j8557ny5s3phmc0000gn/T/QtCreator.ZPMLGQ/stub-socket: No such file or directory
Press <RETURN> to close this window...
```

**Comment by adriweb** [comment]
Well hmm, I believe you can turn off running/debugging inside a terminal in the Project settings, here https://i.imgur.com/44zwQMU.png, uncheck the box

**Comment by acagliano** [comment]
I'm also getting this:
```
Project ERROR: You need to set the ANDROID_NDK_ROOT environment variable to point to your Android NDK.
Could not read qmake configuration file /Users/acagliano/Qt/5.15.0/android/mkspecs/android-clang/qmake.conf.
```

**Comment by adriweb** [comment]
Yeah hm no idea about non-computer builds, as you can see it can already be hard enough to get a backtrace :P
For desktop, make sure to remove/deselect other targets

**Comment by acagliano** [comment]
Where are other targets even listed? I see build configurations, but I only see CEmu. I also don't even know why it's trying to build the android_NDK when im on osx.

**Comment by adriweb** [comment]
Right-click on one of the "Build&Run" config things in the project settings, then click on Disable: https://i.imgur.com/vZc8C94.png

**Comment by acagliano** [comment]
ok, got something new now
```
01:19:00: Starting /Users/acagliano/CEmu/gui/qt/CEmu.app/Contents/MacOS/CEmu ...
qt.qpa.fonts: Populating font family aliases took 977 ms. Replace uses of missing font family "MS Shell Dlg 2" with one that exists to avoid this cost. 
01:19:02: /Users/acagliano/CEmu/gui/qt/CEmu.app/Contents/MacOS/CEmu exited with code 0
```

**Comment by adriweb** [comment]
Well, that's unfortunately not helpful :(

Can you try deleting your CEmu config files? For me it's `/Users/YOURNAMEHERE/Library/Preferences/cemu-dev` and `/Users/YOURNAMEHERE/Library/Preferences/com.adriweb.CEmu.plist`

**Comment by acagliano** [comment]
Ok that worked. So what happened, older config files borking the launch?
Also, would that happen any time you try to upgrade to a version that might not use the same file formats or something?
Could you guys perhaps include versioned config saving? Something akin to:
`~/Library/Preferences/cemu-dev/<version#>/`

**Comment by adriweb** [comment]
Well, we precisely try to make things as compatible as possible, and it's already versioned internally when something "cannot" be made compatible.
But it may not have been the case for feature branches etc.
