### ISSUE TITLE
CEmu TI-nspire CX (CAS)

### ISSUE THREAD

**Issue by JaroslavN** [CE-Programming/CEmu#36]
I thought it would be a lot of work for y'all to shoose the keypad settings, or buttons...
So ,here you go ;)
![nspire cemu](https://cloud.githubusercontent.com/assets/16990273/13355324/0f1d6dca-dca0-11e5-8842-40d82db1d32c.png)

**Comment by MateoConLechuga** [comment]
Great work :) Once nSpire support becomes higher priority, this will definitely be useful. For now, I'm going to close this issue since it isn't really an issue, just a comment :P
