### ISSUE TITLE
Can't get ROM file

### ISSUE THREAD

**Issue by JLP04** [CE-Programming/CEmu#361]
(Thanks for reporting an issue! Please make sure to fill out the blanks below.)

What's wrong, and with what software version?
---------------------------------------------
**Operating System:** …  MacOS Catalina 10.15.6
**CEmu version:** … (see in the `About CEmu` menu)  1.3
**Describe your issue:**  
… (including, if applicable what you expect vs. what happens)  

I updated my calculator to OS 5.6 which prevents you from running assembly programs so I am unable to get a ROM file to use with the app. 

What are the steps to reproduce this issue?
-------------------------------------------
1. … Update your physical calculator to OS 5.6
2. … Load the Assembly Program to get the ROM file onto your calculator using ti Connect CE 5.6
3. … Try to run the assembly program as the app instructs

Any logs, error output, screenshot, other comments...?
------------------------------------------------------
…

**Comment by Jeffitus** [comment]
Not a CEmu bug. I guess a warning could be added somewhere, but an assembly program is required to dump the ROM.

**Comment by JLP04** [comment]
I figured I'd ask if anyone knew another way to get the ROM file that works in 5.6.

**Comment by jacobly0** [comment]
You can use the unreleased [usb branch](https://github.com/CE-Programming/CEmu/tree/usb) to transfer an OS to an existing ROM.

**Comment by JLP04** [comment]
I don't have an existing ROM to do it from.

**Comment by adriweb** [comment]
Then you'll have to wait for a jailbreak to be released in order to execute ASM programs again.

**Comment by commandblockguy** [comment]
You may want to take a look at arTIfiCE: https://yvantt.github.io/arTIfiCE/

**Comment by adriweb** [comment]
Indeed. Closing for now.
