### ISSUE TITLE
How do I install an app onto the emulator

### ISSUE THREAD

**Issue by JLP04** [CE-Programming/CEmu#365]
(Thanks for reporting an issue! Please make sure to fill out the blanks below.)

What's wrong, and with what software version?
---------------------------------------------
**Operating System:** …  macOS 10.15.6

**CEmu version:** …  1.3

**Describe your issue:**  
When I open the file for an app, it doesn't show up in the apps menu on the calculator. 

What are the steps to reproduce this issue?
-------------------------------------------
1. …Open an app file (for example the file for the transform app)
2. …Go to apps menu on calculator

**Comment by adriweb** [comment]
For now, the latest release doesn't support that. The next version emulated USB transfers and as such allows Apps and OSes to be transferred to the emulated calculator.
I could build a beta version for macOS "soon" if needed...

**Comment by MorissetteThomasV** [comment]
Hi @adriweb , 
You said 

> you can install apps on your real CE calculator and dump the ROM again.

but if I try to include a .8ek to the ROM, it fails. And if I use only the ROMData files, the ROM does not include the app that I want.
Did I misunderstand something ?
Thank you !

**Comment by Jeffitus** [comment]
In order for the app to be part of the ROM, it has to be installed on your calculator when you dump the ROM. If you do the ROM dumping process while the app is on your calculator, the resulting ROM image should have the app in it.

**Comment by JLP04** [comment]
Mine also didn't have the app even though the app was installed when I dumped the ROM

**Comment by adriweb** [comment]
Hmm, maybe I got confused as to what the CEmu dumper does, then.
Anyway, either get yourself the latest master build (in which real USB transfers got merged recently), or use TILP for dumping the ROM, which does a real full dump.
