### ISSUE TITLE
All versions of cemu from repositories immediately segfault on Arch

### ISSUE THREAD

**Issue by cdknight** [CE-Programming/CEmu#366]
What's wrong, and with what software version?
---------------------------------------------
**Operating System:** Arch Linux
**CEmu version:** 1.3.0 and git version from AUR
**Describe your issue:**  

As soon as I start the program, it segfaults and fails to run.

What are the steps to reproduce this issue?
-------------------------------------------
1. Install CEmu from the AUR (`cemu`, `cemu-git`) or from the officially-provided OBS repository
2. Run `cemu` in the terminal
3. Crashes immediately

Any logs, error output, screenshot, other comments...?
------------------------------------------------------
`segmentation fault (core dumped)  cemu`

**Comment by adriweb** [comment]
Can you check if it would be the same reason as https://github.com/CE-Programming/CEmu/issues/360 ?

**Comment by TheMachine02** [comment]
I can confirm it is the same reason as #360. Arch package qt5-base version 5.15.1-1 segfault immediately, 5.15.0-5 also does it, but reverting to package 5.15.0-4 seems to correct the issue. Most likely a issue from upstream.

**Comment by cdknight** [comment]
I cannot downgrade my qt5-base but I can confirm the crash is happening for the same reason as #360.

**Comment by Vogtinator** [comment]
If Arch recently updated to binutils 2.35, this might be a manifestation of https://bugreports.qt.io/browse/QTBUG-86173. As a workaround, use `CONFIG += ltcg` instead of `-flto` in the `.pro` file to ensure that `-fPIC` is passed to the linking command as well.

**Comment by TheMachine02** [comment]
binutils 2.35 was updated the 9 august on arch and rebuild against 5.8 header not so long ago.
I can confirm that adding `CONFIG += ltcg` fix the issue. Thanks.

**Comment by adriweb** [comment]
Thanks :)
Should we just add that to the .pro file globally and see how it goes?

**Comment by adriweb** [comment]
Nobody said not to add it, so that's done now 🤷‍♂️
