### ISSUE TITLE
Emulator refuses to work after sending files

### ISSUE THREAD

**Issue by BioHazard1282** [CE-Programming/CEmu#367]
(Thanks for reporting an issue! Please make sure to fill out the blanks below.)

What's wrong, and with what software version?
---------------------------------------------
**Operating System:** macOS Mojave 10.14.6
**CEmu version:** 1.3 (see in the `About CEmu` menu)  
**Describe your issue:**  
I am trying to send 11 files for testing, but after I send them the keyboard refuses to respond. I've reset the calculator (which works up to a point), reloaded some different ROMS, but the same exact result every time.  

What are the steps to reproduce this issue?
-------------------------------------------
1. Send 11 of the specific files
2. Try to use the keyboard on the screen

Any logs, error output, screenshot, other comments...?
------------------------------------------------------
My one comment is, don't download for macOS. Use Windows or Linux instead.

**Comment by acagliano** [comment]
CEmu for Mac is on v2+, last I checked. Try it with the latest version.

**Comment by BioHazard1282** [comment]
> CEmu for Mac is on v2+, last I checked. Try it with the latest version.

Oh, so 1.3 isn't the latest? Where can I get v2?

**Comment by adriweb** [comment]
Well this doesn't look macOS specific, though... or if it is, it's either PEBCAK or a Qt issue.

Anyway, transfers on the master branch (and consequently upcoming releases) use USB, so this issue is moot.

@acagliano: nah, latest release is 1.3.

Conclusion: try on latest master (build it yourself for now though, we don't have macOS automated builds) and report back if you're still having issues with that.

**Comment by BioHazard1282** [comment]
I can try it. I'll see what I can do

**Comment by adriweb** [comment]
(closing this but feel free to reply)

**Comment by acagliano** [comment]
> @acagliano: nah, latest release is 1.3.
Then why does mine say 2.0? Is that due to the fact that I'm on the usb-branch?

**Comment by adriweb** [comment]
Yes, dev builds are 2.0.

Note that usb got merged in master now.

**Comment by acagliano** [comment]
Does it support SRLDRVCE/USBDRVCE?
Natively? Or via the edit command made where it uses pipe files to act as a usb?

**Comment by adriweb** [comment]
No, that would be usb-host.

The current master allows you to send OSes, apps, from the computer to the emulated calc without the "hacks" like memory injection that were used before.

**Comment by C3productions** [comment]
Where can I get this build for this? I'd like to send apps and OSs to my CEmu.

**Comment by adriweb** [comment]
For instance on https://jacobly.com/CEmu/master/latest/CEmu64.exe, for Windows, which was updated today.

**Comment by C3productions** [comment]
I don't like Windows very much. I use Macintosh instead. Is there a mac version for this?

**Comment by adriweb** [comment]
Well, for macOS I make the builds myself (and codesign+notarize them since I have a developer account), I just made one:

(I had to zip the .dmg because github doesn't want the dmg directly 🤦)

[CEmu_macOS.dmg.zip](https://github.com/CE-Programming/CEmu/files/5270198/CEmu_macOS.dmg.zip)
