### ISSUE TITLE
Search in RAM fails

### ISSUE THREAD

**Issue by PeterTillema** [CE-Programming/CEmu#37]
When I try to search in the RAM in the Memory console for a program name, it fails and I get the error: 
Runtime Error!

Program: C:\...............

This application has requested  the Runtime to terminate it in an unusual way. Please contact the application's support team for more information.

[http://i.imgur.com/rKKTEaK.png](url)

I ran it under Windows 10

**Comment by MateoConLechuga** [comment]
The search is not for strings, it is for hexadecimal string numbers. I'll fix that runtime error though.
