### ISSUE TITLE
Instant crashes on Win10 Home Edition

### ISSUE THREAD

**Issue by TimmyTurner51** [CE-Programming/CEmu#370]
(Thanks for reporting an issue! Please make sure to fill out the blanks below.)

What's wrong, and with what software version?
---------------------------------------------
**Operating System:** Windows 10 (Home)
**CEmu version:** CEmu v1.3 (stable), also crashed on developmental build
**Describe your issue:**  
The issue is an instant crash when opening CEmu. Not sure as to why. It happened in both stable and developmental builds.

What are the steps to reproduce this issue?
-------------------------------------------
1. Get the attached zip, and extract it.
2. Put the extracted folder in %appdata% > Local (NOT roaming).
3. CEmu should crash. If it doesn't, this issue isn't getting anywhere...

Any logs, error output, screenshot, other comments...?
[CEmu.zip](https://github.com/CE-Programming/CEmu/files/5482953/CEmu.zip)

------------------------------------------------------
…

**Comment by alberthdev** [comment]
What kind of error do you get when it crashes? Also, are you able to follow [these steps](https://helgeklein.com/blog/2018/10/creating-an-application-crash-dump/) and send the file that is outputted as a result?

**Comment by TimmyTurner51** [comment]
No I never did try those steps, but it didn't give any errors. It just crashed. CEmu works now.
