### ISSUE TITLE
Warning when dragging screen to browser/file manager/picture viewer...

### ISSUE THREAD

**Issue by PrivacyDragon** [CE-Programming/CEmu#371]
What's wrong, and with what software version?
---------------------------------------------
**Operating System:** Linux, OpenSuse Leap 15.1 
**CEmu version:** 1.3  
**Issue:**  
When I drag the screen into my browser, file manager or picture viewer, I get a big warning in the terminal.
It's like three lines of six times "WARNING!!!"
The browser I use is: Firefox
The file manager I use is: Dolphin
The picture viewer I use is: Gwenview

What are the steps to reproduce this issue?
-------------------------------------------
1. Open CEmu (Of course...)
2. Open a Browser or filemanager or picture viewer.
3. Go back to CEmu.
4. Drag the screen.
5. Open it on a new browser tabblad, copy it to somewhere via the file manager or drop it in the picture viewer.
6. Look in the terminal and you'll see a warning.

Any logs, error output, screenshot, other comments...?
------------------------------------------------------
![Screenshot](https://pic.infini.fr/aRtmzcBK/mZrP4wmr)

**Comment by adriweb** [comment]
Maybe @Vogtinator can help with that one?

**Comment by Vogtinator** [comment]
That's from here: https://github.com/qt/qtimageformats/blob/024527e1fa36fbe5f25e0e438d43d11cd15d68de/src/plugins/imageformats/jp2/qjp2handler.cpp#L860

So something tries to write a JPEG2000 file?

**Comment by adriweb** [comment]
Not as far as I know, hmmm.
CEmu captures are either standard PNG (https://github.com/CE-Programming/CEmu/blob/8e31441310ea16d4eb90b2b2cd31bc4ca47115d3/gui/qt/lcdwidget.cpp#L105 wher we use Qt stuff), or animated PNGs (in which case, we use libpng-apng anyway)

**Comment by Vogtinator** [comment]
I guess the format negotiation for the drag and drop somehow results with image/jpeg2000 getting selected. In Leap 15.2 and up, the jpeg2000 support was dropped from libqt5-qtimageformats, so I can't reproduce it here.

**Comment by adriweb** [comment]
Interesting, I guess we can force PNG and see how it goes.

**Comment by PrivacyDragon** [comment]
Well, OpenSuse Leap 15.1 won't be supported in a certain amount of time or something like that (According to my father), so I have to update to Leap 15.2 somewhere in the next months... (well, my father will do that, but that doesn't really matter)

**Comment by Vogtinator** [comment]
Getting a backtrace at the `jas_stream_memopen` call should show why exactly it's being called.

**Comment by adriweb** [comment]
May have been fixed along the years.
Also https://github.com/CE-Programming/CEmu/commit/1ce65e8b2b25e3b18804914d367f76586bf3c42c may help too...

To re-open if needed.
