### ISSUE TITLE
There isn't any tabs.

### ISSUE THREAD

**Issue by 143396** [CE-Programming/CEmu#372]
(Thanks for reporting an issue! Please make sure to fill out the blanks below.)

What's wrong, and with what software version?
---------------------------------------------
Operating System: Windows 10 64 bit
CEmu version: 1.3
Describe your issue:  There isn't any tabs.

What are the steps to reproduce this issue?
-------------------------------------------
1. Open Cemu

Any logs, error output, screenshot, other comments...?
------------------------------------------------------
What I expect:
<img width="319" alt="66102069-eb152580-e565-11e9-9bd9-986272ba8d74 (2)" src="https://user-images.githubusercontent.com/64433746/101189371-33b9ea00-3614-11eb-8a27-934645a9ad86.png">
What I have:
![CemuScreenshot](https://user-images.githubusercontent.com/64433746/101189423-446a6000-3614-11eb-9b09-26c660e7ec6c.PNG)

**Comment by mateoconlechuga** [comment]
You have hidden the menubar. Right click on the screen and go to `Extras > Hide Menubar` and uncheck that option.
