### ISSUE TITLE
CEmu take exceedingly long accessing filesystem

### ISSUE THREAD

**Issue by BioHazard1282** [CE-Programming/CEmu#373]
(Thanks for reporting an issue! Please make sure to fill out the blanks below.)

What's wrong, and with what software version?
---------------------------------------------
**Operating System:** Ubuntu MATE 20.04 Focal Fossa | Raspberry Pi 3B
**CEmu version:** 1.3
**Describe your issue:**  CEmu takes 10+ minutes trying to access the filesystem.

What are the steps to reproduce this issue?
-------------------------------------------
1. Install CEmu via the binary package (.deb)
2. Place the ROM on the Desktop and make a desktop launcher/shortcut to CEmu
3. Open it, select the ROM, and wait for it to load.
4. Try to access a folder by selecting File > Open...
5. Wait for 10+ minutes while it tries to open the folder

Any logs, error output, screenshot, other comments...?
------------------------------------------------------
I have verified no other processes are running. I only have my flash drive plugged in. I've rebooted and reinstalled the package but the same results every time. It also makes the emulator unresponsive if you cancel the file selection.

**Comment by adriweb** [comment]
Seems like an external issue, but please try the latest release and re-open the issue if necessary.
