### ISSUE TITLE
CEmu broken after update

### ISSUE THREAD

**Issue by BioHazard1282** [CE-Programming/CEmu#375]
(Thanks for reporting an issue! Please make sure to fill out the blanks below.)

What's wrong, and with what software version?
---------------------------------------------
**Operating System:** Ubuntu MATE 20.04 Focal Fossa
**CEmu version:** 1.3 (Doesn't show Git) 
**Describe your issue:**  
CEmu always becomes unresponsive after the update I installed. I installed directly through the .deb package and yesterday it said it had an update (with `sudo apt update`). I updated and every time I try to execute it always it unresponsive.

I've purged all files from it and reinstalled it 3 times, but no luck. I've waited for hours for it to open, but it fails. I have enough RAM and storage left, but I get this result every time.

What are the steps to reproduce this issue?
-------------------------------------------
1. Install it via binary (.deb)
2. Use it for a while
3. Update in Terminal with `sudo apt update`
4. Install the update and try to execute.

Any logs, error output, screenshot, other comments...?
------------------------------------------------------
![Screen Shot 2020-12-10 at 03 54 05 PM](https://user-images.githubusercontent.com/44819642/101839838-4fcff680-3b00-11eb-8d96-3debfd9e4bb6.png)

**Comment by adriweb** [comment]
What's weird is that I only enabled more versions in the build server, so anything already existing shouldn't have changed, for instance the Ubuntu 20.04 build...
Are you able to try to build the latest master?

**Comment by BioHazard1282** [comment]
> What's weird is that I only enabled more versions in the build server, so anything already existing shouldn't have changed, for instance the Ubuntu 20.04 build... Are you able to try to build the latest master?

How do I do that? Do I use `dpkg-build --build <folder_name>`

**Comment by adriweb** [comment]
Well following this rather: https://github.com/CE-Programming/CEmu/wiki/Building-CEmu

**Comment by adriweb** [comment]
It would still be good to understand what's going on with the package though :/

**Comment by BioHazard1282** [comment]
> It would still be good to understand what's going on with the package though :/

I purged everything again and built and installed it, and it seems to work fine now. Thanks! 💯

**Comment by adriweb** [comment]
Built from the repo on master?
What does the version number say in About?

**Comment by BioHazard1282** [comment]
Yes. The version says 1.3, but the Git is still null




*----------------------------------------------*
*Arbiter (BioHazard)*
*Senior at Cedar Valley High School*
*Computer and Calculator programmer*

*biohazard1282@gmail.com <biohazard1282@gmail.com>*

*dahlty000@alpinesd.org <dahlty000@alpinesd.org>*
*c3-productions.github.io <http://c3-productions.github.io/>*

**Comment by adriweb** [comment]
Well master is definitely not 1.3 anymore so I guess somehow you just got the version from the release. Anyway, if it works, at least, that's good
