### ISSUE TITLE
"Pause emulation" setting prevents CEmu from closing.

### ISSUE THREAD

**Issue by KryptonicDragon** [CE-Programming/CEmu#378]
(Thanks for reporting an issue! Please make sure to fill out the blanks below.)

What's wrong, and with what software version?
---------------------------------------------
**Operating System:** Windows 10 x64 v20H2
**CEmu version:** v2.0dev (git: g1d7d78)
If the "Pause emulation on focus change" setting (in the "Settings" pane) is enabled, CEmu will not immediately close when told to, if it isn't in focus. Once it regains focus, it will "realize" it was supposed to close and then close as expected.

Methods of telling the window to close without focusing it include:
-middle clicking it in the alt+tab menu
-pressing "del" on it in the alt+tab menu
-clicking the X in the top right of the window in the alt+tab menu
-shutting down, restarting, or logging off Windows (which is particularly annoying because windows will say that the program is preventing windows from shutting down/restarting/logging off, and once you click on "cancel" to go take a look, it puts CEmu in focus and it immediately closes, as if to tease you)

**Comment by adriweb** [comment]
Solved.
