### ISSUE TITLE
CEmu can open outside monitor boundaries.

### ISSUE THREAD

**Issue by TheLastMillennial** [CE-Programming/CEmu#379]
What's wrong, and with what software version?
---------------------------------------------
**Operating System:** Windows 10 Home
**CEmu version:** CEmu v2.0dev (git: d0a8e2c)
**Describe your issue:** Sometimes CEmu will open outside the boundaries of the monitor so it's impossible to see the application or even move it inside the monitor.

What are the steps to reproduce this issue?
-------------------------------------------
1. Open CEmu
2. Move it to an external monitor (snapping it to the left or right side reproduces issue most reliably) 
3. Close CEmu
4. Disconnect the external monitor
5. Open CEmu. It will try to open where the external monitor use to be, however since it's not plugged in, you cannot see or interact with CEmu.

Any logs, error output, screenshot, other comments...?
------------------------------------------------------
Closing CEmu, reconnecting the external monitor, and opening CEmu again is the only reliable solution I've found.

**Comment by DJOmnimaga** [comment]
This happened to me as well, even though I only have one monitor. Restarting CEmu, re-installing and attempting moving the window around with the keyboard will not fix it so I can no longer use CEmu at all.

**Comment by adriweb** [comment]
Does it still happen if you delete the config files?

**Comment by adriweb** [comment]
Might be helpful for us, idk: https://stackoverflow.com/a/48742231

**Comment by DJOmnimaga** [comment]
I cannot find the config files.

**Comment by adriweb** [comment]
Aren't they somewhere in %APPDATA% on Windows?

**Comment by DJOmnimaga** [comment]
Oh I actually found them in AppData/Local now, but deleting them doesn't fix my problem.

**Comment by adriweb** [comment]
Can't repro this anymore (latest nightly build, Win11).

Feel free to re-open if needed.
