### ISSUE TITLE
Sending files doesn't work.

### ISSUE THREAD

**Issue by xLumi** [CE-Programming/CEmu#381]
(Thanks for reporting an issue! Please make sure to fill out the blanks below.)

What's wrong, and with what software version?
---------------------------------------------
**Operating System:** …  Windows 10
**CEmu version:** … CEmu v1.3 (git: 87c3b43)
**Describe your issue:**  
… File transfers don't actually transfer files. I'm trying to use the emulator over an actual physical calculator because I find it easier to work with, but I can't get the games, apps and other things to actually install onto the emulated calculator (ex. the 5.6 OS and Apps bundle)

What are the steps to reproduce this issue?
-------------------------------------------
1. … literally try to send anything to the calculator.
2. …
3. …

Any logs, error output, screenshot, other comments...?
------------------------------------------------------
… It doesn't say it errored.

**Comment by adriweb** [comment]
You can't transfer APPS or OSes in the released CEmu. It may work for the development release for v2.0, although it's not stable yet, and is undergoing a rewrite anyway.

Programs (8xp) and Appvars (8xv) should send just fine though.
