### ISSUE TITLE
Cant send calculator OS files and app files

### ISSUE THREAD

**Issue by Collin8000** [CE-Programming/CEmu#385]
(Thanks for reporting an issue! Please make sure to fill out the blanks below.)

Qt5 5.12.8
**Ubuntu 20.04:** …  
**V2 Dev:** … (see in the `About CEmu` menu)  
**Dont know how to send OS files and app files to calculator:**

**Comment by jacobly0** [comment]
Assuming you have a recent enough version you can open OS and app files from the file menu, the variables dock, or you can drag and drop them onto the calculator screen.

**Comment by adriweb** [comment]
Version more recent than the latest release, that is.
You can build the latest master, it should be fine, although you may want to revert c9c7d12796b1091eaaa503865f1700ddf9285a46
