### ISSUE TITLE
CEmu (SDL2 version) crashes with "Segmentation fault:11" when I use the --keypad smartpad argument

### ISSUE THREAD

**Issue by TIny-Hacker** [CE-Programming/CEmu#390]
What's wrong, and with what software version?
---------------------------------------------
**Operating System:** MacOS 10.11.6 El Capitan
**CEmu version:** CEmu SDL2 version (I just cloned the repo)
**Describe your issue:**  
I've been interested in controlling CEmu with my TI-84 Plus CE, and since that isn't available in the qt version I tried the sdl version. I have used it (sdl version with smartpad) on Ubuntu before with no errors. When I run the program without the `--keymap smartpad` argument, it works fine, but when I try to run it with the `--keymap smartpad` argument, I get this:
```
rom: /Users/owen/Desktop/calc_misc/my84cerom.rom
Segmentation fault: 11
```

What are the steps to reproduce this issue?
-------------------------------------------
1. Install libsdl2 by building from source, then run `make` on both the core and sdl folders in the CEmu folder.
2. Run `/path/to/cemu-sdl -r /path/to.rom --keypad smartpad`

Any logs, error output, screenshot, other comments...?
------------------------------------------------------
Here's the debug generated in lldb:
```
* thread #1: tid = 0x5eb1, 0x00007fff97b27365 libsystem_platform.dylib`_platform_strncmp + 325, queue = 'com.apple.main-thread', stop reason = EXC_BAD_ACCESS (code=1, address=0xaaa00000004)
  * frame #0: 0x00007fff97b27365 libsystem_platform.dylib`_platform_strncmp + 325
    frame #1: 0x00007fff87b6c1f6 libsystem_c.dylib`parse_long_options + 239
    frame #2: 0x00007fff87b6bf92 libsystem_c.dylib`getopt_internal + 1208
    frame #3: 0x0000000100001000 cemu-sdl`main + 176
    frame #4: 0x00007fff961a85ad libdyld.dylib`start + 1
    frame #5: 0x00007fff961a85ad libdyld.dylib`start + 1
```

**Comment by jacobly0** [comment]
Already fixed with e0a592f238ebb6e6f32586d9341c62e14d79354c.
