### ISSUE TITLE
Toolbar and Windows don't display

### ISSUE THREAD

**Issue by Pinefoxo** [CE-Programming/CEmu#391]
I was using TEmu and accidentally clicked on an option that hid the toolbar. However, to access that option again requires the toolbar. So, I'm now stuck and can't do anything with the program because I can't display windows or change settings. I've looked online and can't find any keyboard shortcuts that would allow me to display the toolbar. I also tried deleting the program or moving it to a different folder, but the issue persists. I tried looking in my appdata files to see if I can reset anything there for this program, but I didn't find anything. Please help! Thanks.

**Comment by jacobly0** [comment]
Right click on the calculator screen, `Extras`, uncheck `Hide menu bar`.
