### ISSUE TITLE
Sending .8ek Files not Working?

### ISSUE THREAD

**Issue by JWBstuhr** [CE-Programming/CEmu#392]
(Thanks for reporting an issue! Please make sure to fill out the blanks below.)

What's wrong, and with what software version?
---------------------------------------------
**Operating System:** MacOS
**CEmu version:** CEmu v1.3 (git: 87c3b43)
**Describe your issue:**  
Sending the files does nothing, they don't appear in the memory at all. The console also seems to report nothing?

What are the steps to reproduce this issue?
-------------------------------------------
1. Send files, any 8ek- specifically for me, the standard apps like Inequalz
2. Nothing happens?

**Comment by adriweb** [comment]
This is normal for the released version, it's only supported on the development builds for now. (#362).
You can try downloading a recent mac build, for instance from here: https://github.com/CE-Programming/CEmu/issues/341#issuecomment-811477894

**Comment by JWBstuhr** [comment]
I don't know if I should make a new issue for this or not, but something isn't working for me with that build.
![Screen Shot 2021-04-21 at 2 26 35 PM](https://user-images.githubusercontent.com/77174240/115609867-b4207500-a2ad-11eb-9815-27a3921ab2e8.png)
![Screen Shot 2021-04-21 at 2 28 44 PM](https://user-images.githubusercontent.com/77174240/115610047-f47ff300-a2ad-11eb-978f-3fe01548c499.png)

**Comment by adriweb** [comment]
Hmm, interesting. I guess I'll have to fix that somehow with `install_name_tool` magic...

In the meantime, you can try to install some libs (whichever it's complaining about) with [brew](https://brew.sh/): for instance for liblzma.5.dylib, you'd do `brew install xz`

Also, which macOS version do you have?

**Comment by JWBstuhr** [comment]
MacOS Catalina 10.15.7 (19H524)

Also, I unfortunately can't try installing the libs like that, as I don't have permission to run anything in terminal.

**Comment by JWBstuhr** [comment]
There's a bit in the error that says
`Reason: unsafe use of relative rpath */liblzma.5.dylib in /Users/USER/Downloads/CEmu App.app/Contents/MacOS/../Frameworks/libarchive.13.dylib with restricted binary`

**Comment by adriweb** [comment]
Yes I know, that's what I have to manually fix, apparently. Should be doable.

**Comment by adriweb** [comment]
See follow up on #393
