### ISSUE TITLE
After changing settings, sometimes the arrow keybindings stop working until next emulator restart

### ISSUE THREAD

**Issue by DJOmnimaga** [CE-Programming/CEmu#395]
What's wrong, and with what software version?
---------------------------------------------
**Operating System:** …  Windows 10 Pro
**CEmu version:** v1.3
**Describe your issue:**  
… After changing emulator settings, sometimes the arrows on the emulator keypad stops accepting arrow keypresses from the computer keyboard. To fix the issue the emulator has to be restarted.

What are the steps to reproduce this issue?
-------------------------------------------
1. …Change emulator settings that can be changed using arrows (such as emulation speed, screen zoom and frame skip). This also happens with settings that do not require arrow keypresses, but far less often.
2. …Go back to the keypad view in CEmu and try to press arrows on the computer keyboard. Clicking the keypad buttons on the emulator will not fix it.

**Comment by jacobly0** [comment]
If you focus a ui element than the arrow keys are going to control that element.  If you want the arrow keys to control the emulated calculator again, you can simply click on the calculator screen to focus the emulator again.
