### ISSUE TITLE
[Feature Request] Add support for different hardware revisions.

### ISSUE THREAD

**Issue by RoccoLoxPrograms** [CE-Programming/CEmu#396]
I realize that this is a big ask, but it would be really nice if CEmu could be set to emulate at least pre-rev M hardware and rev M+ hardware. 
Going along with that, it would be nice if CEmu could be set to emulate the different screens in the calculators. (The newer calcs, around rev I+, have a different screen that displays colors differently. Yes... this is true and has been tested.)

**Comment by adriweb** [comment]
CEmu can already do I+ as in "no more IM2", but for LCD differences, see maybe #358.

For rev M, it's another story and existing developments should probably be split from python-related things, but it's in the feature/python branch, see https://github.com/CE-Programming/CEmu/issues/321#issuecomment-518088015

**Comment by adriweb** [comment]
Available on master as of a few weeks/months ago!
