### ISSUE TITLE
CEmu resets RAM continually in v: 1.3

### ISSUE THREAD

**Issue by randomguy70** [CE-Programming/CEmu#399]
When using CEmu version 1.3 on my mid 2012 MacBook air, it worked fine until today, when it suddenly started continually resetting the RAM in a loop after I quit a C program that I was developing (the program did not have any issues exiting or starting before or after). I restored the state that I had saved yesterday, but when I quit the program, it again went into the RAM-resetting loop. I reloaded the ROM and CEmu was fine. I am not sure what caused it, but it might happen again. Thank you!

**Comment by jacobly0** [comment]
It's a bug in your program, there's nothing the CEmu devs can do for you.
