### ISSUE TITLE
Flash self-test causes emulation to reset

### ISSUE THREAD

**Issue by MateoConLechuga** [CE-Programming/CEmu#40]
Who broke it? :)

**Comment by adriweb** [comment]
Works fine for me, actually.
I get the `FLASH PASS` message and the protection matrix correctly.

**Comment by MateoConLechuga** [comment]
Doesn't for me :( That makes me sad.

**Comment by MateoConLechuga** [comment]
I'm crazy because I changed the flash of my testing rom manually for some odd reason. This works fine. :)
