### ISSUE TITLE
Can't run the ROM dumper program

### ISSUE THREAD

**Issue by lafkpages** [CE-Programming/CEmu#400]
What's wrong, and with what software version?
---------------------------------------------
**Operating System:** macOS 11.2
**CEmu version:** v.1.3 (see in the `About CEmu` menu)  
**Describe your issue:**  
I can't find the `Asm(` key on my calculator or in the catalog (`2nd` + `0`), so I can't run the program. I've tried running it without the `Asm(` but it gives me the following error.

![image](https://user-images.githubusercontent.com/62298468/125647365-73978dfc-a19f-44e9-b631-3fa6d60457cb.png)

What are the steps to reproduce this issue?
-------------------------------------------
1. Open CEmu
2. Save the ROM dumper program
3. Put it on the calculator via TI Connect CE

Any logs, error output, screenshot, other comments...?
------------------------------------------------------
I think they removed ASM in OS version 5.5.5.

**Comment by adriweb** [comment]
Yes, you'll have to use https://yvantt.github.io/arTIfiCE/ then install [AsmHook](https://github.com/jacobly0/asmhook/releases/latest) (launch it once then quit) from the artifice shell.
After that, the dumper should work fine.

**Comment by lafkpages** [comment]
Oh, thanks. What do I chose when it asks me `Garbage Collect? No/Yes`?

**Comment by lafkpages** [comment]
It tells me I have no memory. How much does it need?

**Comment by adriweb** [comment]
Just in case, delete from memory any useless things you don't need, then archive the rest. There shouldn't really be anything in RAM unless you're editing them.
