### ISSUE TITLE
CEmu 2.0dev crashes on M1

### ISSUE THREAD

**Issue by LogicalJoe** [CE-Programming/CEmu#401]
**Operating System:** MacOS Big Sur 11.4 (M1)
**CEmu version:** CEmu v2.0dev (git: dcb3c27)
**Describe your issue:**  The dev version in https://github.com/CE-Programming/CEmu/issues/393#issuecomment-826395031 crashes on M1 and works fine on native X86.

[Problem Report.txt](https://github.com/CE-Programming/CEmu/files/6826938/Problem.Report.txt)

**Comment by LogicalJoe** [comment]
For whatever reason rebooting the computer fixed it or cleared whatever Rosetta had cached.  I can't seem to reproduce this issue now.

**Comment by adriweb** [comment]
Ok we'll reopen if needed.
