### ISSUE TITLE
Binary download error

### ISSUE THREAD

**Issue by BlazerYoo** [CE-Programming/CEmu#404]
What's wrong, and with what software version?
---------------------------------------------
**Operating System:** Win10
**CEmu version:** Latest release on [download](https://ce-programming.github.io/CEmu/download) page
**Describe your issue:**  
Expected a binary download. Received `Failed to detect the latest folder. (Current path: /oss-snapshot-local/org/github/CE-Programming/CEmu/git/)` error.

What are the steps to reproduce this issue?
-------------------------------------------
1. Go to [download](https://ce-programming.github.io/CEmu/download) page
2. Click on Windows
3. Click on either 64 or 32-bit download

Any logs, error output, screenshot, other comments...?
------------------------------------------------------
![image](https://user-images.githubusercontent.com/69565038/128758949-44355086-ebcf-433a-b142-48e453726d55.png)

**Comment by adriweb** [comment]
Yes, it needs to be fixed, basically you can get it from the Github Actions, or here: https://jacobly.com/CEmu/master/CEmu64.exe

**Comment by albertlarsan68** [comment]
The issue number is well chosen, for a Directory Not Found error...

**Comment by adriweb** [comment]
Obsolete now due to having everything in the github releases!
