### ISSUE TITLE
Feature Request: rpx filename

### ISSUE THREAD

**Issue by CorruptName** [CE-Programming/CEmu#406]
Hello, and thanks for your amazing work.
Could you please add a feature so that when the dialog which says "parsed directory doesn't contain the executable" could possibly tell us the name of the missing executable?
EG: "Parsed directory doesn't contain the executable: "red-pro2.rpx"
or you could make the title of the dialog "red-pro2.rpx is missing"

Reason: I have renamed several .rpx files and now they won't install into CEmu. I don't remember the stock names so I cannot put them back.

does anyone know how I can find these filenames otherwise? thanks!

**Comment by debrouxl** [comment]
Well, .rpx is not a standard file extension for TI-eZ80 calculators, which is what this CEmu is about.
Are you looking for the other CEmu ?

**Comment by CorruptName** [comment]
probably lol. sorry about that.
