### ISSUE TITLE
Install impossible on archlinux

### ISSUE THREAD

**Issue by benoitldr** [CE-Programming/CEmu#407]
(Thanks for reporting an issue! Please make sure to fill out the blanks below.)

What's wrong, and with what software version?
---------------------------------------------
**Operating System:** archlinux  
**CEmu version:** 1-3-0-x86  (see in the `About CEmu` menu)  
**Describe your issue:**  
impossible to install on archlinux

What are the steps to reproduce this issue?
-------------------------------------------
1. install CEmu via pacman or yaourt or yay on arch

Any logs, error output, screenshot, other comments...?
------------------------------------------------------
cemu-1.3-0-x86_64.pkg.tar.zst failed to download
error: failed retrieving file 'cemu-1.3-0-x86_64.pkg.tar.zst' from download.opensuse.org : Maximum file size exceeded
warning: failed to retrieve some files
error: failed to commit transaction (download library error)
Errors occurred, no packages were upgraded.

**Comment by adriweb** [comment]
Unfortunately, this is a dup of #320
