### ISSUE TITLE
CEmu won't launch on Manjaro Linux

### ISSUE THREAD

**Issue by epsilonfive** [CE-Programming/CEmu#409]
(Thanks for reporting an issue! Please make sure to fill out the blanks below.)

What's wrong, and with what software version?
---------------------------------------------
**Operating System:** Manjaro Pahvo 21.1.4
**CEmu version:** 1.3-1 (?) (see in the `About CEmu` menu)  
**Describe your issue:** CEmu, when installed via pacman, will not launch.

What are the steps to reproduce this issue?
-------------------------------------------
1. Install CEmu via the AUR: `pamac build ticemu`
2. Attempt to launch by running `cemu` in the terminal or through the GUI
3. Nothing happens

Any logs, error output, screenshot, other comments...?
------------------------------------------------------
It's possible this is just an outdated package, in which case it should be updated. Alternately, I may be doing something stupid.

**Comment by jacobly0** [comment]
That is not supported by us.

**Comment by epsilonfive** [comment]
Okay, that clears things up. I'll install from [https://software.opensuse.org/download.html?project=home%3Aadriweb%3ACEmu&package=cemu](url) as I'm supposed to.

**Comment by adriweb** [comment]
Or otherwise just build from the master branch
