### ISSUE TITLE
Assembly listing text hard to see with dark themes

### ISSUE THREAD

**Issue by ctrlaltmilk** [CE-Programming/CEmu#410]
What's wrong, and with what software version?
---------------------------------------------
**Operating System:** Arch Linux 5.14.7
**CEmu version:** v2.0dev (git: 0f45ce7) 
**Describe your issue:**  
Using any theme with a white foreground and dark background means it's incredibly hard to see any white text on the currently selected line.

What are the steps to reproduce this issue?
-------------------------------------------
1. Open the disassembly view using any theme with white text on a dark background, such as KDE Breeze Dark.

Any logs, error output, screenshot, other comments...?
------------------------------------------------------
![image](https://user-images.githubusercontent.com/38171793/135947751-9712981c-9016-4ba8-98cd-962531c8d03c.png)

**Comment by adriweb** [comment]
Yeah, not actually OS-specific, it's just that color choices aren't indeed always good in dark mode. I've tweaked a few already as I encountered the same issue on macOS before, but I need to finish the work I guess.

**Comment by adriweb** [comment]
I believe this has been improved since then.
