### ISSUE TITLE
Bytes in disassembly pane don't match ROM for index bit instructions

### ISSUE THREAD

**Issue by commandblockguy** [CE-Programming/CEmu#411]
For the `bit n,(iy+d)` instruction (and probably others), the instruction is disassembled correctly, but the raw bytes next to the instruction don't match the actual contents of the ROM.
e.g., memory contains "fdcb365e", the disassembly pane displays "FDCB5E36      bit 3,(iy+$36)"

**Comment by adriweb** [comment]
Info for potential fix: @jacobly0 said "the disassembler reads the bytes out of order for that instruction and apparently the disassembly lists what bytes the disassembler read, not what bytes are actually there"
