### ISSUE TITLE
CEmu acting up in Windows 11

### ISSUE THREAD

**Issue by BioHazard1282** [CE-Programming/CEmu#412]
(Thanks for reporting an issue! Please make sure to fill out the blanks below.)

What's wrong, and with what software version?
---------------------------------------------
**Operating System:** Windows 11 x64 - Build 22000.348
**CEmu version:** 1.3
**Describe your issue:**  
So I downloaded CEmu recently, first ran it and it went well. After a little bit of usage, CEmu's window got into an impossible place and I cannot access the Window. I've restarted my PC multiple times, with no luck.

I have cleared it's folder in `C:/Users/achak/AppData/Local/cemu-dev` to see if it works. I was able to get to the ROM selection screen, but after I select the ROM, I get the first "Welcome" prompt, but after that it does the same thing again.

I have ensured Windows 11 is always up-to-date, and not running any Insider Builds. I have not had this issue in Ubuntu 21.10 or macOS Big Sur.

I have tried to click the Window with the three-finger swipe motion to pull up the screen (in the screenshot below) and clicked it, tried to snap it, nothing.

What are the steps to reproduce this issue?
-------------------------------------------
1. Download the stable version of CEmu
2. Use it for a bit

Any logs, error output, screenshot, other comments...?
------------------------------------------------------
![image](https://user-images.githubusercontent.com/44819642/143666582-a425e51c-8a61-48d3-bd57-100f42c3d57f.png)

**Comment by adriweb** [comment]
To re-open if need be (try the nightly release builds first, it's probably working fine now)
