### ISSUE TITLE
Graphing this equation produces the wrong result

### ISSUE THREAD

**Issue by jon0x0** [CE-Programming/CEmu#414]
(Thanks for reporting an issue! Please make sure to fill out the blanks below.)

What's wrong, and with what software version?
---------------------------------------------
Windows 10
1.3 git 87c3b43  
ROM version: ti-84ce.rom from https://tiroms.weebly.com/uploads/1/1/0/5/110560031/ti-84ce.rom

Graphing an equation produces the wrong result.
I was graphing the equation:
Y1=6X^3+7X^2-63X+20
and comparing with a real TI-84 Plus CE side by side (helping my son with his homework).
The graph produced on the emulator was incorrect and had an inverted sense (also compared with result from wolfram alpha).
For example as X->-inf, Y should go to -inf but in the emulator goes to +inf.

What are the steps to reproduce this issue?
-------------------------------------------
1. Press Y= button
2. Enter equation above
3. Press graph
4. Change limits as appropriate (press window button and change Xmin=-7,Xmax=7,Ymin=-200,Ymax=200, you can match wolfram alpha for example.

![image](https://user-images.githubusercontent.com/20186418/144796181-46d03ae4-3e94-4dc0-8b86-3f3596a2b511.png)

![image](https://user-images.githubusercontent.com/20186418/144796291-6f2482c5-13b8-423b-9ced-43abaa7f44eb.png)

![image](https://user-images.githubusercontent.com/20186418/144796436-3ad50dec-2390-49fa-8481-607c0efa6670.png)

**Comment by jacobly0** [comment]
You have pressed the `(-)` key instead of of the `—` key, which is a negation instead of a subtraction, which means you had an implicit multiplication and it graphed `6X³+7X²×⁻63x+20` instead.  This is exactly how it behaves on hardware, so nothing to do with CEmu.
