### ISSUE TITLE
Can't Upload Basic Applications

### ISSUE THREAD

**Issue by CALPARDO** [CE-Programming/CEmu#415]
Hi, I want to use the default applications in "Apps" on the emulator. When I try to send files by doing exactly [this](https://github.com/CE-Programming/CEmu/wiki/Sending-Files), nothing changes on the emulator. The options on "Apps" and "Prgm" remain same. I'm probably doing something wrong, but I couldn't figure it out. I've also checked other closed issues.

I've tried both using an online TI-84 Plus CE ROM and generating the ROM via the built-in generator. I noticed that there are 3 default apps injected into the online ROM, but none of those apps are available on the generated one.

Temporary solution: Can someone send me a rom or bootable CEmu image that has all the default applications in it? (I need it ASAP)

What's wrong, and with what software version?
---------------------------------------------
**Operating System:** Windows 10  
**CEmu version:** v1.3 (git:87c3b43)
**Basic Application Transfer Fail**  

What are the steps to reproduce this issue?
-------------------------------------------
1. `File->Open->PlySmlt2.8ek`
2. Send it via "Variables" dock
3. Can't see the program that I sent in "Apps" or "Prgm"

![cemu-issue](https://user-images.githubusercontent.com/59120618/144914526-b215523a-2d17-4488-afd0-20d2b38296bc.PNG)

I'll be waiting for your reply,
Thank You!

**Comment by jacobly0** [comment]
You can only send applications to the latest dev version, e.g. from [here](https://jacobly.com/CEmu/master/CEmu64.exe), not the latest release.  The old way was to transfer your desired applications to a physical calculator and then get a rom dump from that which will also contain all installed applications.

**Comment by CALPARDO** [comment]
Sorry for opening an issue unnecessarily. Thank you so much!
