### ISSUE TITLE
Cannot demo Dutch exam mode: mouse click [on] missed

### ISSUE THREAD

**Issue by Stephan-P** [CE-Programming/CEmu#417]
I cannot do a demo of the Dutch exam mode with the latest CEmu build.

- Start CEmu (with OS 5.7.0)
- Make sure to switch it OFF
- On de PC keyboard hold [Shift] and next press and hold the keys [+] and [enter]
- While holding these keys - they are indicated as pressed - use the mouse pointer to click the [on] button at the CEmu keyboard
- This last click to switch on CEmu does not get through like it used to do in previous versions

Possibly this issue is about not being able to catch the mouse click (of the [on] button)

By suggestion of Adriweb I was able to work around the issue by using the [F12] key on the PC keyboard which is [bound](https://github.com/CE-Programming/CEmu/wiki/Keybindings) to the CEmu [on] key.

Environment: PC Windows 11 64-bit
CEmu: v2.0dev (git: 28575a4)

**Comment by jacobly0** [comment]
You can also right click on the keys you want to be held.

**Comment by adriweb** [comment]
Considering right clicking is actually the standard way to make keys "held", can you confirm this works without having to resort to the F12 keybinding?

**Comment by Stephan-P** [comment]
Using RMB-clicks things work beautifully. Much easier than superflexing [shift] [+] [enter] [fn] [f12]
I assume that closes this issue then
