### ISSUE TITLE
Asm( not found

### ISSUE THREAD

**Issue by sdnjack** [CE-Programming/CEmu#419]
I know that this is not brand new, but I have not found a way to dump a rom image. I have a new calculator with OS version 5.7. The catalog does not contain asm( so I cannot run the dump program. Is there a new/alternate way of doing this?

**Comment by adriweb** [comment]
First, use [arTIfiCE](https://yvantt.github.io/arTIfiCE/), and install Cesium and/or AsmHook, as you want.
Then you can launch the dumper.
