### ISSUE TITLE
[Question] How can I upload .8xk files or update OS?

### ISSUE THREAD

**Issue by m-doescode** [CE-Programming/CEmu#420]
Hello!
In my emulation, I want to install artifice in order to run ASM apps. However, artifice relies on Cabri Jr., which is a Flash App (.8xk file). When I try to upload it to the calculator, it does nothing.

So I thought maybe it was an incompatible OS, so I tried to update it and nothing happens.

I've heard that the release is very outdated and instead I should build from source, so I did. This time when I  upload the OS CEmu just hangs.

What should I do? Is there a version that doesn't experience this hang? Or is the OS too incompatible with CEmu?

---------------------------------------------
**Operating System:** Windows 10 Home (64-bit)
**CEmu version:** CEmu v2.0dev (git: 28575a4)
**TI Model:** TI-83 Premium CE
**TI OS Version:** 5.6.1.0012

What are the steps to reproduce this issue?
-------------------------------------------
1. Use the attached build of [CEmu](https://github.com/CE-Programming/CEmu/files/8507229/CEmu.zip)
2. Upload a rom containing v. 5.6.1 (downgrade using jailbreak if necessary)
3. Try to upload [TI83CEBundle-5.7.0.17.b83](https://education.ti.com/fr/software/details/fr/881DDA6D5FCF4C0FA60E7E9D10CC0950/OS-Apps-Bundle)
4. Crash

Any logs, error output, screenshot, other comments...?
------------------------------------------------------
![dwm_m4C89cnKVQ](https://user-images.githubusercontent.com/80221594/163854097-c96f4261-5900-46f1-b2cd-fd3da025ac95.png)
Console is empty
![image](https://user-images.githubusercontent.com/80221594/163851185-da671e6c-cad4-4b44-b9fa-8b6e85b87920.png)

[[ I don't know where to get logs from, please let me know where to find them and I will upload them here ]]

If you need more information, let me know!

**Comment by m-doescode** [comment]
It seems to be a problem with my build, as the nightly prebuilt works without crashing, so I'll close this for now.

**Comment by m-doescode** [comment]
Well, to answer the question in the title, the .8xk seemed to not be enough. Maybe it was an update? Anyway, I downloaded the bundle (which can be found in my first comment) and extracted CabriJr.8ek (note 8ek instead of 8xk) from the bundle using 7zip and just uploaded that. (It takes a while to validate) And then it worked!

**Comment by adriweb** [comment]
Two things for future readers: 
- CEmu 2.0 or later is needed for apps and OS transfers (current master branch is OK)
- apps for the CE calculator models need to be .8ek files. The ones that are 8xk are for older calculators.
