### ISSUE TITLE
[Feature Request] Edit keybinds

### ISSUE THREAD

**Issue by TheAlphaReturns** [CE-Programming/CEmu#422]
(Thanks for reporting an issue! Please make sure to fill out the blanks below.)

What's wrong, and with what software version?
---------------------------------------------
**Operating System:** windows 11
**CEmu version:** 1.3
**Describe your issue:**  Make it possible to edit keybinds.

**Comment by mateoconlechuga** [comment]
You already can by exporting the current keybindings and setting the keys you want in the text file, then loading the text file when you select the custom keybind option.

**Comment by Reycko** [comment]
> You already can by exporting the current keybindings and setting the keys you want in the text file, then loading the text file when you select the custom keybind option.

how do you do that?
