### ISSUE TITLE
Can't load Mirage OS

### ISSUE THREAD

**Issue by Robbonabbo** [CE-Programming/CEmu#423]
What's wrong, and with what software version?
---------------------------------------------
**Operating System: Windows 10 Enterprise**
**CEmu version: 1.3** 
**Describe your issue: Mirage OS extension not avaiable. In the extensions bar the .xk file cannot be opened up**  

What are the steps to reproduce this issue?
-------------------------------------------
1. Open new File
2.Mirage Os not avaiable

Any logs, error output, screenshot, other comments...?
It's not really an issue but it's worth noticing

**Comment by debrouxl** [comment]
MirageOS is for the monochrome 83+-type calculators series. On the TI-eZ80 series, Cesium is the way to go :)
