### ISSUE TITLE
Windows 10 requires gamingoverlay app?

### ISSUE THREAD

**Issue by Stephan-P** [CE-Programming/CEmu#425]
![image](https://user-images.githubusercontent.com/10008599/177705783-17d29d86-140b-4e64-aa94-03507ef9eefc.png)

Edition: Windows 10 Home
Version: 21H2
Installation date: ‎11-‎3-‎2022
Build of the OS: 19044.1806
Experience: Windows Feature Experience Pack 120.2212.4180.0

Suddenly my W10 is throwing up complaints that I should provide a link to a gamingoverlay app.

"You need a new app to open this MS-GamingOverlay-lnk"

Whether I tick the box or not, the [ok]  button never becomes active.
The dialogue disappears after pressing the [esc] key or clicking any window on the screen.

Any idea as to resolving/preventing this?

**Comment by adriweb** [comment]
Well that's not something we've intentionally requested... Maybe touch events from Qt are now triggering this, with some windows update?

**Comment by Stephan-P** [comment]
I'll do some digging to find out more.
Maybe it has something to do with my specific Windows setup.

**Comment by Stephan-P** [comment]
Closing this issue as I'm no longer using W10

**Comment by alberthdev** [comment]
Somewhat late, but I think it's a semi-known issue because there's a very similarly named gaming oriented project. You can totally rename the EXE to avoid that pop up.
