### ISSUE TITLE
How to create a graphing calculator emulator?

### ISSUE THREAD

**Issue by marethyu** [CE-Programming/CEmu#426]
Sorry if this is not the right place to ask but I am wondering how to create a graphing calculator emulator like CEmu. I plan to create one for fun but I am not sure where to find comprehensive hardware documentations. [This is all I can find](https://www.ticalc.org/pub/text/calcinfo/). What are other good places I should check out?

**Comment by adriweb** [comment]
[WikiTI](https://wikiti.brandonw.net/index.php?title=Calculator_Documentation) has lots of info.
