### ISSUE TITLE
Incorrect behavior of EX (SP),HL/I instructions in 16-bit mode

### ISSUE THREAD

**Issue by calc84maniac** [CE-Programming/CEmu#427]
As it turns out, EX (SP),HL and its index register equivalents don't actually zero the upper byte of the register pair in 16-bit mode on a real eZ80. I use 16-bit mode a lot and this was hiding some bugs in my code, so fix plzkthx

**Comment by jacobly0** [comment]
Fixed by bfe5d1cd694ca3288168c478666ef20367afaa31.
