### ISSUE TITLE
apple sillicon native compatibility

### ISSUE THREAD

**Issue by anonymousaga** [CE-Programming/CEmu#428]
(Thanks for reporting an issue! Please make sure to fill out the blanks below.)

What's wrong, and with what software version?
---------------------------------------------
**Operating System:** MacOS 12.4 Monterey
**CEmu version:** 1.3
**Describe your issue:**  
The app runs via rosetta on an m1 mac, but eventually it will need to run natively. When will this happen?

**Comment by adriweb** [comment]
Yes: probably when we release v2.0 which is when the GUI is rewritten (now a work in progress). Also this supposed all the dependencies are buildable natively but hopefully by now they are...

**Comment by anonymousaga** [comment]
Should i close this now or when 2.0 is released? Thanks!

**Comment by adriweb** [comment]
That's fine let's keep it open and we'll close it after I actually make the native build

**Comment by Jerry23011** [comment]
Hi, wondering if we have any update on this?

**Comment by adriweb** [comment]
Not yet, but it will definitely be done one day!

**Comment by Jerry23011** [comment]
Thanks a lot! Waiting for that day to come. Amazing emulator you've made

**Comment by adriweb** [comment]
When GitHub Actions has M1/M2 runners (see [here](https://github.com/actions/runner-images/issues/2187)), these builds will be automatic, considering I just merged a patch to have mac builds automatically.

**Comment by Jerry23011** [comment]
> When GitHub Actions has M1/M2 runners (see [here](https://github.com/actions/runner-images/issues/2187)), these builds will be automatic, considering I just merged a patch to have mac builds automatically.

Thanks for the update, surprised that no Apple silicon runners is deployed 2 years after Apple's release, lol

**Comment by Jerry23011** [comment]
Hi, I think GitHub already deployed Apple silicon runners, if I'm not mistaken. I was browsing the blog and I found [this](https://github.blog/changelog/2022-08-09-github-actions-self-hosted-runners-now-support-apple-m1-hardware/)
I also found it in [GitHub roadmap](https://github.com/github/roadmap/issues/507) labeled as done.

**Comment by adriweb** [comment]
Nope actually this is for self-hosted runners, which we don't have.

**Comment by adriweb** [comment]
No this is for self-hosted runners, which we don't have.

**Comment by Jerry23011** [comment]
Oh, I see, thanks

**Comment by davecarlson** [comment]
They've now been given a timeline - Q3 of this year! 
https://github.com/orgs/github/projects/4247?pane=issue&itemId=5944419

**Comment by jfawkes5** [comment]
Fingers crossed!

**Comment by Jerry23011** [comment]
I think this has been implemented last month, what are your thoughts?

https://github.blog/2023-10-02-introducing-the-new-apple-silicon-powered-m1-macos-larger-runner-for-github-actions/

**Comment by adriweb** [comment]
This is currently only for "Large(r) runners" which are not free unfortunately.

**Comment by Jerry23011** [comment]
> This is currently only for "Large(r) runners" which are not free unfortunately.

Oh no 🥲

**Comment by adriweb** [comment]
I should be able to provide native builds manually from time to time however.

**Comment by adriweb** [comment]
GitHub is now supporting free m1 builds apparently. I'll try to make the required changes soon.

**Comment by Jerry23011** [comment]
The native arm build is super fast, thank you so much
