### ISSUE TITLE
[Feature Request] RetroAchievements Support

### ISSUE THREAD

**Issue by TheFetishMachine** [CE-Programming/CEmu#429]
[RetroAchievements](http://retroachievements.org/) is a website, community and service that uses emulators to add achievement support for a variety of game platforms (not only consoles) by hooking into the emulator's memory. As there is a healthy TI calculator homebrew scene, I think it might be nice to have RetroAchievements support for all the available games.

NB: Yes I am aware this TI-84 emulator called CEmu isn't the same as the Wii U emulator Cemu :P

Here are some documents on how integration works:
https://github.com/RetroAchievements/RAInterface/wiki/Creating-a-new-emulator
https://github.com/RetroAchievements/rcheevos/wiki

**Comment by SuperSamus** [comment]
Well, the other Cemu is now on GitHub.
https://github.com/cemu-project/Cemu/issues/50

**Comment by adriweb** [comment]
(We aren't planning on doing that ourselves, but if someone is still interested in this feature, please contribute!)
