### ISSUE TITLE
cemu-autotester CLI does not find correct hashes; running program through the CEmu autotester dialog does

### ISSUE THREAD

**Issue by captain-calc** [CE-Programming/CEmu#430]
What's wrong, and with what software version?
---------------------------------------------
**Operating System:** Fedora 36
**CEmu version:** CEmu v2.0dev (git: 28575a4)
**Describe your issue:**  

The CLI-based testing script does not get the correct hashes for a particular test. Homescreen output appears as expected when running the test manually. Putting the test through the CEmu Autotester dialog reports that all correct hashes were found. The CLI autotester and the one in the CEmu GUI are not reporting the same results.

The testing framework requires a Linux distribution (only tested under Fedora), Python 3.9+, and Bash.

What are the steps to reproduce this issue?
-------------------------------------------
1. Clone the MemoryClassTest repo, available [here](https://www.github.com/captain-calc/MemoryClassTest).
2. Set the `TI84PCE_ROM_PATH` and `PROGRAM_SRC_PATH` environment variables following the instructions in the repo's README.
3. Run `bash runtests.sh tests/`. This script calls a Python program that will automatically update every autotest.json file with the ROM path you provided in `TI84PCE_ROM_PATH`.
4. The script will compile all of the tests and then run them. The code that calls the `cemu-autotester` in the testing script is [here](https://github.com/captain-calc/MemoryClassTest/blob/225d02382958ccb81c4f2d565d4e4711b06740c6/.runtests/runtests-backend.sh#L108).
5. The test `memory_ReadOnlyMemory_read_seq_4` will fail with 3 out of 3 mismatched hashes.

Any logs, error output, screenshot, other comments...?
------------------------------------------------------
The testing script's output on the failed test (using `cemu-autotester -d`):
![autotester_error](https://user-images.githubusercontent.com/57052406/184948155-597b32ba-be92-49a9-8a4c-93962a5cdc9f.png)

The output for the CEmu Autotester dialog:
![CEmu_autotester_output](https://user-images.githubusercontent.com/57052406/184948592-f79ac725-fad1-4ea5-8bdc-b214e81007cd.png)

**Comment by jacobly0** [comment]
You are hashing the following images:
![failure_hash1_num1_dump](https://user-images.githubusercontent.com/15544577/184953453-7cfdde9d-45a8-4a37-b0a4-3c3dfbea2384.png)
![failure_hash2_num2_dump](https://user-images.githubusercontent.com/15544577/184953473-1c7eb606-ae40-40aa-8e11-5919b4b7ce31.png)
![failure_hash3_num3_dump](https://user-images.githubusercontent.com/15544577/184953485-796c4d01-339a-4ca3-a4f4-33be7454bec0.png)
