### ISSUE TITLE
CEmu port on 3DS in the works

### ISSUE THREAD

**Issue by superbeelavaman** [CE-Programming/CEmu#432]
Hello. I am planning to port CEmu to Nintendo 3DS so that Homebrewers need not carry their calculators around in gaming conventions, and can instead bring an 11-year-old handheld console. The Nintendo 3DS, or 3DS for short, is a handheld console released by Nintendo in 2011 with an ARM11 cpu, running at 268 or 804 MHz, depending on the variation. The TI-84 Plus CE, while it was released in 2015, 3 years after the 3DS, has a mere eZ80 cpu running at only 6-15 MHz depending on compatibility modes. This leads me to believe that it will be easy to port CEmu to Nintendo 3DS and have it run well enough to be usable. I will get started on this project as soon as possible so that all of us nerds in the TI-Calc community and the Homebrew Community can have fun as one larger community.

**Comment by adriweb** [comment]
Ok sure you can try, even though I'm not sure that it will perform well. Of course, use a small gui on top of the core, maybe like [the SDL one](https://github.com/CE-Programming/CEmu/tree/master/gui/sdl).

**Comment by superbeelavaman** [comment]
I stopped working on this, I might finish this eventually but there's no reason to leave this open
