### ISSUE TITLE
CEmu crashes when exporting keybind layout 

### ISSUE THREAD

**Issue by ascpial** [CE-Programming/CEmu#434]
I'm using CEmu on Fedora 36, but I did ran into the same issue on Windows a while ago.
My current version is v1.3 (I used the RPM package for fedora 35 on the website).

To reproduce the bug, selectthe natural keyboard layout, go to the `File` section, then `Export` and export the Keyboard layout.
When the file is selected, the app crashes and the file is not exported.

I can see in the terminal the following output : `Erreur de segmentation (core dumped)`

**Comment by ascpial** [comment]
Apparently the issue seems random : I just tried to replicate it and it doesn't work...

**Comment by adriweb** [comment]
Dup of #448 (keeping that new one open instead since it got more attention)
