### ISSUE TITLE
Unable to select save location for ROM from calculator image

### ISSUE THREAD

**Issue by etleyden** [CE-Programming/CEmu#441]
Operating System: macOS 12.6
CEmu version: The MACOS 64-BIT release from 2021-09-20 (the current download as of 2022-10-30)

Issue: 
I downloaded the app, and I'm trying to create a ROM image from my TI-84 Plus CE. Here is what I did:

1. Clicked "Create a ROM image from you calculator" in the application
2. Ran DUMP program that was provided on the calculataor
3. Used TI-Connect CE Software to drag and drop 13 ROMData prefixed files to the window of the CEmu app
4. A finder window opens up to select a directory to save the ROM to. 
5. When selecting the directory, there is only an option to "Open" the directory, instead of saving to the directory -- So I can't actually save the ROM, just navigate the directory where I want to save the files. 

<img width="1792" alt="Screen Shot 2022-10-30 at 11 28 42" src="https://user-images.githubusercontent.com/113561319/198887085-6036fe0c-a6e3-402c-b611-ea0ccd255f1f.png">

**Comment by adriweb** [comment]
No, you have to drag'n'drop the files OUT OF the ti connect ce's window into a folder of your choice in the finder, which you'll later choose from CEmu. CEmu will make a .rom file out of the 8xv, that will be used for emulation.

**Comment by etleyden** [comment]
I see 👀 thanks!
