### ISSUE TITLE
Image artifacts when pasting screenshot to Imgur

### ISSUE THREAD

**Issue by TheLastMillennial** [CE-Programming/CEmu#442]
(Thanks for reporting an issue! Please make sure to fill out the blanks below.)

What's wrong, and with what software version?
---------------------------------------------
**Operating System:** Windows 10 21H2
**Browser:** Firefox 106
**CEmu version:** 1.3

**Describe your issue:**  
Clicking 'Copy PNG' then pasting to Imgur results in a black row of pixel at the very top, and distortion on the right side. The distortion looks like the left side of the image is overflowing to the right side.
Example:
https://i.imgur.com/pLIfwBVm.png

Expected image:
https://i.imgur.com/vxQ9Hg3m.png

What are the steps to reproduce this issue?
-------------------------------------------
1. Click 'Copy PNG'
2. Press ctrl+v at username.imgur.com/all/
3. View the image you just paste.

Any logs, error output, screenshot, other comments...?
------------------------------------------------------
This is only a problem between CEmu and Imgur.
I can properly paste to other applications such as Paint. 
Other applications can properly paste to Imgur such as Paint.
To get expected image:
1. Copy PNG 
2. Paste to Paint
3. Copy the photo in paint
4. Paste from Paint to Imgur
5. You will get the expected image.

**Comment by adriweb** [comment]
Seems to me like it's a recompression issue over at imgur? We don't do anything special for CEmu screenshots, it's all handled by the Qt lib, so 🤷‍♂️

**Comment by adriweb** [comment]
To re-open if need be
