### ISSUE TITLE
Chinese localization

### ISSUE THREAD

**Issue by Jerry23011** [CE-Programming/CEmu#443]
What's wrong, and with what software version?
---------------------------------------------
**Operating System:** macOS 12.6.1
**CEmu version:** CEmu v2.0dev (git: bbc337b)
**Describe your issue:**  
Hi, I really love this app, helped me a lot when I forget to bring my Ti-84 with me. I see that the GUI has been already translated into several languages and I'm wondering if you could add Chinese localization strings? I'd love to help with the translations

**Comment by adriweb** [comment]
Hi,

Sure, you can add a translation with the **Qt Linguist** tool loaded on the project. You can choose the language, start translating the strings, then make a PR here with the two files (.ts and .qm, if I remember correctly)

**Comment by Jerry23011** [comment]
Hi, after reading the qt docs, I find it too energy-consuming for me to learn a new platform. I'll just stick with the English version which I'm already happy with and wait to see if anyone with the skill would like to do the translation strings. Thanks🙏🏻

**Comment by adriweb** [comment]
You may have been intimidated by the whole Qt environment, but for translating strings, it's not required. As I said, only Qt Linguist (a standalone app) is needed, then you just translate the strings.
But, as you want :P

**Comment by Jerry23011** [comment]
Yeah, I just managed to install Qt Linguistic, learning on the usage of it.
