### ISSUE TITLE
Windows 11 => black logging window no longer auto closes on launch

### ISSUE THREAD

**Issue by tutorllini** [CE-Programming/CEmu#446]
(Thanks for reporting an issue! Please make sure to fill out the blanks below.)

What's wrong, and with what software version?
---------------------------------------------
**Operating System:** …  Windows 11
**CEmu version:** … v2.0dev
**Describe your issue:**  
… CEmu64 black window does not auto close on Windows 11

What are the steps to reproduce this issue?
-------------------------------------------
1. … Launch CEmu
2. … Observe 2nd window not auto closing
3. …

Any logs, error output, screenshot, other comments...?
------------------------------------------------------
…
![image](https://user-images.githubusercontent.com/119153475/204123303-8434e512-6587-42a7-ad51-f7b61b591b5e.png)

**Comment by adriweb** [comment]
Can confirme on (a recent) Windows 11 - apparently doesn't happen on older versions of windows.
There's also no logging there, in the default (?) window, or the one that pop up when we explicitly ask for it in the menus, even with console logging picked instead of in the dock.

**Comment by adriweb** [comment]
However, after restarting CEmu, logging does appear there... and closing the main window also closes it.
So... it's only buggy the first time?

**Comment by tutorllini** [comment]
Hi Adrien!

My issue is that I really want the black logging window to auto close on launch. Anything I can do to make that happen? Just like on Windows 10.

**Comment by adriweb** [comment]
I have no idea for now sorry :P 
The fact that it was working on a previous windows version is annoying, considering we didn't change the behavior in CEmu

**Comment by Stephan-P** [comment]
@tutorllini 
I only use CEmu for maths educational purposes and have no desire whatsoever for the Terminal window to appear.

I guess we would need some sort of automated task in the Windows Task Scheduler
Task "Kill CEmu Terminal":
- if CEmu AND Terminal become active
- then close the Terminal window

Now how can we establish this?
I'm on the hunt!

**Comment by adriweb** [comment]
No, it would of course be better to do this in windows-specific CEmu code instead.

**Comment by Stephan-P** [comment]
Solution from [Microsoft Learn](https://learn.microsoft.com/en-us/answers/questions/1114677/task-scheduler-task-to-detect-and-close-window.html?childToView=1114853#comment-1114853):
- create - if you hadn't done so already - a shortcut to CEmu.exe
- give the shortcut the property "run minimized"

Start CEmu through this shortcut and it will start without the Terminal window. Pin to your taskbar for regular usage.

**Comment by adriweb** [comment]
Good job finding this workaround!

**Comment by Stephan-P** [comment]
BTW, in my CEMu installation folder (C:\Program Files\CEmu) I've got the following additional files that may be helpful:
- TI-84 Plus CE-T Emulator.ico
- TI-84 Plus CE-T Emulator.lnk

[CEmu ico and lnk.zip](https://github.com/CE-Programming/CEmu/files/10146825/CEmu.ico.and.lnk.zip)

**Comment by tutorllini** [comment]
What do those two files do? Thanks so much for finding the solution!

**Comment by Stephan-P** [comment]
The first is a nice icon for CEmu.
The second is a shortcut to cemu making use of this icon file

**Comment by adriweb** [comment]
I'm not quite sure what changed, but I can't repro with the latest nightly version (for both qt5 and qt6 builds) on Win11.

Feel free to re-open with details if it happens again (using nightly at least)

**Comment by Stephan-P** [comment]
@adriweb Cleaning up or picking up developments again?

**Comment by adriweb** [comment]
Both - we're getting ready for a v2.0 release, and there is a very long list of improvements lately, mostly done by @calc84maniac :)
