### ISSUE TITLE
natural keybindings export causes CEmu to crash

### ISSUE THREAD

**Issue by tutorllini** [CE-Programming/CEmu#448]
(Thanks for reporting an issue! Please make sure to fill out the blanks below.)

What's wrong, and with what software version?
---------------------------------------------
**Operating System:** …  Windows 11
**CEmu version:** … v2.0dev
**Describe your issue:**  
… exporting natural keybindings causes crash. really want to customize!

What are the steps to reproduce this issue?
-------------------------------------------
1. …Launch CEmu
2. …Set key bindings to Natural
3. …File => Export => Keypad Mapping => Save (crash)

Any logs, error output, screenshot, other comments...?
------------------------------------------------------
…would love to customize these bindings. Please let me export the ini file!

**Comment by adriweb** [comment]
I'm not sure natural keybindings are supposed to be modified/modifiable as they're made to translate what you type into something as close as possible on the calc... but I'll let @jacobly0 answer more precisely.

**Comment by Jerry23011** [comment]
I just found the same problem, if I change key bindings to `Natural` in settings and choose to export key bindings, CEmu will crash the moment I click `Save`

Here are the screenshots
<img width="633" alt="截屏2022-12-02 20 31 49" src="https://user-images.githubusercontent.com/89069957/205295972-bce78dcd-58f2-45be-abba-680ec50328c8.png">
<img width="475" alt="截屏2022-12-02 20 32 08" src="https://user-images.githubusercontent.com/89069957/205295986-01d99d1f-0954-41b4-b734-3041d56454ce.png">

macOS 12.6.1
CEmu v2.0dev (git: 6cab11d)

**Comment by adriweb** [comment]
Turns out this is a dup of #434 but this issue got more attention, so let's keep this one open and close the other one

**Comment by adriweb** [comment]
Natual keymap isn't exportable because it is not actually a real keymap in the sense of the other ones. It now shows a warning before trying to export it.
