### ISSUE TITLE
Localization incomplete on macOS menubar

### ISSUE THREAD

**Issue by Jerry23011** [CE-Programming/CEmu#450]
What's wrong, and with what software version?
---------------------------------------------
**Operating System:** macOS 12.6.1
**CEmu version:** CEmu v2.0dev (git: 2a005b1)
**Describe your issue:**  
`About CEmu` doesn't show the translation even if it is localized, I tried all the languages, and the option in every language is displayed as English

Also, is it possible to make other options in the menu localizable, like `Quit CEmu`, `Hide`, and `Hide Others`, etc.

Screenshots
------------------------------------------------------
<img width="262" alt="截屏2022-11-29 20 31 55" src="https://user-images.githubusercontent.com/89069957/204531118-1b4110d8-74ef-4f86-912b-52bb354971dd.png">

**Comment by adriweb** [comment]
We're probably missing some `tr(...)` here and there.

**Comment by Jerry23011** [comment]
Anything I can do?

**Comment by adriweb** [comment]
I need to check on my side, but those may be Qt interacting with macOS standard stuff and it might not be the same way to translate those... Is your OS also in Chinese? I would expect it to be translated correctly if it was system-provided, but... I don't know, I need to dig into it more I guess.

**Comment by Jerry23011** [comment]
Yes, my system is in Chinese, too.
and it's very likely it's system-provided because some other apps who doesn't have Xcode as IDE also experience the same problem with options like `Hide`, `Service`, `Hide Others`.
It shows in system settings that CEmu doesn't support languages other than English, so I suppose Qt doens't provide the option.

**Comment by Jerry23011** [comment]
I just tested on Windows (Chinese version) and find the translations for `About CEmu` and `Quit` are all there, so I think it's likely to be Qt's problem.

**Comment by adriweb** [comment]
Alright can you try this ? (macOS 10.15 minimum)
[CEmu_qt6_macOS_test.zip](https://github.com/CE-Programming/CEmu/files/10140852/CEmu_qt6_macOS_test.zip)

(it's codesigned, but you might have to do right-click > open, I don't remember)

**Comment by adriweb** [comment]
ok, we'll keep that in mind if we ever switch to Qt6.
Anyway, I guess I'll have to close this then, it's an external issue :(

Feel free to re-open if you know of a workaround, thanks!

**Comment by Jerry23011** [comment]
Thanks a lot for testing it out. 🙏🏻

**Comment by Jerry23011** [comment]
Hi, I think I found a string that is not localizable `Version copied!`, I can't reopen this issue for now, could you please reopen it, thanks

**Comment by adriweb** [comment]
well that's for another issue/PR, you can directly open a PR for that if you want :)

Basically `tr("Version copied!")` instead of `"Version copied!"`, then the usual translation files updates (qm/ts)
