### ISSUE TITLE
CEmu Terminal window stays visible in latest W11

### ISSUE THREAD

**Issue by Stephan-P** [CE-Programming/CEmu#451]
CEmu v2.0dev (git: 6cab11d) on Windows 11 (fully up-to-date)

Off late, the CEmu terminal window remains visible whereas it used to disappear when CEmu would be fully started.
Most likely some Windows 11 update changed this behaviour.

How can I make the CEmu Terminal window automatically disappear again, or better not to show up at all?

[Edit: updated CEmu version to latest]

**Comment by adriweb** [comment]
Duplicate of #446 

seems like a windows/qt issue on win11.
