### ISSUE TITLE
Missing translation in About page

### ISSUE THREAD

**Issue by Jerry23011** [CE-Programming/CEmu#452]
Hi, I did find where I should add `tr(`, but how can I sync the change to the `.ts` file.
<img width="806" alt="截屏2022-12-02 21 31 15" src="https://user-images.githubusercontent.com/89069957/205303916-5aa3d364-21ca-4063-86a3-6764f13e69f7.png">
<img width="671" alt="截屏2022-12-02 21 28 21" src="https://user-images.githubusercontent.com/89069957/205304595-4df0a7a3-b31c-4b74-a2d7-ff5e42d28c1f.png">

**Comment by adriweb** [comment]
You'll have to run the qt `lupdate` command on the .pro file (as parameter), which will update the .ts file. Then with Qt Linguist, add the translation, then save/release the file to get the .qm binary. Then PR all this.

If you don't manage to do that, let me know what the translation would be

**Comment by Jerry23011** [comment]
Do you think this is right? I think it's messing up the `.ts` file. LOL
I just used the command `lupdate mainwindow.cpp -ts zh-CN.ts`

<img width="1264" alt="截屏2022-12-02 22 16 49" src="https://user-images.githubusercontent.com/89069957/205312887-a1bb731d-1af4-4bcb-9d15-6c35034dad14.png">

**Comment by adriweb** [comment]
no no, `lupdate CEmu.pro`
