### ISSUE TITLE
CEmu not receiving Apps.

### ISSUE THREAD

**Issue by ValkTheBoxman** [CE-Programming/CEmu#460]
(Thanks for reporting an issue! Please make sure to fill out the blanks below.)

What's wrong, and with what software version?
---------------------------------------------
**Operating System:** Windows 11 Insider Build (Beta Channel)
**CEmu version:** 1.3  
**Describe your issue:**  
I want to do a screenshot of a Python program i made.
My rom dump came without programs nor apps.
I have OS 5.8 with python edition and CEmu wont recieve Python app or Cabri Jr 5.0.
But sending programs or appvars work.

What are the steps to reproduce this issue?
-------------------------------------------
1. Try to send .8ek files to CEmu

Any logs, error output, screenshot, other comments...?
------------------------------------------------------
Nothing interesting to see in logs.
My calculator is TI-84 Plus CE-T Python edition revision V (the one without charging led)

**Comment by adriweb** [comment]
Yes that's not supported using the latest release. You'll have to download the latest nightly/dev build instead : https://github.com/CE-Programming/CEmu/releases/tag/nightly

**Comment by rsenna** [comment]
@adriweb That makes sense, but **please** add that information to the README.md file... I am just starting, and it took me a while to find out. 🙏🏼
