### ISSUE TITLE
Allow CEmu to be pushed to the back of the screen instead of leaving it in the front.

### ISSUE THREAD

**Issue by Zexxerd** [CE-Programming/CEmu#465]
(Thanks for reporting an issue! Please make sure to fill out the blanks below.)

What's wrong, and with what software version?
---------------------------------------------
**Operating System:** MacOS v12.6.1
**CEmu version:** CEmu v2.0dev (git: dcb3c27)
**Describe your issue:**  
CEmu is always at the front of the screen, makes it really inconvenient to switch from there and back while coding.

What are the steps to reproduce this issue?
-------------------------------------------
1. Open CEmu and another GUI application, like a browser. CEmu should appear in the front.
2. Click on application to see if CEmu vanishes.

Any logs, error output, screenshot, other comments...?
------------------------------------------------------
.. / .-.. --- ...- . / .--. . .- ...

**Comment by adriweb** [comment]
There's a checkbox in the settings for keeping CEmu in the foreground, so I guess you must have checked that at some point.
Now you just want to uncheck that.

**Comment by Zexxerd** [comment]
Ah, I see 🙃
