### ISSUE TITLE
Variables that start with `r` show up as `Ans` in the Variable Viewer

### ISSUE THREAD

**Issue by LogicalJoe** [CE-Programming/CEmu#466]
What's wrong, and with what software version?
---------------------------------------------
**Operating System:** MacOS Ventura 13.3.1 (a)
**CEmu version:** CEmu v2.0dev (git: 851a59e)
**Describe your issue:**  
Any variable that starts with the letter `r` shows up as `Ans` in the Variable Viewer.

What are the steps to reproduce this issue?
-------------------------------------------
1. Send variable (AppVar) with a name that starts with `r` to the calculator
2. Open the Variable Viewer

Any logs, error output, screenshot, other comments...?
------------------------------------------------------
This is because `Ans` (token 072h) and `r` (font character 072h) are the same, so when generating the file name it checks the first character and `Ans` takes precedence.
https://github.com/CE-Programming/CEmu/blob/badbf3c0cbc377115977eb4a4c3f0c619849649c/core/vat.c#L176-L180
<img width="535" src="https://github.com/CE-Programming/CEmu/assets/47825483/99d2c441-4832-4e4f-adcb-cd6b0cc049ed">

**Comment by captain-calc** [comment]
Pull request with possible fix here: https://github.com/CE-Programming/CEmu/pull/467
