### ISSUE TITLE
Dark mode does not work on macOS

### ISSUE THREAD

**Issue by SoCuul** [CE-Programming/CEmu#471]
What's wrong, and with what software version?
---------------------------------------------
**Operating System:** macOS Ventura 13.5
**CEmu version:** CEmu v1.3 (git: 87c3b43)
**Describe your issue:** Even though macOS dark mode is enabled, all UI elements appear in light mode.

What are the steps to reproduce this issue?
-------------------------------------------
1. Open CEmu and be faced with the bright UI elements haha

Any logs, error output, screenshot, other comments...?
------------------------------------------------------
<img width="1440" alt="image" src="https://github.com/CE-Programming/CEmu/assets/63339559/078b8b7c-79bc-44fc-b954-522dbaa3947f">

**Comment by adriweb** [comment]
I think it only does that on a Qt5 build, with Qt6 it's all good. I should probably make the CI do that...

**Comment by SoCuul** [comment]
> I think it only does that on a Qt5 build, with Qt6 it's all good. I should probably make the CI do that...

Are there any plans to publish a new release build anytime soon?

**Comment by adriweb** [comment]
When I get around to work on the Qt6 CI (maybe this weekend) it will show up in the _nightly release_ which has binaries automatically updated at every commit.

**Comment by SoCuul** [comment]
Good to know!

**Comment by adriweb** [comment]
Ok so that was easy enough, and it is available here: https://github.com/CE-Programming/CEmu/releases/download/nightly/CEmu-nightly_mac_qt6.dmg
... but will only actually work as soon as I fix something that unexpectedly broke with a lib update a few days/weeks ago.
Which should be hopefully soon, I've found a "solution" to the issue.

**Comment by adriweb** [comment]
All good, it's ready on the download link I wrote before!

Dark mode as expected :)
<img width="1041" alt="image" src="https://github.com/CE-Programming/CEmu/assets/660896/fd008c0e-6984-4dd1-b965-9215d56a4d88">

**Comment by SoCuul** [comment]
How stable is the nightly build in this case?

**Comment by adriweb** [comment]
It's supposed to be considered stable, considering the master branch gets either small fixes/features, or major ones that have been worked on in another branch before being ready
