### ISSUE TITLE
Python app isn't working

### ISSUE THREAD

**Issue by UnChiller** [CE-Programming/CEmu#472]
What's wrong, and with what software version?
---------------------------------------------
**Operating System:** Ubuntu 23.10
**CEmu version:** CEmu v2.0dev (git: dd34079)  
**Describe your issue:** when trying to use the TI python app it seems stuck setting up "python firmware" 

What are the steps to reproduce this issue?
-------------------------------------------
1. start with TI-84 Plus CE Python ROM with latest OS version (on ubuntu?)
2. send latest python app
3. open python app

Any logs, error output, screenshot, other comments...?
------------------------------------------------------
![image](https://github.com/CE-Programming/CEmu/assets/81498434/c3044a10-d6a6-4463-8309-58e3e02e33e0)

**Comment by adriweb** [comment]
Indeed, the python-related hardware/features aren't emulated yet in CEmu. One day they may...

**Comment by UnChiller** [comment]
Same problem with feature/python

**Comment by adriweb** [comment]
Yes, it's not currently supported. Might be in the future.
