### ISSUE TITLE
Cant send Flash Apps to calc

### ISSUE THREAD

**Issue by superduperdev01** [CE-Programming/CEmu#475]
(Thanks for reporting an issue! Please make sure to fill out the blanks below.)

What's wrong, and with what software version?
---------------------------------------------
**Windows 11:** …  
**1.3:** … (see in the `About CEmu` menu)  
**Not sending .8ek (Flash Apps) files:**  
… (including, if applicable what you expect vs. what happens)  

What are the steps to reproduce this issue?
-------------------------------------------
1. …Load up CEmu
2. …Create ROM
3. …Load ROM
4. ...Load .8ek file on to emulated calculator
5. ...Send to calculator
6. ...Check apps

Any logs, error output, screenshot, other comments...?
------------------------------------------------------
…

**Comment by superduperdev01** [comment]
No console errors

**Comment by adriweb** [comment]
Yep, the latest actual release is super old and doesn't include USB improvements, so you need a nightly build from here instead: https://github.com/CE-Programming/CEmu/releases/tag/nightly
