### ISSUE TITLE
Sending .8ek files not working on Mac OS

### ISSUE THREAD

**Issue by SpyterDev** [CE-Programming/CEmu#477]
For Mac OS 14.4 (M1 Mac Mini), I tried sending a .8ek file (Cabri Jr as I need to test out some c programs and only have a 5.7.0 rom saved) to my emulated calculator but it doesn't receive the app when I send any .8ek files to the calculator and there is no error in terminal.

**Comment by adriweb** [comment]
You need to download the [latest nightly version](https://github.com/CE-Programming/CEmu/releases/tag/nightly) of CEmu, not the latest release
