### ISSUE TITLE
Fullscreen CLI flag doesn't work

### ISSUE THREAD

**Issue by maxwiseman** [CE-Programming/CEmu#479]
What's wrong, and with what software version?
---------------------------------------------
**Operating System:** Tested on MacOS Sonoma 14.5 and Raspbian 11
**CEmu version:** 1.3
**Describe your issue:**  
When I run the `cemu --fullscreen 2` (or 1) commands, CEmu launches in its normal mode, not in fullscreen. The help flag shows that it should launch in either of the two fullscreen modes depending on whether you pass a 1 or 2. I can still get to fullscreen by pressing F11, but it does not launch in fullscreen as I would expect it to.

What are the steps to reproduce this issue?
-------------------------------------------
1. Run CEmu with the --fullscreen flag

**Comment by adriweb** [comment]
Can repro in nightly too.

**Comment by adriweb** [comment]
Maybe [this code](https://github.com/CE-Programming/CEmu/blob/master/gui/qt/mainwindow.cpp#L1005-L1010) needs to be put at the end of the function?

**Comment by adriweb** [comment]
There have been some changes recently regarding full-screen handling (c1a2f1a2e2287e67d2bbaf6bc3c6f1f3a0e76ee9 , ee9570dc1fc5dd8f1df68ae6ff14c1f15c2b4270).
I can't repro the issue anymore.

Feel free to re-open if you encounter the issue again when trying the latest nightly build.
