### ISSUE TITLE
Box whisker plot with outliers is not drawn correctly

### ISSUE THREAD

**Issue by paulybrowneyes** [CE-Programming/CEmu#480]
(Thanks for reporting an issue! Please make sure to fill out the blanks below.)

What's wrong, and with what software version?
---------------------------------------------
**Operating System: MacOS Sonoma  
**CEmu version:** … V2.0dev 
**Describe your issue:**  
When you draw an box whisker plot using a list with outliers, the plot doesn't have the outliers 

What are the steps to reproduce this issue?
-------------------------------------------
1. Enter following in your list L1 (stat key, then 1)
    3, 7, 8, 8, 5, 9, 10, 12, 14, 7, 1, 3, 8, 16, 8, 6, 9, 10, 13, 7
2. Press 2nd + y= keys to graph the list
3. Select the 4th graph next to Type
4. Press graph key
5. Notice that no outliers are drawn (there are 2 outliers: 1 and 16)
<img width="738" alt="Screenshot 2024-05-31 at 00 16 43" src="https://github.com/CE-Programming/CEmu/assets/171272089/a4550bf5-9cfc-43cc-b5e6-5293ef424546">
<img width="553" alt="Screenshot 2024-05-31 at 00 20 48" src="https://github.com/CE-Programming/CEmu/assets/171272089/b1ea3ff7-a9c8-4796-ad1f-8e1bf097cabb">
<img width="405" alt="Screenshot 2024-05-31 at 00 19 09" src="https://github.com/CE-Programming/CEmu/assets/171272089/cd476b06-fdd1-4e87-bc3d-a1e5e5e3f714">

Any logs, error output, screenshot, other comments...?  No
------------------------------------------------------
…

**Comment by adriweb** [comment]
Well this is a potential issue with TI's OS not with the emulator. CEmu isn't affiliated with TI.
So try contacting them: ti-cares@ti.com

**Comment by paulybrowneyes** [comment]
Sorry, I made a mistake in data entry.  This is not a bug.
<img width="551" alt="Screenshot 2024-05-31 at 08 26 12" src="https://github.com/CE-Programming/CEmu/assets/171272089/bf140738-0c96-42b5-bd7b-1fa9b4b4408b">
