### ISSUE TITLE
Option to disable keyboard inputs

### ISSUE THREAD

**Issue by Void2258** [CE-Programming/CEmu#481]
Maybe it's just my brain, but mapping the calculator inputs to a normal keyboard makes no sense; either I instinctively type normally or can't track which keys correspond to what, so I can't really use the keyboard ad have to just use the mouse. There is an option to export a keyboard mapping, but no way to import it (so not sure how to change anything) and I am more looking to just turn it off entirely.

I just want to use the mouse alone and not have to worry about accidentally focusing the wrong window. Could we get an option to disable keyboard input or at least restrict to number keys or the numpad?

Windows 10
CEmu 1.3

**Comment by adriweb** [comment]
This is such a ~~crazy~~original request, we've never had this suggestion in 9 years. But I guess why not....

**Comment by mateoconlechuga** [comment]
> but no way to import it

Just select the "custom" keybinding option in settings to import. Closing because you can do this already.

**Comment by adriweb** [comment]
(Also, until v2.0 comes out (soon), you should use CEmu nightly not the latest release (1.3), it will be a much better experience)

**Comment by mateoconlechuga** [comment]
Also if you aren't sure what keybindings are what, they are listed right here: https://github.com/CE-Programming/CEmu/wiki/Keybindings
