### ISSUE TITLE
Building using CMAKE 

### ISSUE THREAD

**Issue by Cipher66hz** [CE-Programming/CEmu#488]
---------------------------------------------
Operating System: …   
**Linux Mint  21.3**

CEmu version: … 
 **1.3**

Describe your issue:  
**Unable to build, QT-creator/qmake requires an account. In the documentation it states that a user can use cmake, but does not elaborate on this:**
"(Note that you can also use CMake if you want - check the CI for an example)"  
There is no example it seems ^^^ 

What are the steps to reproduce this issue?
-------------------------------------------
1. … Attempt to build the package using cmake, on a system that does not have QT-Creator installed.

Any logs, error output, screenshot, other comments...?
------------------------------------------------------
If y'all could further elaborate in the documentation about building using cmake that'd be great :D 

**_Thank you so much_**

**Comment by adriweb** [comment]
Right, we literally just revamped all that actually. We'll update the docs. You don't need Qt Creator at all.

**Comment by Cipher66hz** [comment]
> Right, we literally just revamped all that actually. We'll update the docs. You don't need Qt Creator at all.

Sweet. I actually ended up installing QT-Creator through Flatpak without having to make an account for it.

I was wondering if it would be possible to make a Desktop launcher for immediately running CEmu as an executable of sorts. To where I dont need to open QT-Creator , and can just start up my calculator. f so, would you be able to point me in the right direction as to how to achieve this? If not, thats fine :)

Thanks so much! :D

**Comment by Cipher66hz** [comment]
>    Right, we literally just revamped all that actually. We'll update the docs. You don't need Qt Creator at all.

Sweet. I actually ended up installing QT-Creator through Flatpak without having to make an account for it.

I was wondering if it would be possible to make a Desktop launcher for immediately running CEmu as an executable of sorts. To where I dont need to open QT-Creator , and can just start up my calculator. f so, would you be able to point me in the right direction as to how to achieve this? If not, thats fine :)

Thanks so much! :D

**Comment by adriweb** [comment]
To answer this specific question here, the easiest solution would be to move/copy the built CEmu binary file into a folder that's in your PATH env var (maybe /usr/bin, /usr/local/bin, or 
similar), so that you can launch CEmu from your terminal directly. (This should work especially well with the static linux builds we provides in the releases however).
Something like https://github.com/probonopd/linuxdeployqt might also help. but that's out of our scope I guess.

As for desktop files, I think we had something at some point, I forgot...

**Comment by adriweb** [comment]
As for desktop files, we have something here: https://github.com/CE-Programming/CEmu/tree/master/gui/qt/resources/linux

**Comment by adriweb** [comment]
The build instructions page on the wiki has been updated: https://github.com/CE-Programming/CEmu/wiki/Building-CEmu
