### ISSUE TITLE
Add official scoop portable installer (sample manifest included)

### ISSUE THREAD

**Issue by milnak** [CE-Programming/CEmu#493]
Not a bug, but a suggestion.  scoop is great, and I've created a manifest for installing cemu.

Install scoop
Do `scoop bucket add milnak 'https://github.com/milnak/scoop-bucket'`
Then `scoop install milnak/cemu`
To see the manifest definition do `scoop cat milnak/cemu`

If that manifest looks good, you might consider submitting it to scoop.

**Comment by adriweb** [comment]
Hi there,

If we were to consider PR'ing the manifest upstream, it would have to be without _certain elements_ you mention/link in there, as that would break the law otherwise ;)

Also, the guidebook link is wrong, it would have to be the CE one.

thanks though, we'll keep that in mind for later!

**Comment by milnak** [comment]
Makes sense to me. What's the link to the CE guidebook?
