### ISSUE TITLE
FEATURE REQUEST: Input Passthrough

### ISSUE THREAD

**Issue by Perodactyl** [CE-Programming/CEmu#495]
**Operating System:** Arch Linux
**CEmu version:** CEmu v2.0 (git: a2072af)

I think that it would be very helpful as Quality-Of-Life if there was a way to connect an actual calculator, run an assembly program on it, and be able to press physical keys which trigger emulator keys. Basically, I want to press "mode" on my calculator and have the emulated one open the "mode" menu.

I understand this might be incredibly difficult as AFAIK there isn't any support for cables and/or physical connections, but maybe with another program like TiLP it might be doable.

**Comment by adriweb** [comment]
If I understood correctly, this is already doable with the SmartPad app on the calc side, and the recently-added SmartPad keymap on CEmu's side.
