### ISSUE TITLE
Missing Menu Bar at Top

### ISSUE THREAD

**Issue by Wootcakes1701** [CE-Programming/CEmu#499]
Not really an issue, but I accidentally checked the option to hid that menu at the top and now I can't figure out for the life of me how to get it back. I tried right clicking to bring up all the menu options, but none of those options will get me back to the actual settings menu so that I can uncheck the "hide menu bar" option. I even tried re-downloading the .exe but it kept all the settings. How can I get the menu bar back at the top? Thanks!

**Comment by adriweb** [comment]
You can right-click on the emulated screen.
