### ISSUE TITLE
v2.0 windows 7 build does not work

### ISSUE THREAD

**Issue by aleczdr** [CE-Programming/CEmu#500]
(Thanks for reporting an issue! Please make sure to fill out the blanks below.)

What's wrong, and with what software version?
---------------------------------------------
Windows 7 SP1 x64
CEmu 2.0 x64 Qt5

CEmu fails to launch. Windows displays a command prompt and an error dialog stating that _The procedure entry point CreateFile2 could not be located in the dynamic link library KERNEL32.dll_

What are the steps to reproduce this issue?
-------------------------------------------
1. Download WIndows 7 Qt5 Build
2. Launch

Any logs, error output, screenshot, other comments...?
------------------------------------------------------
![image](https://github.com/user-attachments/assets/1ca41204-3a0b-4772-8fbc-952bd864cc13)

**Comment by mateoconlechuga** [comment]
Windows 7 has been EOL for 4 years. There is no point in us trying to support it.

**Comment by adriweb** [comment]
Yeah definitely no specific effort should be spent on supporting obsolete stuff, I'm just curious if having the CI use the older windows image is enough though.
