### ISSUE TITLE
CEmu fails under Qt 6.8.0

### ISSUE THREAD

**Issue by myclevorname** [CE-Programming/CEmu#502]
(Thanks for reporting an issue! Please make sure to fill out the blanks below.)

What's wrong, and with what software version?
---------------------------------------------
**Operating System:** NixOS revision dc460ec76cbff0e66e269457d7b728432263166c
**CEmu version:** v3.0-dev (actually x2.0(, also replicated on revision 1aa39a3a631d4f3e0f4c6ec9e0186404c324b061
**Describe your issue:**  Under both Wayland and X11, CEmu segfaults when trying to move docks on NixOS. This is likely due to the fact that NixOS Unstable switched to Qt 6.8.0.

What are the steps to reproduce this issue?
-------------------------------------------
1. Install Nix
2. Enable flakes
3. Run `nix run github:NixOS/nixpkgs/dc460ec76cbff0e66e269457d7b728432263166c#cemu-ti`
4. Try to move a dock from one window to another

Any logs, error output, screenshot, other comments...?
------------------------------------------------------

[CEmu under Wayland](https://github.com/user-attachments/assets/0258c5a4-1547-4097-a340-1c682859e083)
[CEmu under X11](https://github.com/user-attachments/assets/a6f2b2df-e79c-4e49-a7a4-7de0c32ea3e1)

I know that CEmu currently doesn't support Qt 6.8, but this is an issue with a(n unofficial package), but this issue should be left open for the time CEmu uses Qt 6.8, as well as the fact that it is a package on a Linux distro.

**Comment by mateoconlechuga** [comment]
not out resposibility to be package maintainers outside of this repository.
