### ISSUE TITLE
ERR: VERSION

### ISSUE THREAD

**Issue by rickalex21** [CE-Programming/CEmu#507]
(Thanks for reporting an issue! Please make sure to fill out the blanks below.)

What's wrong, and with what software version?
---------------------------------------------
**Operating System:** …  MAC OS 15.1.1
**CEmu version:** … (see in the `About CEmu` menu)   V2.0
**Describe your issue:**  

Trying to send the program when I send it and try to run it I get:

```text
ERR: VERSION
1: Quit
```

What are the steps to reproduce this issue?
-------------------------------------------
1. Download program dump using CEmu
2. Send to TI-84 Plus Silver Edition Software 2.55
3. Run the program

**Comment by mateoconlechuga** [comment]
Not an issue with CEmu, it's an issue with the program you are trying to run. What program are you using?

**Comment by adriweb** [comment]
CEmu and its dumper program anre only for the CE calculator models, not the 84+ Silver Edition.

**Comment by rickalex21** [comment]
@adriweb  Is there something similar for the 84+ Silver Edition?

Thanks

**Comment by debrouxl** [comment]
For dumping your calculator model, the ROM dumper in TILP (technically, libticalcs, which underlies TILP) works.
For emulating your calculator model... in general, TilEm, part of the same family as libti* and TILP, is an option, but MacOS isn't its favorite platform, AFAIK.

**Comment by adriweb** [comment]
Well, Tilem does work fine on macOS, I recently built/tried it just fine :) Some online emulators exist though, for instance jsTIfied.
For Tilp, you can check https://tipla.net/tilpinst

**Comment by rickalex21** [comment]
@adriweb  I don't use Mac, I use nixos but I was troubleshooting on mac to see if I can get a ROM to use it on Linux.

jsTIfied looks good but I need a ROM.

 There's issues with TiLP for nixos: https://github.com/NixOS/nixpkgs/issues/76098#issuecomment-2502152178

My use case was to have a TI-84+ Silver Edition emulator on nixos so I won't need to have my calculator with
me. I'm use to now,  having a mac next to me to transfer files with Ti CE connect. 

I think I will just have to do it like this for the next couple of days.

Thanks

**Comment by myclevorname** [comment]
Good news: I re-added TILP into Nixpkgs with the package name `tilp` instead of `tilp2`. It will take a while to get into nixos-unstable.
