### ISSUE TITLE
Placing calculator in SHIP mode does not emulate correctly

### ISSUE THREAD

**Issue by MateoConLechuga** [CE-Programming/CEmu#56]
In the selftest menu, on a real calculator, SHIP mode causes a low-power mode induced in the calculator's state. This does not happen in CEmu, and the trigger for this appears hardware related.

**Comment by adriweb** [comment]
Improved by 4c20f2e

**Comment by adriweb** [comment]
Although if someone could fix the emulation so as not to make it take 100% of the CPU while being in SHIP/low-power-mode, that'd be great :D

**Comment by MateoConLechuga** [comment]
lol it's good enough :) Not many people will enter it for a long time, unless they really want to heat up their computer. Thanks! :)

**Comment by Ivoah** [comment]
It's ironic that putting the emulated calculator into low-power mode eats up the host's CPU/battery

**Comment by Runer112** [comment]
Pegging the CPU during what should be an idle mode is not really appropriate implementation.
