### ISSUE TITLE
Interrupts are broken

### ISSUE THREAD

**Issue by MateoConLechuga** [CE-Programming/CEmu#67]
In OS 5.1.5.0019, at address 084D6E - 084D9C exists the delay loop the OS uses for the Pause command (its second argument, the time to wait in seconds).
The value at `(ix - 05)` contains the number of times to loop for, and D00590 (`apdSubTimer`) is changed by the interrupt controller.
The interrupt generation appears off, or doubled in most cases. This basically means that APD is probably off as well.

Further information: the value at `(ix - 1)` stores the previous value of `apdSubTimer` for comparison.

**Comment by adriweb** [comment]
For some odd reason, I cannot seem to reproduce the timed Pause bug anymore (ie: I get the correct wait time, not twice as much).
Can anyone try having cleared the .ce image file / state?
A program with `Pause "FOO", 2` should be enough
