### ISSUE TITLE
Slowness when using touch-screen (Windows 8.1)

### ISSUE THREAD

**Issue by ghost** [CE-Programming/CEmu#71]
So , I got back.
And found a little bug, sort of.
if I use touchscreen on cemu , it's really slow and bad , I need to tap 3 times to let it work.
(my touchscreen works perfect.)
windows 8.1 because my laptop crashed...

**Comment by adriweb** [comment]
Can you add be more specific about "I need to tap 3 times to let it work"?
Also, is it "really slow and bad" only when using your touchscreen or in general?

**Comment by JaroslavN** [comment]
ok, it's only slow when using touchscreen.
and about that "3 times tapping" thing, I am tapping on the "button" and its reacting on the sides of the "button"    
![naamloos](https://cloud.githubusercontent.com/assets/16990273/15325023/373aa3de-1c49-11e6-87d8-6cfeac2809ac.png)
   tapping 0.5cm from it away
(sorry for my english -_- )

**Comment by MateoConLechuga** [comment]
Has anyone tested this with the recent keypad branch?

**Comment by adriweb** [comment]
Hm, we'd need a Windows build of the keypad branch ; I may be able to do that tomorrow evening, which I'll attach here.
(unless @JaroslavN has already built one?)

**Comment by MateoConLechuga** [comment]
This is probably fixed now. You can reopen it if it is not though

**Comment by sdeutsch354** [comment]
Hi, I'm having this issue now as well. I'm on Windows 10 on my laptop and on my desktop with my smartboard. For me it's double tapping twice and it's an annoyance to me and my students.

**Comment by sdeutsch354** [comment]
I am using the latest stable version. v.1.1.1

**Comment by mateoconlechuga** [comment]
Here's a link to a development build. It would be great if you could test it and let us know if it actually works properly: https://github.com/CE-Programming/CEmu/issues/282#issuecomment-434941651

**Comment by jacobly0** [comment]
Since this issue was about the old keypad, before it was completely rewritten, I'm closing it in favor of #282.
