### ISSUE TITLE
code, little help.

### ISSUE THREAD

**Issue by JaroslavN** [CE-Programming/CEmu#72]
so ,i tried to help: 
![schermopname 32](https://cloud.githubusercontent.com/assets/16990273/15633954/34bc041c-25b9-11e6-86eb-e3f773c89563.png)

**Comment by adriweb** [comment]
It doesn't matter right now, the Nspire port is not supported nor planned currently.
If one day it's brought back to life, it'll be done in a better way anyway (read from an array/"map")
