### ISSUE TITLE
LCD off but emulator working?

### ISSUE THREAD

**Issue by zephirFR** [CE-Programming/CEmu#73]
Hey,
I did everything asked (from downloading the guithub project to putting the rom img of my calculator to the app). Look at my screenshots, it displays "LCD off" and when I press the key "on" nothing happens, but, when in the top menu I select take a screenshot, I can see what I typed, why?
thx!
![testing qwertyuiop](https://cloud.githubusercontent.com/assets/10205873/15930835/4b0218aa-2e98-11e6-8f88-b9d9d27c4d34.gif)
![capture d ecran 2016-06-09 23 09 06](https://cloud.githubusercontent.com/assets/10205873/15930846/5cc78f84-2e98-11e6-9857-4b146f1e0c28.png)

**Comment by adriweb** [comment]
That's the first time I see this - however, taking a screenshot would indeed create a valid screenshot of the content as if the screen were off, because it's just that it's turned off, the content itself is still there. I suppose we could make the screenshot feature check if the screen is turned on first...

I'm noticing you have the `alpha` key pressed. Could you try clicking on that alpha button (if needed, several times), make it not "pressed", then try to click on `on`.

**Comment by zephirFR** [comment]
Thx for the quick response, but no it still doesn't work

**Comment by zephirFR** [comment]
I can't see the screen exept with a screen shot

**Comment by adriweb** [comment]
Alright, that's a bit weird...

Temporary fix so that you can at least see the screen: edit your `gui/qt/qtframebuffer.cpp` file.
At line 29: `if (lcds && (lcd.control & 0x800) && !asic.shipModeEnabled) {`, replace it by `if (true) {`

What do you have in the settings tab?

**Comment by zephirFR** [comment]
![capture d ecran 2016-06-10 06 56 14](https://cloud.githubusercontent.com/assets/10205873/15946078/76180d8e-2ed8-11e6-9fa9-f1832930fe67.png)
settings tab before editing line

**Comment by zephirFR** [comment]
Do I have to rebuild the file?

**Comment by zephirFR** [comment]
![capture d ecran 2016-06-10 06 59 57](https://cloud.githubusercontent.com/assets/10205873/15946181/f879b340-2ed8-11e6-9116-dd82c680473a.png)
Is that it?

**Comment by adriweb** [comment]
Replace the whole line by  `if (true) {`
And yes, then you have to rebuild (Were you using Qt Creator ? or the `qmake` command?) Anyway, whichever you did at first to get the application to build, you can do the same, it should take into account the change.

**Comment by adriweb** [comment]
I see no issues with your settings screenshot, by the way.

**Comment by adriweb** [comment]
Okay, I have found the issue, however I don't know why it's there...
You can go back to the original code (the line 29), basically you just need to check the "PWR" checkbox of the calculator when that happens (and when it shouldn't be off).

To do that, Go to the `Debug` tab, under `Misc`, then check the `PWR` box in the LCD group.
![LCD Power](https://i.imgur.com/QNuenzN.png)

**Comment by zephirFR** [comment]
thx it works!
