### ISSUE TITLE
Groups aren't correctly handled in PC->Emu transfers

### ISSUE THREAD

**Issue by adriweb** [CE-Programming/CEmu#77]
As [reported](https://codewalr.us/index.php?topic=965.msg42103#msg42103) by DJ_Omnimaga:
> Bug report: Emulator doesn't handle 8xg file transfer properly. When sending a 8xg file to the calculator, it only ungroups the first program that was in it. Also there's no way to send the group without auto-ungrouping it.

My thought:
> Hm, yeah, I think that makes sense: in `sendVariableLink()` (link.c), the file size isn't read, only the var size at 0x39, which corresponds, in a group, to the first variable.
Since groups are just files concatenated, it might be enough to just loop on that main part of the code as long as more variables are there...

**Comment by MateoConLechuga** [comment]
Do we want to ungroup them or send them like a normal file? I think it makes more sense to receive a group as a hardware calculator would, and then ungroup manually from within the emulator.

**Comment by adriweb** [comment]
Funny thing is that TI-Connect CE will ungroup some 8xg (I don't remember on top of my head what the condition is) before sending the files in it.
So in theory, both behaviors are acceptable, I guess. It could even be a setting checkbox.

**Comment by MateoConLechuga** [comment]
I have not had this issue. Please provide a .8xg file where this fails. Thanks

**Comment by adriweb** [comment]
Here is a .8xg file that doesn't get transferred properly (only the first variable inside does).
[bad_group.zip](https://github.com/CE-Programming/CEmu/files/427655/bad_group.zip)

In TI-Connect CE, it gets auto-ungrouped before transfer when I drag'n'drop the 8xg:
![screenshot](https://i.imgur.com/o4AyDvi.png)

**Comment by MateoConLechuga** [comment]
Well, sometimes a .8xg is a concatenation of variables directly, and other times it is a variable in itself... What in the world. I guess some parsing code to differentiate and analyze the two types will have to be written :P
