### ISSUE TITLE
Compile Issue on Ubuntu x64

### ISSUE THREAD

**Issue by firestar115** [CE-Programming/CEmu#78]
I Googled it, and the only relevant thing I could find was a failed build of this program:

    $ make
    g++ -m64 -Wl,-z,relro -Wl,-z,now -Wl,-z,noexecstack -Wl,--gc-sections -pie -g3 -W -Wall -Wno-unused-parameter -Werror=shadow -Werror=write-strings -Werror=redundant-decls -Werror=format -Werror=format-security -Werror=declaration-after-statement -Werror=implicit-function-declaration -Werror=date-time -Werror=missing-prototypes -Werror=return-type -Werror=pointer-arith -Winit-self -ffunction-sections -fdata-sections -fno-strict-overflow -O3 -flto -fPIE -Wstack-protector -fstack-protector-strong --param=ssp-buffer-size=1 -Wl,-O1 -o CEmu utils.o main.o mainwindow.o romselection.o qtframebuffer.o lcdwidget.o emuthread.o qtkeypadbridge.o qmlbridge.o keymap.o datawidget.o lcdpopout.o searchwidget.o basiccodeviewerwindow.o chunks.o commands.o qhexedit.o gif.o utils_tivarslib.o TH_0x00.o TH_0x05.o autotester.o asic.o cpu.o keypad.o lcd.o registers.o port.o interrupt.o flash.o misc.o schedule.o timers.o usb.o sha256.o realclock.o backlight.o cert.o control.o mem.o link.o vat.o emu.o extras.o disasm.o debug.o stepping.o os-linux.o qrc_resources.o moc_mainwindow.o moc_romselection.o moc_lcdwidget.o moc_emuthread.o moc_qmlbridge.o moc_datawidget.o moc_lcdpopout.o moc_searchwidget.o moc_basiccodeviewerwindow.o moc_commands.o moc_qhexedit.o   -L/usr/X11R6/lib64 -lQt5QuickWidgets -lQt5Quick -lQt5Widgets -lQt5Gui -lQt5Qml -lQt5Network -lQt5Core -lGL -lpthread 
    ../../core/cpu.h:46:1: warning: type ‘struct eZ80cpu’ violates one definition rule [-Wodr]
     PACK(typedef ALIGNED_(8) struct eZ80cpu {
     ^
    ../../core/cpu.h:72:4: note: a type with different alignment is defined in another translation unit
     }) eZ80cpu_t;
        ^
    tivarslib/TypeHandlers/TH_0x05.cpp: In function ‘reindentCodeString’:
    /usr/include/c++/5/bits/regex.h:2478:7: warning: ‘end._M_position._M_pregex’ may be used uninitialized in this function [-Wmaybe-uninitialized]
           regex_iterator(const regex_iterator& __rhs) = default;
           ^
    tivarslib/TypeHandlers/TH_0x05.cpp:134:31: note: ‘end._M_position._M_pregex’ was declared here
             sregex_token_iterator end;
                                   ^
    /usr/include/c++/5/bits/regex.h:2478:7: warning: ‘MEM[(struct regex_token_iterator *)&end + 24B]’ may be used uninitialized in this function [-Wmaybe-uninitialized]
           regex_iterator(const regex_iterator& __rhs) = default;
           ^
    tivarslib/TypeHandlers/TH_0x05.cpp:134:31: note: ‘MEM[(struct regex_token_iterator *)&end + 24B]’ was declared here
             sregex_token_iterator end;
                                   ^
    lto1: internal compiler error: in splice_child_die, at dwarf2out.c:4914
    Please submit a full bug report,
    with preprocessed source if appropriate.
    See <file:///usr/share/doc/gcc-5/README.Bugs> for instructions.
    lto-wrapper: fatal error: g++ returned 1 exit status
    compilation terminated.
    /usr/bin/ld: error: lto-wrapper failed
    collect2: error: ld returned 1 exit status
    Makefile:366: recipe for target 'CEmu' failed
    make: *** [CEmu] Error 1

How do I fix this error? I would really like to start developing and testing programs with my calculator on days other than Thursday (the only day I have access to a Mac).

**Comment by jacobly0** [comment]
This is a g++ bug. Removing the -g3 should allow it to work.
