### ISSUE TITLE
The "download" site doesn't work

### ISSUE THREAD

**Issue by JaroslavN** [CE-Programming/CEmu#79]
I came back and, this link isn't working anymore to download the CEmu builds http://pimathbrainiac.me/CEmu/

**Comment by adriweb** [comment]
It's known, the server isn't available anymore.
Nightly builds will be made once we spend time on auto deployment from travis, for instance (@alberthdev and I were talking about it at some point)

**Comment by alberthdev** [comment]
If you don't mind MSVC builds, I have them hosted here:
http://tiny.cc/CEmuMSVC

Builds are made whenever my mini fork gets updated:
https://github.com/alberthdev/CEmu

**Comment by MateoConLechuga** [comment]
Closing :)
