### ISSUE TITLE
Crash while sending files in specific conditions

### ISSUE THREAD

**Issue by adriweb** [CE-Programming/CEmu#84]
Just so that we don't forget about it... (bug also confirmed by Mateo)

> 19:32:13 Adriweb> anyway, maybe you can try: transfer a bunch of files (like, 20), while speed is unthrottled
> 19:32:44 Adriweb> in fact, when I tried, I hadn't finished DnD'ing the files that the calc went into sleep mode
> 19:32:55 Adriweb> then, the initial transfers failed
> 19:33:00 Adriweb> because the calc was off.
> 19:33:09 Adriweb> but then it turned on by itself eventually
> 19:33:18 Adriweb> and CEmu crashed shortly after
> [...]
> 19:38:09 Adriweb> apparently in SendingHandler::sendFiles
> 19:38:32 Adriweb> at/around the `fread`, it looks like.
> 19:38:43 Adriweb> (for some reason, I don't have source debugging...)
> 19:38:59 Adriweb> it's actually crashing in a memmove, but that's inside `fread`.
> 19:39:24 Adriweb> it may just be the OS timing out on the DnD handler, though that would be somewhat weird :P

Anyway, we should check that the calc is on before starting transfers (and turn it on if it isn't), it may be a workaround to this issue, at least partially.

**Comment by MateoConLechuga** [comment]
I can no longer do this :/
