### ISSUE TITLE
Stepping is broken

### ISSUE THREAD

**Issue by MateoConLechuga** [CE-Programming/CEmu#85]
Yeah.... There's a lot of cases where it fails... And after a few minutes the run button no longer works....

**Comment by jacobly0** [comment]
Also, stepping over prefixed block instructions is broken.

**Comment by MateoConLechuga** [comment]
Everything is broken, isn't it :/

**Comment by MateoConLechuga** [comment]
Just step out and stepping with interrupts seems broken now

**Comment by MateoConLechuga** [comment]
Okay; there seems to be nothing wrong with stepping now other than having weird things like `call _ \ _: ret`

**Comment by MateoConLechuga** [comment]
Everything now appears to be properly handled. Closed for now.
