### ISSUE TITLE
Wiki page to document keybindings

### ISSUE THREAD

**Issue by adriweb** [CE-Programming/CEmu#87]
Before the v1.0 release, we also have to create a [Keybindings](https://github.com/CE-Programming/CEmu/wiki/Keybindings) page on the wiki documenting them.
At the very least, [the CEmu ones](https://github.com/CE-Programming/CEmu/blob/master/gui/qt/keypad/keymap.cpp#L34-L94) (<- code).

_(tagged with the 'hacktoberfest' label in case someone wants to help :P)_

**Comment by adriweb** [comment]
@MateoConLechuga and I think it might be good to have it in some kind of an image format (in addition to a raw "list", maybe)

**Comment by MateoConLechuga** [comment]
Added a table to the [Keybindings](https://github.com/CE-Programming/CEmu/wiki/Keybindings) page. I think it looks fine as is without the need for an image.

**Comment by adriweb** [comment]
Yeah, it's good enough for now :)
Also, I improved the table a little bit.
