### ISSUE TITLE
Substitute (or even replace) Helvetica Neue with an open font

### ISSUE THREAD

**Issue by alberthdev** [CE-Programming/CEmu#91]
Some discussion on IRC spawned this issue - basically, the current font, Helvetica Neue, is not generally available on most systems, and the alternative currently listed (Open Sans) does not look very good. (The font seems to be available on Mac, but is potentially too condensed; Linux seems to look the best, but is certainly not using the commercial font unless it is manually installed.) The goal is to (hopefully) make the keypad look consistent across platforms.

One alternative is Liberation Sans Narrow Bold ([license](https://fedoraproject.org/wiki/Licensing:LiberationFontLicense?rd=Licensing/LiberationFontLicense)), which seems to look very much alike with the original font. (See: [original (Linux screenshot lookalike)](https://www.linotype.com/53866/frutiger-next-condensed-bold-product.html) and [free version](http://www.ffonts.net/Liberation-Sans-Narrow-Bold.font?text=stat%20plot).)

It looks like Qt does allow for font embedding, assuming we specify the right font name. Each Liberation Sans Narrow font is 108-131 KB (Regular, Bold, Italic, BoldItalic), so the footprint isn't _too_ bad. Combined with Qt's resource compression, I think embedding this font could be a real possibility.

IRC discussion:

```
<alberthro> hmm... do you think we can embed a free font to replace helvetica? cuz compared to the helvetica font, open sans looks kinda weird...
<MateoC> Possibly :)
<alberthro> helvetica neue (https://www.linotype.com/53866/frutiger-next-condensed-bold-product.html) vs. http://www.ffonts.net/Liberation-Sans-Narrow-Bold.font?text=stat%20plot
<alberthro> did a side by side comparison with "stat plot", looks pretty similar!
<MateoC> That would be awesome :)
<Runer112> what's wrong with helvetica
<alberthro> not always installed on systems, even windows
<Runer112> seems unlikely
<alberthro> given that my VM's Windows 7 doesn't have it, then.... :p
<MateoC> It's not on my windows 7
<Runer112> wut
<Runer112> it's not on mine either..?
<Runer112> is this a mac thing
<Runer112> this is a mac thing isn't it
<MateoC> It's a linux thing
<alberthro> (and maybe a mac thing)
<alberthro> linux is just clever enough to find some random substitute, cuz I highly doubt that a commercial font is distributed in distros...
<alberthro> mac seems to have a weird type: https://i.imgur.com/LznBl5u.png
<alberthro> linux looks the nicest of them all, but not sure what's the underlying font: https://i.imgur.com/26sioCw.png
<alberthro> and windows... ehh https://cloud.githubusercontent.com/assets/1274384/19636682/d2a7366c-9998-11e6-91f5-8737a694a262.png
<Runer112> mac could look weird because of the semi-condensed thing
<Runer112> is that still there
<Runer112> I don't know why it was
<Runer112> by the way, theta is supposed to be italicized
<alberthro> or actually, maybe open sans looks nice on Linux :p
```

**Comment by MateoConLechuga** [comment]
This sounds like a reasonable solution to me :)

**Comment by adriweb** [comment]
Just re-opening that not to forget to fix the Windows display "issues" of the new font :D

**Comment by alberthdev** [comment]
Update from previous - we're using this font, but Windows still looks ugly because Qt doesn't really know how to handle this font on Windows, and/or Windows renders it awfully.

IIRC, pimath's builds (and likely jacobly's as well) statically includes Freetype, and their builds look perfectly fine I believe... so my next step is probably to try and re-build Qt with embedded Freetype support so that it ends up using that instead of Windows to render the font. Hopefully we'll end up with font rendering that looks much better, if not comparable to how it looks in Linux!

**Comment by alberthdev** [comment]
Some updates:

 * As it turns out, FreeType2 was being included in Qt after all! However, because of GDI being the preferred and default method of rendering text in Qt, FreeType2 is never used unless you invoke a particular command line option, aka `-platform windows:fontengine=freetype`.
   * No wonder Qt is trying hard to make their configuration easier... embedding a full copy of FreeType2 and never really using it!
 * Enabling FreeType2 usage strictly requires a command line option - looked around and there doesn't seem to be any other way of setting the FreeType2 engine. I have an uncommitted hack that injects the correct CLI argument into QApplication() (and doesn't affect functionality), but it's really a nasty hack...
 * Fonts do look better on the keypad, but it impacts the whole GUI, and now the GUI looks somewhat foreign on win32. Not to mention that the keypad looks *better*, but not *great*.
 * One interesting project to note that has this problem: MuseScore. They took a [very interesting route](https://github.com/musescore/musescore/commit/eff562e) to making this work. Corresponding issue [here](https://musescore.org/en/node/43661), and as of 2 days ago (!!, 4/15/17) they are just as [confused](http://dev-list.musescore.org/Qt-and-OpenType-td7579162.html) as we were about the current state of Qt font rendering on Windows...
   * AFAIK, from my digging into Qt + FreeType2, it doesn't provide any direct access - all of the FreeType2 functionality is abstracted and hidden away.
   * If we do decide to use FreeType2 (+Harfbuzz?) directly, hopefully there is some way we can leverage the existing Qt build to access this functionality (w/o building FreeType2 separately)...

More to come...

**Comment by mateoconlechuga** [comment]
It looks like they were able to fix this issue [here](https://github.com/musescore/musescore/commit/eff562e). Perhaps I'll take a stab at getting something like that working.

**Comment by garethcollins** [comment]
I am curious - Is there a workaround for this? Any way I can change the font? I have three Windows computers - one where the keys are correct (Windows 8.1)...and two others where I can't see the keys (one Windows 8.1 and one Windows 10). None of the three computers have "Helvetica Neue" installed...so I don't know how the Windows 8.1 machine works.

**Comment by adriweb** [comment]
Could you check if you have a dedicated GPU on the computer that correctly displays the font?
And also check that on the other ones not correctly displaying it, the computers have an integrated one?

**Comment by garethcollins** [comment]
The Windows 8.1 desktop  which works has a dedicated Nvidia GPU. The Windows 8.1 laptop which doesn't work does not have a dedicated GPU. The Windows 10 laptop which doesn't work does have a Nvidia GPU (Nvidia GTX 950M).

**Comment by adriweb** [comment]
That's... a bit unexpected. Maybe the Win10 laptop with the 950M was running on the integrated one though (dGPU didn't get activated for CEmu).
Basically, most of the time for things like that it's rendering issues on some iGPU (and I guess 2 of your tries confirm that).
In any case, it's annoying, especially since it's windows only.

**Comment by garethcollins** [comment]
Perhaps these settings are being ignored, but I have tried to explicitly run with the Nvidia GPU in the Context Menu Settings. I also setup the NVIDIA Control Panel to force CEmu to run with the Nvidia GPU. I still cannot get it to display properly. Anything else you suggest I could try?

**Comment by adriweb** [comment]
Maybe then Win10 changed something related to font rendering, regardless of the GPU (which would be even more annoying)... I currently don't have any morea ideas of tests or solutions (have you tried some things from @alberthdev's comment above ?)
Anyway, hopefully we'll be able to work on that if we have new ideas, or even just workarounds

**Comment by alberthdev** [comment]
@garethcollins Out of curiosity, could you take a screenshot of the messed up display/font? Also, what build are you using? Are you using jacobly's builds (e.g. http://jacobly.com/CEmu/master/latest/CEmu64.exe or http://jacobly.com/CEmu/master/latest/CEmu32.exe) or are you using one of the older Qt builds (e.g. https://oss.jfrog.org/artifactory/oss-snapshot-local/org/github/alberthdev/cemu/git/)?

Also - can you try [this build](https://oss.jfrog.org/artifactory/oss-snapshot-local/org/github/alberthdev/cemu/git-test/201610/20161025/cemu-20161025_023237-git-b5d48d4/)? This is a very very old build, but it contains some test fixes to this issue. Combine this build with the command line option `-platform windows:fontengine=freetype` and see if that helps.

**Comment by garethcollins** [comment]
I am using joacobly's 64 bit build (http://jacobly.com/CEmu/master/latest/CEmu64.exe) which is linked to in the README. I will get some screenshots and try the older build sometime later today. Thanks!

**Comment by runer112** [comment]
@alberthdev That build fixes the problem for me, with no command line options needed. I'm running Windows 10 with an NVIDIA card and graphics switching, so CEmu probably gets integrated Intel graphics.

**Comment by garethcollins** [comment]
@alberthdev The old build works fine for me on my windows 10 laptop without
the -platform windows:fontengine=freetype parameter. When I add the
parameter I can't see any keys at all (with the latest build I can see the
numbers, but all other keys are messed up).

**Comment by garethcollins** [comment]
![cemu64-latest](https://user-images.githubusercontent.com/1203506/30871624-7e4518f6-a2b5-11e7-9c28-76b93bc6e087.jpg)
![cemuold-freetype](https://user-images.githubusercontent.com/1203506/30871638-827c8ecc-a2b5-11e7-854b-6410f8a6b97b.jpg)

Attached are the screenshots, the first from the old release with freetype, the second from the current CEmu64.exe

**Comment by garethcollins** [comment]
For reference here is a screenshot from the old release, no freetype param
![cemuold](https://user-images.githubusercontent.com/1203506/30871813-1330d89c-a2b6-11e7-9545-934f9ce14363.png)

**Comment by adriweb** [comment]
Okay....

And what if you try a build from here : https://oss.jfrog.org/artifactory/oss-snapshot-local/org/github/alberthdev/cemu/git/201709/20170925/cemu-20170925_230412-git-9cbcf39/ ?

if it's good, something's going wrong with jacobly's cross-builds, if it's not, we'll have to try things with a git bisect to see where things started to go bad on windows...

**Comment by garethcollins** [comment]
OK, the one from artifactory is better.
![cemuartifactory](https://user-images.githubusercontent.com/1203506/30878602-1cfc41d0-a2cb-11e7-8171-89f68aa115b1.jpg)

**Comment by alberthdev** [comment]
Please try these builds and see if it looks like the older build I sent you:
https://oss.jfrog.org/artifactory/oss-snapshot-local/org/github/alberthdev/cemu/git/201709/20170928/cemu-20170928_054954-git-fc512ee/

**Comment by adriweb** [comment]
Here's a potentially helpful comment about this: https://www.cemetech.net/forum/viewtopic.php?p=263705#263705

@garethcollins any news btw?

**Comment by garethcollins** [comment]
Sorry, I didn't see the comment. I will check this evening.

**Comment by alberthdev** [comment]
@adriweb: Regarding the post you linked, the interesting part for reference:

> The windows console for CEmu84.exe states: 
setGeometry: Unable to set geometry 3075x2493+597+207 on QWidgetWindow/'MainWindowWindow'. Resulting geometry: 3075x2108+597+207 (frame: 16, 72, 16, 16, custom margin: 0, 0, 0, 0, minimum size: 894x605, maximum size: 16777215x16777215). 
> 
> Any idea how to fix this so I can see the labels on the keys? 
> 
> Windows 10, screen 3840 x 2160 
> 
> Thank you for any suggestions, and thank you for such an awesome tool ! 
> 
> EDIT: OK... Must be some kind of scaling issue, as stated above. If i run the CEmu program with the screen at 2048 x 1152 then all looks fine. If I then resize the screen back to native, things get weird and truncated but the labels on the keys are preserved. 
> 
> Any way to make it look correct on the native resolution?

Looking at our code, it doesn't look like we should be causing this:
```
$ grep -r setGeometry .
./gui/qt/ui_mainwindow.h:        menubar->setGeometry(QRect(0, 0, 1004, 22));
./gui/qt/ui_mainwindow.h:        calcSkinTop->setGeometry(QRect(0, 0, 440, 351));
./gui/qt/ui_mainwindow.h:        lcdWidget->setGeometry(QRect(60, 78, 320, 240));
```
DPI related code:
```
$ grep -r -i DPI .
./gui/qt/main.cpp:    // DPI scaling fix must be applied at the very beginning before QApplication init
./gui/qt/main.cpp:    QCoreApplication::setAttribute(Qt::AA_EnableHighDpiScaling);
./gui/qt/main.cpp:    app.setAttribute(Qt::AA_UseHighDpiPixmaps);
./gui/qt/mainwindow.ui:                   <string>cmdPixelShadow2</string>
./gui/qt/main.cpp.orig:    app.setAttribute(Qt::AA_UseHighDpiPixmaps);
```

I'm kinda certain that this might just be a Qt bug somewhere, since we're not directly influencing much...

**Comment by garethcollins** [comment]
@alberthdev @adriweb That build worked fine too. Thanks!

**Comment by garethcollins** [comment]
My windows 10 machine is high res as well (3840x2160)

**Comment by mateoconlechuga** [comment]
It seems to not work well on high res screens. I don't have a high res screen (1366x768 or something); so this issue has never appeared for me.

**Comment by adriweb** [comment]
@garethcollins are the labels narrow too or do they look normal? As in, like the other build you tried.
(in any case, it's better than nothing...)

**Comment by garethcollins** [comment]
Perhaps a little narrow but it doesn't bother me...

**Comment by alberthdev** [comment]
Try [one of these builds](https://oss.jfrog.org/artifactory/oss-snapshot-local/org/github/alberthdev/cemu/git/201710/20171005/cemu-20171005_024840-git-9b38ec8/) and see if that gets closer (or even matches) the older release spacing! I have an odd feeling about this particular build...

**Comment by mateoconlechuga** [comment]
*bump*

**Comment by garethcollins** [comment]
@alberthdev That looks better, yes. What did you change?
![cemu64-1005](https://user-images.githubusercontent.com/1203506/31312256-2f11c8e4-ab8c-11e7-9c6f-7d144add65bd.jpg)

**Comment by mateoconlechuga** [comment]
Looks like this change? https://github.com/CE-Programming/CEmu/commit/9b38ec81d1ce1e09deecb047698ca0decc068e53

**Comment by alberthdev** [comment]
@garethcollins, @mateoconlechuga: Yup - the old version didn't have any of the embedded font changes we tried to do to make things look better (e.g. [this commit](https://github.com/CE-Programming/CEmu/commit/2f2db3b17cb0eb3b92ccabf8c71ae295eca5e8bc)). I figured that maybe it wouldn't hurt to disable the support 100% on Windows, since it wasn't working in the first place..

If you or anyone else has Windows systems, can you test that build, just to make sure? If this works consistently on other Windows systems, we'll probably commit these changes to master. (And see if this change fixes it for @jacobly0's builds as well!)

**Comment by garethcollins** [comment]
@alberthdev Looks fine on my hi-res windows machine (windows 10) and my old win 8 desktop.

**Comment by mateoconlechuga** [comment]
It looks good on my low-res windows machine and under my high-res windows vm and when running under wine. Closing this issue once and for all :)

**Comment by runer112** [comment]
This issue is still not fixed in @jacobly0's MinGW builds, which are currently the promoted builds on the unofficial site (https://ce-programming.github.io/CEmu/download). This issue is not present in @alberthdev's MSVC builds.
