### ISSUE TITLE
Cemu portable?

### ISSUE THREAD

**Issue by nicoeni** [CE-Programming/CEmu#93]
Is that the configuration file could be place in the same directory as cemu.exe to make Cemu portable?

**Comment by MateoConLechuga** [comment]
I added an option to the settings dock `Use portable configuration`. This will copy the current settings to the same directory as cemu.exe, and will use the rom image as a relative path to the executable. However, it does lock the locations of the calculator image and debugging information to the same directory as well to prevent conflicts. This is easily changeable by deselecting the portable option however.

Related commit: 365e0b7
