### ISSUE TITLE
GPT issues

### ISSUE THREAD

**Issue by MateoConLechuga** [CE-Programming/CEmu#96]
There's some things wrong with the general purpose timers. For instance; although [this program](https://github.com/CE-Programming/toolchain/tree/master/CEdev/examples/demo_7/bin) used to work in CEmu, it no longer does. I can try to find the earliest commit that might have done this, but I think it had to do with fixing latched interrupts.

**Comment by jacobly0** [comment]
Works for me (random full screen color every half second, on to exit).

**Comment by adriweb** [comment]
Works fine for me as well. Same behaviour @jacobly0 described, on both calc and CEmu.

**Comment by MateoConLechuga** [comment]
It doesn't work on windows. I just cleaned everything and force pulled.

**Comment by MateoConLechuga** [comment]
I'm dumb and forgot to latch the timer. Works fine now :P
